//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor, UIImage;

@interface AACustomShareBubble : NSObject
{
    int _customId;
    UIImage *_icon;
    UIColor *_backgroundColor;
}

@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) UIImage *icon; // @synthesize icon=_icon;
@property int customId; // @synthesize customId=_customId;
- (void).cxx_destruct;

@end

