//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSMutableDictionary, UIColor;

@interface AAShareBubbles : UIView
{
    NSMutableArray *bubbles;
    NSMutableDictionary *bubbleIndexTypes;
    UIView *faderView;
    _Bool _showFacebookBubble;
    _Bool _showTwitterBubble;
    _Bool _showMailBubble;
    _Bool _showGooglePlusBubble;
    _Bool _showTumblrBubble;
    _Bool _showVkBubble;
    _Bool _showLinkedInBubble;
    _Bool _showPinterestBubble;
    _Bool _showYoutubeBubble;
    _Bool _showVimeoBubble;
    _Bool _showRedditBubble;
    _Bool _showInstagramBubble;
    _Bool _showFavoriteBubble;
    _Bool _showWhatsappBubble;
    _Bool _isAnimating;
    int _radius;
    int _bubbleRadius;
    int _facebookBackgroundColorRGB;
    int _twitterBackgroundColorRGB;
    int _mailBackgroundColorRGB;
    int _googlePlusBackgroundColorRGB;
    int _tumblrBackgroundColorRGB;
    int _vkBackgroundColorRGB;
    int _linkedInBackgroundColorRGB;
    int _pinterestBackgroundColorRGB;
    int _youtubeBackgroundColorRGB;
    int _vimeoBackgroundColorRGB;
    int _redditBackgroundColorRGB;
    int _instagramBackgroundColorRGB;
    int _favoriteBackgroundColorRGB;
    int _whatsappBackgroundColorRGB;
    id <AAShareBubblesDelegate> _delegate;
    UIView *parentView;
    NSMutableArray *_customButtons;
    double _faderAlpha;
    UIColor *_faderColor;
}

@property(nonatomic) int whatsappBackgroundColorRGB; // @synthesize whatsappBackgroundColorRGB=_whatsappBackgroundColorRGB;
@property(nonatomic) int favoriteBackgroundColorRGB; // @synthesize favoriteBackgroundColorRGB=_favoriteBackgroundColorRGB;
@property(nonatomic) int instagramBackgroundColorRGB; // @synthesize instagramBackgroundColorRGB=_instagramBackgroundColorRGB;
@property(nonatomic) int redditBackgroundColorRGB; // @synthesize redditBackgroundColorRGB=_redditBackgroundColorRGB;
@property(nonatomic) int vimeoBackgroundColorRGB; // @synthesize vimeoBackgroundColorRGB=_vimeoBackgroundColorRGB;
@property(nonatomic) int youtubeBackgroundColorRGB; // @synthesize youtubeBackgroundColorRGB=_youtubeBackgroundColorRGB;
@property(nonatomic) int pinterestBackgroundColorRGB; // @synthesize pinterestBackgroundColorRGB=_pinterestBackgroundColorRGB;
@property(nonatomic) int linkedInBackgroundColorRGB; // @synthesize linkedInBackgroundColorRGB=_linkedInBackgroundColorRGB;
@property(nonatomic) int vkBackgroundColorRGB; // @synthesize vkBackgroundColorRGB=_vkBackgroundColorRGB;
@property(nonatomic) int tumblrBackgroundColorRGB; // @synthesize tumblrBackgroundColorRGB=_tumblrBackgroundColorRGB;
@property(nonatomic) int googlePlusBackgroundColorRGB; // @synthesize googlePlusBackgroundColorRGB=_googlePlusBackgroundColorRGB;
@property(nonatomic) int mailBackgroundColorRGB; // @synthesize mailBackgroundColorRGB=_mailBackgroundColorRGB;
@property(nonatomic) int twitterBackgroundColorRGB; // @synthesize twitterBackgroundColorRGB=_twitterBackgroundColorRGB;
@property(nonatomic) int facebookBackgroundColorRGB; // @synthesize facebookBackgroundColorRGB=_facebookBackgroundColorRGB;
@property(retain, nonatomic) UIColor *faderColor; // @synthesize faderColor=_faderColor;
@property(nonatomic) double faderAlpha; // @synthesize faderAlpha=_faderAlpha;
@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(nonatomic) int bubbleRadius; // @synthesize bubbleRadius=_bubbleRadius;
@property(nonatomic) int radius; // @synthesize radius=_radius;
@property(retain, nonatomic) NSMutableArray *customButtons; // @synthesize customButtons=_customButtons;
@property(nonatomic) _Bool showWhatsappBubble; // @synthesize showWhatsappBubble=_showWhatsappBubble;
@property(nonatomic) _Bool showFavoriteBubble; // @synthesize showFavoriteBubble=_showFavoriteBubble;
@property(nonatomic) _Bool showInstagramBubble; // @synthesize showInstagramBubble=_showInstagramBubble;
@property(nonatomic) _Bool showRedditBubble; // @synthesize showRedditBubble=_showRedditBubble;
@property(nonatomic) _Bool showVimeoBubble; // @synthesize showVimeoBubble=_showVimeoBubble;
@property(nonatomic) _Bool showYoutubeBubble; // @synthesize showYoutubeBubble=_showYoutubeBubble;
@property(nonatomic) _Bool showPinterestBubble; // @synthesize showPinterestBubble=_showPinterestBubble;
@property(nonatomic) _Bool showLinkedInBubble; // @synthesize showLinkedInBubble=_showLinkedInBubble;
@property(nonatomic) _Bool showVkBubble; // @synthesize showVkBubble=_showVkBubble;
@property(nonatomic) _Bool showTumblrBubble; // @synthesize showTumblrBubble=_showTumblrBubble;
@property(nonatomic) _Bool showGooglePlusBubble; // @synthesize showGooglePlusBubble=_showGooglePlusBubble;
@property(nonatomic) _Bool showMailBubble; // @synthesize showMailBubble=_showMailBubble;
@property(nonatomic) _Bool showTwitterBubble; // @synthesize showTwitterBubble=_showTwitterBubble;
@property(nonatomic) _Bool showFacebookBubble; // @synthesize showFacebookBubble=_showFacebookBubble;
@property(nonatomic) __weak UIView *parentView; // @synthesize parentView;
@property(nonatomic) id <AAShareBubblesDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)imageWithView:(id)arg1;
- (id)colorFromRGB:(int)arg1;
- (void)addCustomButtonWithIcon:(id)arg1 backgroundColor:(id)arg2 andButtonId:(int)arg3;
- (void)createButtonWithIcon:(id)arg1 backgroundColor:(int)arg2 andType:(int)arg3;
- (void)createButtonWithIcon:(id)arg1 backgroundColor:(id)arg2 andButtonId:(int)arg3;
- (void)hideBubbleWithAnimation:(id)arg1;
- (void)showBubbleWithAnimation:(id)arg1;
- (void)shareViewBackgroundTapped:(id)arg1;
- (void)hide;
- (void)show;
- (void)shareButtonTappedWithType:(int)arg1;
- (void)buttonWasTapped:(id)arg1;
- (id)initWithPoint:(struct CGPoint)arg1 radius:(int)arg2 inView:(id)arg3;
- (id)initCenteredInWindowWithRadius:(int)arg1;

@end

