//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ActivityDataModel, ActivityViewModel, NSMutableArray, NSString, UIButton, UITableView, UIView;

@interface ActivityViewController : FDBaseViewController <UITableViewDataSource, UITableViewDelegate>
{
    UIView *_headView;
    UITableView *_tableView;
    UIButton *_addNewBtn;
    struct CGSize _tagSize;
    _Bool _isTop;
    NSString *_activityID;
    NSString *_summary;
    ActivityViewModel *_viewModel;
    ActivityDataModel *_activityDataModel;
    NSMutableArray *_articleList;
}

@property(retain, nonatomic) NSMutableArray *articleList; // @synthesize articleList=_articleList;
@property(retain, nonatomic) ActivityDataModel *activityDataModel; // @synthesize activityDataModel=_activityDataModel;
@property(retain, nonatomic) ActivityViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) _Bool isTop; // @synthesize isTop=_isTop;
@property(retain, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(retain, nonatomic) NSString *activityID; // @synthesize activityID=_activityID;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)footerRereshing;
- (void)headerRereshing;
- (void)setupRefresh;
- (void)fillHeadView;
- (void)bindViewModel;
- (void)addNewAction:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

