//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIImageView, UILabel;

@interface AddressTableViewCell : UITableViewCell
{
    UILabel *_nameLabel;
    UILabel *_addressLabel;
    UILabel *_phoneLabel;
    UIImageView *_defaultIndicator;
    UILabel *_provinceLabel;
    UIButton *_addressTypeLabel;
}

@property(nonatomic) __weak UIButton *addressTypeLabel; // @synthesize addressTypeLabel=_addressTypeLabel;
@property(nonatomic) __weak UILabel *provinceLabel; // @synthesize provinceLabel=_provinceLabel;
@property(nonatomic) __weak UIImageView *defaultIndicator; // @synthesize defaultIndicator=_defaultIndicator;
@property(nonatomic) __weak UILabel *phoneLabel; // @synthesize phoneLabel=_phoneLabel;
@property(nonatomic) __weak UILabel *addressLabel; // @synthesize addressLabel=_addressLabel;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (void)onSetDefaultPress:(id)arg1;
- (void)onEditPress:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

