//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "QBImagePickerControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"
#import "UMSocialUIDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString, QBImagePickerController, StarRatingControl, UIButton, UIImagePickerController, UILabel, UIScrollView, UITextField, UITextView, UIView;

@interface AddTasteReportViewController : FDBaseViewController <UITextViewDelegate, UITextFieldDelegate, UIActionSheetDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, UMSocialUIDelegate, QBImagePickerControllerDelegate>
{
    _Bool _isUploading;
    _Bool _placeHolderShow;
    UIView *_photoView;
    UITextView *_commentTextArea;
    UIScrollView *_commentScrollView;
    UIButton *_addNewPhotoButton;
    UITextField *_reportTitleTextView;
    UITextField *_reporterInfoTextLabel;
    StarRatingControl *_starRatingControl;
    UILabel *_tasteItemListName;
    UIImagePickerController *_imagePickerController;
    QBImagePickerController *_qbImagePickerController;
    UIButton *_submitButton;
    NSMutableDictionary *_productInfo;
    NSMutableArray *_photoPool;
    NSString *_applyID;
    NSString *_productName;
    NSString *_productImage;
    NSString *_productId;
    NSString *_appDescription;
    NSString *_appLink;
    struct CGPoint _contentOffset;
}

@property _Bool placeHolderShow; // @synthesize placeHolderShow=_placeHolderShow;
@property _Bool isUploading; // @synthesize isUploading=_isUploading;
@property(retain, nonatomic) NSString *appLink; // @synthesize appLink=_appLink;
@property(retain, nonatomic) NSString *appDescription; // @synthesize appDescription=_appDescription;
@property(retain, nonatomic) NSString *productId; // @synthesize productId=_productId;
@property(retain, nonatomic) NSString *productImage; // @synthesize productImage=_productImage;
@property(retain, nonatomic) NSString *productName; // @synthesize productName=_productName;
@property(retain, nonatomic) NSString *applyID; // @synthesize applyID=_applyID;
@property(retain, nonatomic) NSMutableArray *photoPool; // @synthesize photoPool=_photoPool;
@property(retain, nonatomic) NSMutableDictionary *productInfo; // @synthesize productInfo=_productInfo;
@property struct CGPoint contentOffset; // @synthesize contentOffset=_contentOffset;
@property(nonatomic) __weak UIButton *submitButton; // @synthesize submitButton=_submitButton;
@property(retain, nonatomic) QBImagePickerController *qbImagePickerController; // @synthesize qbImagePickerController=_qbImagePickerController;
@property(retain, nonatomic) UIImagePickerController *imagePickerController; // @synthesize imagePickerController=_imagePickerController;
@property(retain, nonatomic) UILabel *tasteItemListName; // @synthesize tasteItemListName=_tasteItemListName;
@property(nonatomic) __weak StarRatingControl *starRatingControl; // @synthesize starRatingControl=_starRatingControl;
@property(nonatomic) __weak UITextField *reporterInfoTextLabel; // @synthesize reporterInfoTextLabel=_reporterInfoTextLabel;
@property(nonatomic) __weak UITextField *reportTitleTextView; // @synthesize reportTitleTextView=_reportTitleTextView;
@property(nonatomic) __weak UIButton *addNewPhotoButton; // @synthesize addNewPhotoButton=_addNewPhotoButton;
@property(nonatomic) __weak UIScrollView *commentScrollView; // @synthesize commentScrollView=_commentScrollView;
@property(nonatomic) __weak UITextView *commentTextArea; // @synthesize commentTextArea=_commentTextArea;
@property(nonatomic) __weak UIView *photoView; // @synthesize photoView=_photoView;
- (void).cxx_destruct;
- (void)goBack:(id)arg1;
- (void)shareAppInfo;
- (void)deleteSinglePhoto:(id)arg1;
- (void)deleteAllPhotoFile;
- (id)createPhotoSingleView:(int)arg1 image:(id)arg2;
- (void)onDeletePhoto:(id)arg1;
- (void)adjustAddButtonPosition:(int)arg1;
- (void)reLoadImageView;
- (void)clearImageView;
- (void)saveImage:(id)arg1 withData:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)useImage:(id)arg1;
- (id)highResImageForAsset:(id)arg1;
- (void)imagePickerController:(id)arg1 didSelectAssets:(id)arg2;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)addProductComment;
- (void)onSubmitReport:(id)arg1;
- (void)onAddPhoto:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)backToPrevious;
- (void)afterAddComment;
- (_Bool)checkRequiredField;
- (_Bool)checkCommentLength;
- (_Bool)checkCommentInput;
- (void)fillProductInfo;
- (void)alertErrorMessage:(id)arg1;
- (void)hideKeyBoard;
- (void)onViewPressed:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)showHideBusyIndicator:(_Bool)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)keyboardWillHide;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

