//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "DZNEmptyDataSetDelegate.h"
#import "DZNEmptyDataSetSource.h"
#import "ProductListItemCellDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class FDProductItemListData, NSArray, NSDictionary, NSMutableArray, NSString, UIButton, UILabel, UIScrollView, UISearchBar, UISegmentedControl, UITableView, UIView;

@interface AdvancedSearchViewController : FDBaseViewController <ProductListItemCellDelegate, DZNEmptyDataSetSource, DZNEmptyDataSetDelegate, UISearchBarDelegate, UIScrollViewDelegate, UITableViewDataSource, UITableViewDelegate>
{
    FDProductItemListData *_productListData;
    UIButton *_backButton;
    UISearchBar *_searchBar;
    UISegmentedControl *_segmentedControl;
    UIScrollView *_keywordsScrollView;
    UITableView *_historyKeywordsTableView;
    UIButton *_clearSearchHistoryButton;
    UITableView *_searchResultsTableView;
    UIView *_hotKeywordContainer;
    UIView *_hotKeywordView;
    UIView *_guessContainer;
    UIScrollView *_guessScrollView;
    UILabel *_recommendLabel;
    UITableView *_recommendTableView;
    UIScrollView *_hotSearchScrollview;
    NSArray *_hotSearches;
    NSArray *_recommends;
    NSArray *_guessProducts;
    NSMutableArray *_searchResults;
    NSDictionary *_cartItemToAdd;
}

@property(retain, nonatomic) NSDictionary *cartItemToAdd; // @synthesize cartItemToAdd=_cartItemToAdd;
@property(retain, nonatomic) NSMutableArray *searchResults; // @synthesize searchResults=_searchResults;
@property(retain, nonatomic) NSArray *guessProducts; // @synthesize guessProducts=_guessProducts;
@property(retain, nonatomic) NSArray *recommends; // @synthesize recommends=_recommends;
@property(retain, nonatomic) NSArray *hotSearches; // @synthesize hotSearches=_hotSearches;
@property(nonatomic) __weak UIScrollView *hotSearchScrollview; // @synthesize hotSearchScrollview=_hotSearchScrollview;
@property(nonatomic) __weak UITableView *recommendTableView; // @synthesize recommendTableView=_recommendTableView;
@property(nonatomic) __weak UILabel *recommendLabel; // @synthesize recommendLabel=_recommendLabel;
@property(nonatomic) __weak UIScrollView *guessScrollView; // @synthesize guessScrollView=_guessScrollView;
@property(nonatomic) __weak UIView *guessContainer; // @synthesize guessContainer=_guessContainer;
@property(nonatomic) __weak UIView *hotKeywordView; // @synthesize hotKeywordView=_hotKeywordView;
@property(nonatomic) __weak UIView *hotKeywordContainer; // @synthesize hotKeywordContainer=_hotKeywordContainer;
@property(nonatomic) __weak UITableView *searchResultsTableView; // @synthesize searchResultsTableView=_searchResultsTableView;
@property(nonatomic) __weak UIButton *clearSearchHistoryButton; // @synthesize clearSearchHistoryButton=_clearSearchHistoryButton;
@property(nonatomic) __weak UITableView *historyKeywordsTableView; // @synthesize historyKeywordsTableView=_historyKeywordsTableView;
@property(nonatomic) __weak UIScrollView *keywordsScrollView; // @synthesize keywordsScrollView=_keywordsScrollView;
@property(nonatomic) __weak UISegmentedControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
- (void).cxx_destruct;
- (double)verticalOffsetForEmptyDataSet:(id)arg1;
- (id)descriptionForEmptyDataSet:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (void)onClearSearchHistoryPress:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)onBackPress:(id)arg1;
- (void)hideBackButton:(_Bool)arg1;
- (void)showBackButton:(_Bool)arg1;
- (void)hideResultsView;
- (void)recordSearch:(id)arg1;
- (void)performSearch:(id)arg1 sort:(int)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onAddToCartPress:(id)arg1;
- (void)addProduct2CartCell:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)onBannerPress:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)performCouponAnimation;
- (void)showGuessProducts;
- (void)onKeywordPressed:(id)arg1;
- (void)showRecommendView;
- (void)showHotKeywords;
- (void)setButtonTitle:(id)arg1 button:(id)arg2;
- (void)loadGuessProducts;
- (void)loadHotKeywordsView;
- (void)loadHistoryKeywordsView;
- (_Bool)hasSearchHistory;
- (void)onSegmentedControlSelected:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)onCancelSearch:(id)arg1;
- (void)performCellAnimtion;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

