//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "UIAlertViewDelegate.h"

@class NSString, UILabel;

@interface AppSettingTableViewController : UITableViewController <UIAlertViewDelegate>
{
    NSString *trackViewURL;
    UILabel *_customerServiceNumber;
    UILabel *_versionLabel;
}

@property(nonatomic) __weak UILabel *versionLabel; // @synthesize versionLabel=_versionLabel;
@property(nonatomic) __weak UILabel *customerServiceNumber; // @synthesize customerServiceNumber=_customerServiceNumber;
- (void).cxx_destruct;
- (_Bool)shouldPerformSegueWithIdentifier:(id)arg1 sender:(id)arg2;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertErrorMessage:(id)arg1;
- (void)dialCustomerServiceNo;
- (void)goAppStoreComment;
- (void)onCheckVersion;
- (void)clearImageData;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)tableView:(id)arg1 indentationLevelForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

