//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSArray<Optional>, NSArray<Optional><BaiKeCommentData>, NSString<Optional>;

@interface ArticleDataModel : FDBaseDataModel
{
    _Bool _can_delete;
    NSString<Optional> *_id;
    NSString<Optional> *_ctime;
    NSString<Optional> *_stime;
    NSString<Optional> *_type;
    NSString<Optional> *_title;
    NSString<Optional> *_myDescription;
    NSString<Optional> *_content;
    NSArray<Optional> *_photo;
    NSArray<Optional> *_images_thumbs;
    NSString<Optional> *_uid;
    NSString<Optional> *_username;
    NSString<Optional> *_userrank;
    NSString<Optional> *_userface;
    NSString<Optional> *_topic_id;
    NSString<Optional> *_topic_title;
    NSString<Optional> *_share_url;
    NSString<Optional> *_comment_num;
    NSString<Optional> *_worth_num;
    NSString<Optional> *_is_liked;
    NSArray<Optional><BaiKeCommentData> *_latest_comments;
}

+ (id)keyMapper;
@property(retain, nonatomic) NSArray<Optional><BaiKeCommentData> *latest_comments; // @synthesize latest_comments=_latest_comments;
@property(nonatomic) _Bool can_delete; // @synthesize can_delete=_can_delete;
@property(copy, nonatomic) NSString<Optional> *is_liked; // @synthesize is_liked=_is_liked;
@property(copy, nonatomic) NSString<Optional> *worth_num; // @synthesize worth_num=_worth_num;
@property(copy, nonatomic) NSString<Optional> *comment_num; // @synthesize comment_num=_comment_num;
@property(copy, nonatomic) NSString<Optional> *share_url; // @synthesize share_url=_share_url;
@property(copy, nonatomic) NSString<Optional> *topic_title; // @synthesize topic_title=_topic_title;
@property(copy, nonatomic) NSString<Optional> *topic_id; // @synthesize topic_id=_topic_id;
@property(copy, nonatomic) NSString<Optional> *userface; // @synthesize userface=_userface;
@property(copy, nonatomic) NSString<Optional> *userrank; // @synthesize userrank=_userrank;
@property(copy, nonatomic) NSString<Optional> *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString<Optional> *uid; // @synthesize uid=_uid;
@property(retain, nonatomic) NSArray<Optional> *images_thumbs; // @synthesize images_thumbs=_images_thumbs;
@property(retain, nonatomic) NSArray<Optional> *photo; // @synthesize photo=_photo;
@property(copy, nonatomic) NSString<Optional> *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString<Optional> *myDescription; // @synthesize myDescription=_myDescription;
@property(copy, nonatomic) NSString<Optional> *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString<Optional> *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString<Optional> *stime; // @synthesize stime=_stime;
@property(copy, nonatomic) NSString<Optional> *ctime; // @synthesize ctime=_ctime;
@property(copy, nonatomic) NSString<Optional> *id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

