//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSMutableArray<BaiKeCommentData><Optional>;

@interface BaiKeCommentListDataModel : FDBaseDataModel
{
    NSMutableArray<BaiKeCommentData><Optional> *_baikeCommentList;
}

@property(retain, nonatomic) NSMutableArray<BaiKeCommentData><Optional> *baikeCommentList; // @synthesize baikeCommentList=_baikeCommentList;
- (void).cxx_destruct;

@end

