//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSString<Optional>;

@interface BaiKeSectionDataModel : FDBaseDataModel
{
    NSString<Optional> *_id;
    NSString<Optional> *_name;
    NSString<Optional> *_photo;
    NSString<Optional> *_num;
}

@property(copy, nonatomic) NSString<Optional> *num; // @synthesize num=_num;
@property(copy, nonatomic) NSString<Optional> *photo; // @synthesize photo=_photo;
@property(copy, nonatomic) NSString<Optional> *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString<Optional> *id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

