//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UISearchBarDelegate.h"

@class BaiKeSearchKeyViewModel, NSArray, NSString, UIButton, UICollectionView, UISearchBar;

@interface BaiKeSearchViewController : FDBaseViewController <UICollectionViewDataSource, UICollectionViewDelegate, UISearchBarDelegate>
{
    UISearchBar *_searchBar;
    UIButton *_searchBtn;
    UICollectionView *_collectionView;
    BaiKeSearchKeyViewModel *_viewModel;
    NSArray *_searchKeys;
}

@property(retain, nonatomic) NSArray *searchKeys; // @synthesize searchKeys=_searchKeys;
@property(retain, nonatomic) BaiKeSearchKeyViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (_Bool)checkEmpty;
- (void)searchAction:(id)arg1;
- (void)viewEndEditing:(id)arg1;
- (void)initSearchBarView;
- (void)bindViewModel;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

