//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "SCNavTabBarControllerDelegate.h"

@class NSArray, NSString, SCNavTabBarController, UIColor;

@interface BaiKeListViewController : FDBaseViewController <SCNavTabBarControllerDelegate>
{
    SCNavTabBarController *_navTabBarController;
    UIColor *_windowBackgroundColor;
    NSArray *_baikeSection;
    long long _currentIndex;
}

@property(nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) NSArray *baikeSection; // @synthesize baikeSection=_baikeSection;
- (void).cxx_destruct;
- (void)SCNavTabBarController:(id)arg1 DidScrollAtIndex:(long long)arg2;
- (void)bindViewModel;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

