//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaiKeDetailData, UIImageView, UILabel, UIViewController;

@interface BaiKeRecommendView : UIView
{
    UILabel *_viewHeadLabel;
    UIImageView *_viewImageView;
    UILabel *_viewTitleLabel;
    UILabel *_viewDescriptionLabel;
    UIView *_bottomCuttingLine;
    BaiKeDetailData *_baiKeDetailData;
    UIViewController *_target;
}

@property(retain, nonatomic) UIViewController *target; // @synthesize target=_target;
- (void).cxx_destruct;
- (void)tapAction:(id)arg1;
- (void)displayViewByBaiKeDetailData:(id)arg1 target:(id)arg2;
- (void)initialization;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

