//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewModel.h"

@class BaiKeDetailData, NSArray, NSMutableArray, NSString;

@interface BaiKeSearchResultViewModel : FDBaseViewModel
{
    long long _currentQueryPage;
    NSMutableArray *_tmpCurrentMainList;
    NSString *_keyword;
    _Bool _hasMoreMainList;
    NSArray *_topList;
    NSMutableArray *_mainList;
    BaiKeDetailData *_selectedBaiKeDetailData;
}

@property(retain, nonatomic) BaiKeDetailData *selectedBaiKeDetailData; // @synthesize selectedBaiKeDetailData=_selectedBaiKeDetailData;
@property(nonatomic) _Bool hasMoreMainList; // @synthesize hasMoreMainList=_hasMoreMainList;
@property(copy, nonatomic) NSMutableArray *mainList; // @synthesize mainList=_mainList;
@property(copy, nonatomic) NSArray *topList; // @synthesize topList=_topList;
- (void).cxx_destruct;
- (void)setWorth:(id)arg1;
- (void)queryList:(id)arg1;
- (void)getMoreMainListQuery;
- (void)getMainListQuery:(id)arg1;
- (id)init;

@end

