//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseTableViewCell.h"

#import "M80AttributedLabelDelegate.h"

@class M80AttributedLabel, NSLayoutConstraint, NSString, UIButton, UIImageView, UILabel;

@interface BaiKeCommentCell : FDBaseTableViewCell <M80AttributedLabelDelegate>
{
    struct CGSize _tagSize;
    CDUnknownBlockType _userFaceClickAction;
    UILabel *_commentFloorInfoLabel;
    UIImageView *_userImageView;
    M80AttributedLabel *_userNameM80View;
    M80AttributedLabel *_commentContantM80View;
    UIButton *_userfaceButton;
    NSLayoutConstraint *_commentContantHeightConstraint;
    NSLayoutConstraint *_usernameHeightConstraint;
    NSLayoutConstraint *_userfaceButtonLeadingConstraint;
}

+ (double)heightForShequCellWithData:(id)arg1;
+ (double)heightForCellWithData:(id)arg1;
@property(nonatomic) __weak NSLayoutConstraint *userfaceButtonLeadingConstraint; // @synthesize userfaceButtonLeadingConstraint=_userfaceButtonLeadingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *usernameHeightConstraint; // @synthesize usernameHeightConstraint=_usernameHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *commentContantHeightConstraint; // @synthesize commentContantHeightConstraint=_commentContantHeightConstraint;
@property(nonatomic) __weak UIButton *userfaceButton; // @synthesize userfaceButton=_userfaceButton;
@property(nonatomic) __weak M80AttributedLabel *commentContantM80View; // @synthesize commentContantM80View=_commentContantM80View;
@property(nonatomic) __weak M80AttributedLabel *userNameM80View; // @synthesize userNameM80View=_userNameM80View;
@property(nonatomic) __weak UIImageView *userImageView; // @synthesize userImageView=_userImageView;
@property(nonatomic) __weak UILabel *commentFloorInfoLabel; // @synthesize commentFloorInfoLabel=_commentFloorInfoLabel;
@property(copy, nonatomic) CDUnknownBlockType userFaceClickAction; // @synthesize userFaceClickAction=_userFaceClickAction;
- (void).cxx_destruct;
- (void)m80AttributedLabel:(id)arg1 clickedOnLink:(id)arg2;
- (void)userfaceClickAction:(id)arg1;
- (void)loadShequCommentData:(id)arg1 withTarget:(id)arg2;
- (void)loadBaikeCommentData:(id)arg1 withTarget:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

