//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewModel.h"

@class BaiKeDetailData, NSArray, NSMutableArray;

@interface BaiKeViewModel : FDBaseViewModel
{
    long long _currentQueryPage;
    NSMutableArray *_tmpCurrentMainList;
    _Bool _hasMoreMainList;
    NSArray *_baikeSection;
    NSMutableArray *_topList;
    NSMutableArray *_mainList;
    BaiKeDetailData *_selectedBaiKeDetailData;
}

@property(retain, nonatomic) BaiKeDetailData *selectedBaiKeDetailData; // @synthesize selectedBaiKeDetailData=_selectedBaiKeDetailData;
@property(nonatomic) _Bool hasMoreMainList; // @synthesize hasMoreMainList=_hasMoreMainList;
@property(copy, nonatomic) NSMutableArray *mainList; // @synthesize mainList=_mainList;
@property(copy, nonatomic) NSMutableArray *topList; // @synthesize topList=_topList;
@property(copy, nonatomic) NSArray *baikeSection; // @synthesize baikeSection=_baikeSection;
- (void).cxx_destruct;
- (id)JSONValue:(id)arg1;
- (void)setWorth:(id)arg1;
- (void)getBaikeSectionQuery;
- (void)queryList;
- (void)getMoreMainListQuery;
- (void)getMainListQuery;
- (id)init;

@end

