//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewModel.h"

@class NSArray;

@interface BaiKeSearchKeyViewModel : FDBaseViewModel
{
    NSArray *_searchKeys;
}

@property(copy, nonatomic) NSArray *searchKeys; // @synthesize searchKeys=_searchKeys;
- (void).cxx_destruct;
- (id)JSONValue:(id)arg1;
- (void)getSearchKeysQuery;

@end

