//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseTableViewCell.h"

@class BaiKeDetailData, UIButton;

@interface BaiKeOneKindCell : FDBaseTableViewCell
{
    struct CGSize _tagSize;
    UIButton *_likeCountButton;
    UIButton *_commentCountButton;
    BaiKeDetailData *_baiKeDetailData;
    CDUnknownBlockType _supportAction;
}

+ (double)cellHeightByDataSources:(id)arg1 rowAtIndexPath:(id)arg2;
+ (id)cellForTableView:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType supportAction; // @synthesize supportAction=_supportAction;
- (void).cxx_destruct;
- (void)supportAction:(id)arg1;
- (id)likeCountButton;
- (void)displayCellByDataSources:(id)arg1 rowAtIndexPath:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)dealloc;
- (void)awakeFromNib;

@end

