//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSString<Optional>;

@interface BaiKeDetailData : FDBaseDataModel
{
    NSString<Optional> *_id;
    NSString<Optional> *_title;
    NSString<Optional> *_summary;
    NSString<Optional> *_content;
    NSString<Optional> *_type;
    NSString<Optional> *_photo;
    NSString<Optional> *_images_thumbs;
    NSString<Optional> *_share_url;
    NSString<Optional> *_comment_num;
    NSString<Optional> *_stime;
    NSString<Optional> *_worth_num;
    NSString<Optional> *_collection_num;
    NSString<Optional> *_is_worth;
    NSString<Optional> *_is_collect;
    NSString<Optional> *_ctime;
    NSString<Optional> *_username;
    NSString<Optional> *_userrank;
}

@property(copy, nonatomic) NSString<Optional> *userrank; // @synthesize userrank=_userrank;
@property(copy, nonatomic) NSString<Optional> *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString<Optional> *ctime; // @synthesize ctime=_ctime;
@property(copy, nonatomic) NSString<Optional> *is_collect; // @synthesize is_collect=_is_collect;
@property(copy, nonatomic) NSString<Optional> *is_worth; // @synthesize is_worth=_is_worth;
@property(copy, nonatomic) NSString<Optional> *collection_num; // @synthesize collection_num=_collection_num;
@property(copy, nonatomic) NSString<Optional> *worth_num; // @synthesize worth_num=_worth_num;
@property(copy, nonatomic) NSString<Optional> *stime; // @synthesize stime=_stime;
@property(copy, nonatomic) NSString<Optional> *comment_num; // @synthesize comment_num=_comment_num;
@property(copy, nonatomic) NSString<Optional> *share_url; // @synthesize share_url=_share_url;
@property(copy, nonatomic) NSString<Optional> *images_thumbs; // @synthesize images_thumbs=_images_thumbs;
@property(copy, nonatomic) NSString<Optional> *photo; // @synthesize photo=_photo;
@property(copy, nonatomic) NSString<Optional> *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString<Optional> *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString<Optional> *summary; // @synthesize summary=_summary;
@property(copy, nonatomic) NSString<Optional> *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString<Optional> *id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

