//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSArray<PromoProduct>, NSString;

@interface CartPromotionSolution : FDBaseDataModel
{
    _Bool _url;
    float _outofmoney;
    NSString *_title;
    NSString *_tag;
    NSString *_pmtType;
    NSString *_pmtId;
    NSString *_pmtPrice;
    NSArray<PromoProduct> *_products;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSArray<PromoProduct> *products; // @synthesize products=_products;
@property(nonatomic) float outofmoney; // @synthesize outofmoney=_outofmoney;
@property(retain, nonatomic) NSString *pmtPrice; // @synthesize pmtPrice=_pmtPrice;
@property(retain, nonatomic) NSString *pmtId; // @synthesize pmtId=_pmtId;
@property(retain, nonatomic) NSString *pmtType; // @synthesize pmtType=_pmtType;
@property(nonatomic) _Bool url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

