//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class CartPromotionSolution, NSString;

@interface CartPromotionAlert : FDBaseDataModel
{
    NSString *_pmtType;
    CartPromotionSolution *_solution;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) CartPromotionSolution *solution; // @synthesize solution=_solution;
@property(retain, nonatomic) NSString *pmtType; // @synthesize pmtType=_pmtType;
- (void).cxx_destruct;

@end

