//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "EmptyDataHintViewDelegate.h"
#import "ProductItemCellDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CartObject, ConfirmOrderContainerViewController, EmptyDataHintView, NSLayoutConstraint, NSMutableDictionary, NSString, SloppySwiper, UIBarButtonItem, UILabel, UITableView, UIView;

@interface CartViewController : FDBaseViewController <UITableViewDataSource, UITableViewDelegate, UIAlertViewDelegate, ProductItemCellDelegate, EmptyDataHintViewDelegate>
{
    NSMutableDictionary *fees;
    ConfirmOrderContainerViewController *confirmOrderContainerViewController;
    UIBarButtonItem *_clearButton;
    EmptyDataHintView *_emptyDataHintView;
    UITableView *_cartItemTableView;
    UIView *_cartActionView;
    NSLayoutConstraint *_actionTopSeparatorHeight;
    NSLayoutConstraint *_actionBottom;
    UILabel *_total;
    UILabel *_promotionTotal;
    CartObject *_cartObject;
    SloppySwiper *_swiper;
}

+ (id)sharedInstance;
@property(retain, nonatomic) SloppySwiper *swiper; // @synthesize swiper=_swiper;
@property(retain, nonatomic) CartObject *cartObject; // @synthesize cartObject=_cartObject;
@property(nonatomic) __weak UILabel *promotionTotal; // @synthesize promotionTotal=_promotionTotal;
@property(nonatomic) __weak UILabel *total; // @synthesize total=_total;
@property(nonatomic) __weak NSLayoutConstraint *actionBottom; // @synthesize actionBottom=_actionBottom;
@property(nonatomic) __weak NSLayoutConstraint *actionTopSeparatorHeight; // @synthesize actionTopSeparatorHeight=_actionTopSeparatorHeight;
@property(nonatomic) __weak UIView *cartActionView; // @synthesize cartActionView=_cartActionView;
@property(nonatomic) __weak UITableView *cartItemTableView; // @synthesize cartItemTableView=_cartItemTableView;
@property(retain, nonatomic) EmptyDataHintView *emptyDataHintView; // @synthesize emptyDataHintView=_emptyDataHintView;
@property(retain, nonatomic) UIBarButtonItem *clearButton; // @synthesize clearButton=_clearButton;
- (void).cxx_destruct;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)isSignedIn;
- (id)getItemKey:(id)arg1;
- (id)cartItemsFromLocalItems:(id)arg1;
- (id)composeParameterCartItem:(id)arg1;
- (void)setCartCountBadge:(long long)arg1;
- (void)onCheckOutPress:(id)arg1;
- (void)updateActionView:(_Bool)arg1;
- (void)hideActionViewAnimated:(_Bool)arg1;
- (void)showActionView;
- (void)goShopping;
- (void)didTapActionButton;
- (void)hideEmptyDataHintView;
- (void)showEmptyDataHintView;
- (_Bool)isCartEmpty;
- (void)clearCart;
- (void)onClearCart:(id)arg1;
- (void)removeFromCart:(long long)arg1;
- (void)updateCart:(id)arg1;
- (void)qtyMinus:(id)arg1 toDelete:(_Bool)arg2;
- (void)qtyPlus:(id)arg1;
- (void)hideTableView;
- (void)showTableView;
- (void)loadCart:(_Bool)arg1 success:(CDUnknownBlockType)arg2;
- (void)initialLoadCart;
- (void)resetCart;
- (void)animateOnAdd2CartSuccess:(id)arg1;
- (void)addToCart:(id)arg1 target:(id)arg2 isClearCart:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)getCartCount:(CDUnknownBlockType)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

