//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSString<Optional>;

@interface CategorySubLevelDataModel : FDBaseDataModel
{
    NSString<Optional> *_id;
    NSString<Optional> *_is_hot;
    NSString<Optional> *_class_photo;
    NSString<Optional> *_ename;
    NSString<Optional> *_name;
    NSString<Optional> *_photo;
}

@property(copy, nonatomic) NSString<Optional> *photo; // @synthesize photo=_photo;
@property(copy, nonatomic) NSString<Optional> *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString<Optional> *ename; // @synthesize ename=_ename;
@property(copy, nonatomic) NSString<Optional> *class_photo; // @synthesize class_photo=_class_photo;
@property(copy, nonatomic) NSString<Optional> *is_hot; // @synthesize is_hot=_is_hot;
@property(copy, nonatomic) NSString<Optional> *id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

