//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSArray<Optional><CategoryListDataModel>;

@interface CategoryDataModel : FDBaseDataModel
{
    NSArray<Optional><CategoryListDataModel> *_common;
}

@property(retain, nonatomic) NSArray<Optional><CategoryListDataModel> *common; // @synthesize common=_common;
- (void).cxx_destruct;

@end

