//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UITextFieldDelegate.h"

@class NSString, UITextField, UIView;

@interface ChangePasswordViewController : FDBaseViewController <UITextFieldDelegate>
{
    UIView *_border1;
    UIView *_border2;
    UIView *_border3;
    UIView *_border4;
    UITextField *_oldPasswordInput;
    UITextField *_userNewPasswordInput;
    UITextField *_userNewPasswordConfirm;
}

@property(retain, nonatomic) UITextField *userNewPasswordConfirm; // @synthesize userNewPasswordConfirm=_userNewPasswordConfirm;
@property(retain, nonatomic) UITextField *userNewPasswordInput; // @synthesize userNewPasswordInput=_userNewPasswordInput;
@property(retain, nonatomic) UITextField *oldPasswordInput; // @synthesize oldPasswordInput=_oldPasswordInput;
@property(nonatomic) __weak UIView *border4; // @synthesize border4=_border4;
@property(nonatomic) __weak UIView *border3; // @synthesize border3=_border3;
@property(nonatomic) __weak UIView *border2; // @synthesize border2=_border2;
@property(nonatomic) __weak UIView *border1; // @synthesize border1=_border1;
- (void).cxx_destruct;
- (void)onChangePasswordPressed:(id)arg1;
- (void)changePassword;
- (void)backToPreviousView;
- (_Bool)checkInputRequirement;
- (void)alertErrorMessage:(id)arg1;
- (void)showHideBusyIndicator:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)hideKeyBoard;
- (void)onViewPressed:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

