//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSString<Optional>;

@interface CheckRedIndicatorResultDataModel : FDBaseDataModel
{
    NSString<Optional> *_user_center;
    NSString<Optional> *_guoshi;
}

@property(copy, nonatomic) NSString<Optional> *guoshi; // @synthesize guoshi=_guoshi;
@property(copy, nonatomic) NSString<Optional> *user_center; // @synthesize user_center=_user_center;
- (void).cxx_destruct;

@end

