//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString<Optional>;

@interface ChennelIcons : JSONModel
{
    NSString<Optional> *_fresh_point;
    NSString<Optional> *_mobile_only;
    NSString<Optional> *_flash_sale;
    NSString<Optional> *_shake_gift;
    NSString<Optional> *_top_up;
    NSString<Optional> *_logistic_service;
    NSString<Optional> *_good_code;
    NSString<Optional> *_company_user;
    NSString<Optional> *_free_taste;
}

@property(copy, nonatomic) NSString<Optional> *free_taste; // @synthesize free_taste=_free_taste;
@property(copy, nonatomic) NSString<Optional> *company_user; // @synthesize company_user=_company_user;
@property(copy, nonatomic) NSString<Optional> *good_code; // @synthesize good_code=_good_code;
@property(copy, nonatomic) NSString<Optional> *logistic_service; // @synthesize logistic_service=_logistic_service;
@property(copy, nonatomic) NSString<Optional> *top_up; // @synthesize top_up=_top_up;
@property(copy, nonatomic) NSString<Optional> *shake_gift; // @synthesize shake_gift=_shake_gift;
@property(copy, nonatomic) NSString<Optional> *flash_sale; // @synthesize flash_sale=_flash_sale;
@property(copy, nonatomic) NSString<Optional> *mobile_only; // @synthesize mobile_only=_mobile_only;
@property(copy, nonatomic) NSString<Optional> *fresh_point; // @synthesize fresh_point=_fresh_point;
- (void).cxx_destruct;

@end

