//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSMutableArray, NSString;

@interface CommentContent : FDBaseDataModel
{
    NSString *_order_id;
    NSString *_product_id;
    NSString *_content;
    NSString *_star;
    NSMutableArray *_images;
}

@property(retain, nonatomic) NSMutableArray *images; // @synthesize images=_images;
@property(copy, nonatomic) NSString *star; // @synthesize star=_star;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *product_id; // @synthesize product_id=_product_id;
@property(copy, nonatomic) NSString *order_id; // @synthesize order_id=_order_id;
- (void).cxx_destruct;
- (id)init;

@end

