//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UIAlertViewDelegate.h"
#import "UITextFieldDelegate.h"

@class ConfirmOrderViewController, FDAppDelegate, NSDictionary, NSMutableDictionary, NSString, OrderObject, UIAlertView, UILabel, UITextField, UIView;

@interface ConfirmOrderContainerViewController : FDBaseViewController <UIAlertViewDelegate, UITextFieldDelegate>
{
    _Bool _orderSubmitSucceed;
    _Bool _needAuthCode;
    _Bool _loadOrSubmit;
    UIView *_containerView;
    UIView *_actionView;
    UIView *_actionHeader;
    UILabel *_totalLabel;
    UITextField *_authCodeInput;
    UIAlertView *_blockBusyIndicator;
    ConfirmOrderViewController *_confirmOrderViewController;
    FDAppDelegate *_delegate;
    NSMutableDictionary *_fees;
    OrderObject *_orderObject;
    NSDictionary *_initialOrder;
    NSMutableDictionary *_invoice;
    NSString *_orderName;
    NSString *_deduction;
    NSString *_authConnectId;
    NSString *_authCode;
    id _sender;
    id _repostSender;
}

@property(retain) id repostSender; // @synthesize repostSender=_repostSender;
@property _Bool loadOrSubmit; // @synthesize loadOrSubmit=_loadOrSubmit;
@property(retain) id sender; // @synthesize sender=_sender;
@property(retain, nonatomic) NSString *authCode; // @synthesize authCode=_authCode;
@property(retain, nonatomic) NSString *authConnectId; // @synthesize authConnectId=_authConnectId;
@property _Bool needAuthCode; // @synthesize needAuthCode=_needAuthCode;
@property(retain, nonatomic) NSString *deduction; // @synthesize deduction=_deduction;
@property(retain, nonatomic) NSString *orderName; // @synthesize orderName=_orderName;
@property(nonatomic) _Bool orderSubmitSucceed; // @synthesize orderSubmitSucceed=_orderSubmitSucceed;
@property(retain, nonatomic) NSMutableDictionary *invoice; // @synthesize invoice=_invoice;
@property(retain, nonatomic) NSDictionary *initialOrder; // @synthesize initialOrder=_initialOrder;
@property(retain, nonatomic) OrderObject *orderObject; // @synthesize orderObject=_orderObject;
@property(retain, nonatomic) NSMutableDictionary *fees; // @synthesize fees=_fees;
@property(retain, nonatomic) FDAppDelegate *delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) ConfirmOrderViewController *confirmOrderViewController; // @synthesize confirmOrderViewController=_confirmOrderViewController;
@property(retain, nonatomic) UIAlertView *blockBusyIndicator; // @synthesize blockBusyIndicator=_blockBusyIndicator;
@property(retain, nonatomic) UITextField *authCodeInput; // @synthesize authCodeInput=_authCodeInput;
@property(nonatomic) __weak UILabel *totalLabel; // @synthesize totalLabel=_totalLabel;
@property(nonatomic) __weak UIView *actionHeader; // @synthesize actionHeader=_actionHeader;
@property(nonatomic) __weak UIView *actionView; // @synthesize actionView=_actionView;
@property(nonatomic) __weak UIView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (void)hideBlockBusyIndicator;
- (void)showBlockBusyIndicator;
- (void)alertErrorMessage:(id)arg1;
- (void)backToConfirmOrderContainer:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)goOrderComplete;
- (void)performSubmitOrder;
- (id)createPaymentId:(int)arg1;
- (void)sendMobileTicket:(id)arg1;
- (void)hideKeyBoard;
- (void)onViewPressed:(id)arg1;
- (void)showMobileAuthCodeDialog;
- (void)confirmAuthCodeInput:(id)arg1;
- (void)cancelAuthCode;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)onSubmitOrderPress:(id)arg1;
- (void)onCancelOrder:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)queryDeliveryFee;
- (void)updateOnlinePayable:(int)arg1;
- (void)updatePayable;
- (void)initOrder;
- (void)loadUserInfo;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

