//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, UIImageView, UILabel;

@interface ConfirmOrderSectionHeader : UIView
{
    UILabel *_titleLabel;
    UIImageView *_arrowImageView;
    NSLayoutConstraint *_labelLeftLayoutConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *labelLeftLayoutConstraint; // @synthesize labelLeftLayoutConstraint=_labelLeftLayoutConstraint;
@property(nonatomic) __weak UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;

@end

