//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "UITextFieldDelegate.h"

@class FDAppDelegate, InvoiceTitle, NSDictionary, NSMutableDictionary, NSString, UIButton, UIImageView, UILabel, UISwitch, UITextField, UITextView;

@interface ConfirmOrderViewController : UITableViewController <UITextFieldDelegate, UIGestureRecognizerDelegate>
{
    int maxCreditUsed;
    _Bool recordOrCancel;
    NSString *currentCredit;
    NSString *userCredit;
    NSDictionary *_valueDict;
    _Bool _invoiceNeeded;
    _Bool _invoiceSupported;
    _Bool _ifShowNoteSection;
    _Bool _ifShowGreetingSection;
    int _isEnterprise;
    FDAppDelegate *_delegate;
    UILabel *_contactName;
    UILabel *_contactAddressArea;
    UILabel *_contactAddressRoad;
    UILabel *_contactNo;
    UILabel *_contactEmptyTitleLabel;
    UILabel *_contactEmptyDetailLabel;
    UILabel *_deliveryTimeTitle;
    UILabel *_deliveryTime;
    UILabel *_payOptionTitle;
    UILabel *_payOption;
    UIImageView *_payOptionLogo;
    UILabel *_payWithCredit;
    UILabel *_payWithVoucher;
    UISwitch *_isInvoiceNeeded;
    UILabel *_noInvoiceMessage;
    UILabel *_invoiceTitle;
    UILabel *_invoiceAddress;
    UITextView *_noteTextView;
    UITextView *_cardTextView;
    UILabel *_total4Items;
    UILabel *_deliveryFee;
    UILabel *_creditDeduction;
    UILabel *_voucherTitle;
    UILabel *_voucherDeduction;
    UILabel *_otherDeduction;
    UILabel *_creditUsedTitle;
    UISwitch *_creditUsedSwitch;
    UITextField *_creditUsedInput;
    UILabel *_creditUsedValue;
    UILabel *_creditTotal;
    UIButton *_addressTypeButton;
    NSDictionary *_cart;
    NSDictionary *_fees;
    NSString *_selectedDeliveryOption;
    NSString *_creditUsed;
    NSDictionary *_couponUsed;
    InvoiceTitle *_invoiceTitleObject;
    NSMutableDictionary *_invoiceAddressDictionary;
}

@property(nonatomic) _Bool ifShowGreetingSection; // @synthesize ifShowGreetingSection=_ifShowGreetingSection;
@property(nonatomic) _Bool ifShowNoteSection; // @synthesize ifShowNoteSection=_ifShowNoteSection;
@property(nonatomic) int isEnterprise; // @synthesize isEnterprise=_isEnterprise;
@property _Bool invoiceSupported; // @synthesize invoiceSupported=_invoiceSupported;
@property _Bool invoiceNeeded; // @synthesize invoiceNeeded=_invoiceNeeded;
@property(retain) NSMutableDictionary *invoiceAddressDictionary; // @synthesize invoiceAddressDictionary=_invoiceAddressDictionary;
@property(retain) InvoiceTitle *invoiceTitleObject; // @synthesize invoiceTitleObject=_invoiceTitleObject;
@property(retain) NSDictionary *couponUsed; // @synthesize couponUsed=_couponUsed;
@property(retain) NSString *creditUsed; // @synthesize creditUsed=_creditUsed;
@property(retain) NSString *selectedDeliveryOption; // @synthesize selectedDeliveryOption=_selectedDeliveryOption;
@property(retain) NSDictionary *fees; // @synthesize fees=_fees;
@property(retain) NSDictionary *cart; // @synthesize cart=_cart;
@property(nonatomic) __weak UIButton *addressTypeButton; // @synthesize addressTypeButton=_addressTypeButton;
@property(nonatomic) __weak UILabel *creditTotal; // @synthesize creditTotal=_creditTotal;
@property(nonatomic) __weak UILabel *creditUsedValue; // @synthesize creditUsedValue=_creditUsedValue;
@property(nonatomic) __weak UITextField *creditUsedInput; // @synthesize creditUsedInput=_creditUsedInput;
@property(nonatomic) __weak UISwitch *creditUsedSwitch; // @synthesize creditUsedSwitch=_creditUsedSwitch;
@property(nonatomic) __weak UILabel *creditUsedTitle; // @synthesize creditUsedTitle=_creditUsedTitle;
@property(nonatomic) __weak UILabel *otherDeduction; // @synthesize otherDeduction=_otherDeduction;
@property(nonatomic) __weak UILabel *voucherDeduction; // @synthesize voucherDeduction=_voucherDeduction;
@property(nonatomic) __weak UILabel *voucherTitle; // @synthesize voucherTitle=_voucherTitle;
@property(nonatomic) __weak UILabel *creditDeduction; // @synthesize creditDeduction=_creditDeduction;
@property(nonatomic) __weak UILabel *deliveryFee; // @synthesize deliveryFee=_deliveryFee;
@property(nonatomic) __weak UILabel *total4Items; // @synthesize total4Items=_total4Items;
@property(nonatomic) __weak UITextView *cardTextView; // @synthesize cardTextView=_cardTextView;
@property(nonatomic) __weak UITextView *noteTextView; // @synthesize noteTextView=_noteTextView;
@property(nonatomic) __weak UILabel *invoiceAddress; // @synthesize invoiceAddress=_invoiceAddress;
@property(nonatomic) __weak UILabel *invoiceTitle; // @synthesize invoiceTitle=_invoiceTitle;
@property(nonatomic) __weak UILabel *noInvoiceMessage; // @synthesize noInvoiceMessage=_noInvoiceMessage;
@property(nonatomic) __weak UISwitch *isInvoiceNeeded; // @synthesize isInvoiceNeeded=_isInvoiceNeeded;
@property(nonatomic) __weak UILabel *payWithVoucher; // @synthesize payWithVoucher=_payWithVoucher;
@property(nonatomic) __weak UILabel *payWithCredit; // @synthesize payWithCredit=_payWithCredit;
@property(nonatomic) __weak UIImageView *payOptionLogo; // @synthesize payOptionLogo=_payOptionLogo;
@property(nonatomic) __weak UILabel *payOption; // @synthesize payOption=_payOption;
@property(nonatomic) __weak UILabel *payOptionTitle; // @synthesize payOptionTitle=_payOptionTitle;
@property(nonatomic) __weak UILabel *deliveryTime; // @synthesize deliveryTime=_deliveryTime;
@property(nonatomic) __weak UILabel *deliveryTimeTitle; // @synthesize deliveryTimeTitle=_deliveryTimeTitle;
@property(nonatomic) __weak UILabel *contactEmptyDetailLabel; // @synthesize contactEmptyDetailLabel=_contactEmptyDetailLabel;
@property(nonatomic) __weak UILabel *contactEmptyTitleLabel; // @synthesize contactEmptyTitleLabel=_contactEmptyTitleLabel;
@property(nonatomic) __weak UILabel *contactNo; // @synthesize contactNo=_contactNo;
@property(nonatomic) __weak UILabel *contactAddressRoad; // @synthesize contactAddressRoad=_contactAddressRoad;
@property(nonatomic) __weak UILabel *contactAddressArea; // @synthesize contactAddressArea=_contactAddressArea;
@property(nonatomic) __weak UILabel *contactName; // @synthesize contactName=_contactName;
@property(retain, nonatomic) FDAppDelegate *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateRelatedValue:(id)arg1 adjustCredit:(_Bool)arg2;
- (void)alertErrorMessage:(id)arg1;
- (void)onCreditUsedChange:(id)arg1;
- (void)onCreditSwitchChange:(id)arg1;
- (void)cancelCreditUsed;
- (void)recordCreditUsed:(id)arg1;
- (void)cancelInvoice:(_Bool)arg1;
- (void)recordInvoice:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (_Bool)shouldPerformSegueWithIdentifier:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 indentationLevelForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)onSectionHeaderPressed:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)addRedIndication:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)updateFees:(id)arg1;
- (void)onInvoiceSwitchChanged:(id)arg1;
- (void)refreshInvoiceAddress;
- (void)updateInvoiceAddress:(id)arg1;
- (void)refreshInvoiceTitle;
- (void)updateInvoiceTitle:(id)arg1;
- (void)supportInvoice:(int)arg1 message:(id)arg2;
- (void)needInvoice:(int)arg1;
- (void)updateVoucherUsed:(id)arg1;
- (void)disableCreditUse;
- (void)updateCreditUsed:(int)arg1;
- (void)updateBankDeduction:(id)arg1;
- (void)updatePaymentView;
- (void)updateDeliveryOptionView;
- (void)updateAddressView;
- (void)adjustCellTilePosition;
- (void)onDonePressCard;
- (void)onDonePress;
- (void)onViewTapped:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

