//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, UISwitch, UITextField;

@interface CostCreditCell : UITableViewCell
{
    id <LocationCellDelegate> _delegate;
    UILabel *_titleLabel;
    UILabel *_availableCreditLabel;
    UITextField *_costCreditLabel;
    UISwitch *_creditControlSwitch;
}

@property(nonatomic) __weak UISwitch *creditControlSwitch; // @synthesize creditControlSwitch=_creditControlSwitch;
@property(nonatomic) __weak UITextField *costCreditLabel; // @synthesize costCreditLabel=_costCreditLabel;
@property(nonatomic) __weak UILabel *availableCreditLabel; // @synthesize availableCreditLabel=_availableCreditLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) id <LocationCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)creditControlAction:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

