//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSDate, NSTimer, UIColor, UIImageView, UILabel;

@interface CountDownView : UIView
{
    int _saleStatus;
    CDUnknownBlockType _saleStatusEvent;
    UIColor *_themeColor;
    UIColor *_salesColor;
    NSTimer *_countDownTimer;
    double _countDown;
    NSDate *_startTime;
    NSDate *_overTime;
    UIImageView *_countDownIconImageView;
    UILabel *_countDownTextLabel;
    UILabel *_countDownHourLabel;
    UILabel *_countDownMinuteLabel;
    UILabel *_countDownSecondLabel;
    UILabel *_countDownDayLabel;
    NSArray *_hourBgImageView;
    NSArray *_blankLabel;
}

@property(retain, nonatomic) NSArray *blankLabel; // @synthesize blankLabel=_blankLabel;
@property(retain, nonatomic) NSArray *hourBgImageView; // @synthesize hourBgImageView=_hourBgImageView;
@property(nonatomic) __weak UILabel *countDownDayLabel; // @synthesize countDownDayLabel=_countDownDayLabel;
@property(nonatomic) __weak UILabel *countDownSecondLabel; // @synthesize countDownSecondLabel=_countDownSecondLabel;
@property(nonatomic) __weak UILabel *countDownMinuteLabel; // @synthesize countDownMinuteLabel=_countDownMinuteLabel;
@property(nonatomic) __weak UILabel *countDownHourLabel; // @synthesize countDownHourLabel=_countDownHourLabel;
@property(nonatomic) __weak UILabel *countDownTextLabel; // @synthesize countDownTextLabel=_countDownTextLabel;
@property(nonatomic) __weak UIImageView *countDownIconImageView; // @synthesize countDownIconImageView=_countDownIconImageView;
@property(retain, nonatomic) NSDate *overTime; // @synthesize overTime=_overTime;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
@property(nonatomic) double countDown; // @synthesize countDown=_countDown;
@property(retain, nonatomic) NSTimer *countDownTimer; // @synthesize countDownTimer=_countDownTimer;
@property(retain, nonatomic) UIColor *salesColor; // @synthesize salesColor=_salesColor;
@property(nonatomic) int saleStatus; // @synthesize saleStatus=_saleStatus;
@property(retain, nonatomic) UIColor *themeColor; // @synthesize themeColor=_themeColor;
@property(copy, nonatomic) CDUnknownBlockType saleStatusEvent; // @synthesize saleStatusEvent=_saleStatusEvent;
- (void).cxx_destruct;
- (void)shortThanOneDay:(long long)arg1;
- (void)moreThanOneDay;
- (void)setCountDownLabels:(int)arg1 interval:(double)arg2;
- (void)endFlashSale;
- (void)startFlashSale:(id)arg1;
- (void)startPreFlashSale:(id)arg1;
- (void)onCountDownFired;
- (void)showFlashSaleCountDown:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

