//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CouponData : NSObject
{
    _Bool _card_o2o_only;
    _Bool _is_expired;
    _Bool _can_not_use;
    NSString *_card_product_id;
    NSString *_remarks;
    NSString *_use_range;
    NSString *_to_date;
    NSString *_card_number;
    long long _card_money;
    long long _coupon_list_from_type;
}

@property(nonatomic) long long coupon_list_from_type; // @synthesize coupon_list_from_type=_coupon_list_from_type;
@property(nonatomic) long long card_money; // @synthesize card_money=_card_money;
@property(retain, nonatomic) NSString *card_number; // @synthesize card_number=_card_number;
@property(retain, nonatomic) NSString *to_date; // @synthesize to_date=_to_date;
@property(retain, nonatomic) NSString *use_range; // @synthesize use_range=_use_range;
@property(retain, nonatomic) NSString *remarks; // @synthesize remarks=_remarks;
@property(retain, nonatomic) NSString *card_product_id; // @synthesize card_product_id=_card_product_id;
@property(nonatomic) _Bool can_not_use; // @synthesize can_not_use=_can_not_use;
@property(nonatomic) _Bool is_expired; // @synthesize is_expired=_is_expired;
@property(nonatomic) _Bool card_o2o_only; // @synthesize card_o2o_only=_card_o2o_only;
- (void).cxx_destruct;
- (void)initWithDictionary:(id)arg1;

@end

