//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface CreditHistoryTableViewCell : UITableViewCell
{
    UILabel *_creditChangeValue;
    UILabel *_creditSource;
    UILabel *_creditChangeDate;
    UIImageView *_levelChangeImageView;
}

@property(nonatomic) __weak UIImageView *levelChangeImageView; // @synthesize levelChangeImageView=_levelChangeImageView;
@property(nonatomic) __weak UILabel *creditChangeDate; // @synthesize creditChangeDate=_creditChangeDate;
@property(nonatomic) __weak UILabel *creditSource; // @synthesize creditSource=_creditSource;
@property(nonatomic) __weak UILabel *creditChangeValue; // @synthesize creditChangeValue=_creditChangeValue;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

