//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "DZNEmptyDataSetDelegate.h"
#import "DZNEmptyDataSetSource.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class FDAppDelegate, NSMutableArray, NSString, UILabel, UITableView;

@interface CreditHistoryViewController : FDBaseViewController <DZNEmptyDataSetSource, DZNEmptyDataSetDelegate, UITableViewDataSource, UITableViewDelegate>
{
    int _currentPage;
    NSString *creditTotal;
    UILabel *_totalCreditLabel;
    UITableView *_creditHistoryTableView;
    FDAppDelegate *_delegate;
    NSMutableArray *_items;
}

@property int currentPage; // @synthesize currentPage=_currentPage;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(retain, nonatomic) FDAppDelegate *delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UITableView *creditHistoryTableView; // @synthesize creditHistoryTableView=_creditHistoryTableView;
@property(nonatomic) __weak UILabel *totalCreditLabel; // @synthesize totalCreditLabel=_totalCreditLabel;
@property(retain, nonatomic) NSString *creditTotal; // @synthesize creditTotal;
- (void).cxx_destruct;
- (void)onCheckCreditRule:(id)arg1;
- (void)emptyDataSetDidTapButton:(id)arg1;
- (double)verticalOffsetForEmptyDataSet:(id)arg1;
- (id)buttonTitleForEmptyDataSet:(id)arg1 forState:(unsigned long long)arg2;
- (id)descriptionForEmptyDataSet:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)showHideBusyIndicator:(_Bool)arg1;
- (void)loadCreditHistory:(int)arg1 isRefresh:(_Bool)arg2;
- (void)loadUserInfo;
- (void)performCreditNumber;
- (void)alertErrorMessage:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

