//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString<Optional>;

@interface DataForBanner : JSONModel
{
    NSString<Optional> *_photo;
    NSString<Optional> *_price;
    NSString<Optional> *_title;
    NSString<Optional> *_type;
    NSString<Optional> *_target_id;
    NSString<Optional> *_myDescription;
    NSString<Optional> *_page_url;
    NSString<Optional> *_position;
    NSString<Optional> *_channel;
}

+ (id)keyMapper;
@property(copy, nonatomic) NSString<Optional> *channel; // @synthesize channel=_channel;
@property(copy, nonatomic) NSString<Optional> *position; // @synthesize position=_position;
@property(copy, nonatomic) NSString<Optional> *page_url; // @synthesize page_url=_page_url;
@property(copy, nonatomic) NSString<Optional> *myDescription; // @synthesize myDescription=_myDescription;
@property(copy, nonatomic) NSString<Optional> *target_id; // @synthesize target_id=_target_id;
@property(copy, nonatomic) NSString<Optional> *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString<Optional> *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString<Optional> *price; // @synthesize price=_price;
@property(copy, nonatomic) NSString<Optional> *photo; // @synthesize photo=_photo;
- (void).cxx_destruct;

@end

