//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSDictionary, NSString, UITableView, UIViewController;

@interface DeliveryOptionsViewController : FDBaseViewController <UITableViewDataSource, UITableViewDelegate>
{
    _Bool _selectionSucceed;
    UITableView *_deliveryOptionsTableView;
    NSDictionary *_selectedAddress;
    NSArray *_deliveryOptions;
    NSDictionary *_selectedDeliveryOption;
    UIViewController *_fromViewController;
    id _repostSender;
}

@property(retain) id repostSender; // @synthesize repostSender=_repostSender;
@property(nonatomic) _Bool selectionSucceed; // @synthesize selectionSucceed=_selectionSucceed;
@property(retain, nonatomic) UIViewController *fromViewController; // @synthesize fromViewController=_fromViewController;
@property(retain, nonatomic) NSDictionary *selectedDeliveryOption; // @synthesize selectedDeliveryOption=_selectedDeliveryOption;
@property(retain, nonatomic) NSArray *deliveryOptions; // @synthesize deliveryOptions=_deliveryOptions;
@property(retain, nonatomic) NSDictionary *selectedAddress; // @synthesize selectedAddress=_selectedAddress;
@property(nonatomic) __weak UITableView *deliveryOptionsTableView; // @synthesize deliveryOptionsTableView=_deliveryOptionsTableView;
- (void).cxx_destruct;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)alertErrorMessage:(id)arg1;
- (_Bool)shouldPerformSegueWithIdentifier:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)loadDeliveryOptions;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

