//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EAIntroPage, EAIntroView;

@protocol EAIntroDelegate <NSObject>

@optional
- (void)intro:(EAIntroView *)arg1 pageEndScrolling:(EAIntroPage *)arg2 withIndex:(unsigned long long)arg3;
- (void)intro:(EAIntroView *)arg1 pageStartScrolling:(EAIntroPage *)arg2 withIndex:(unsigned long long)arg3;
- (void)intro:(EAIntroView *)arg1 pageAppeared:(EAIntroPage *)arg2 withIndex:(unsigned long long)arg3;
- (void)introDidFinish:(EAIntroView *)arg1;
@end

