//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSArray, NSDictionary, NSMutableDictionary, NSString, UIButton, UIPickerView, UIScrollView, UISwitch, UITextField, UIView;

@interface EditAddressViewController : FDBaseViewController <UIPickerViewDataSource, UIPickerViewDelegate, UITextFieldDelegate>
{
    NSString *selectedProvince;
    NSString *selectedCity;
    NSString *selectedDistrict;
    NSString *selectedProvinceId;
    NSString *selectedCityId;
    NSString *selectedDistrictId;
    NSString *userProvince;
    NSString *userCity;
    NSString *userDistrict;
    NSString *addressID;
    NSString *_mobileNo;
    _Bool _saveOrDelete;
    NSMutableDictionary *addressData;
    UIPickerView *_addressPicker;
    UIView *_addressSelectedView;
    UIScrollView *_addressUserScrollView;
    UIView *_border1;
    UIView *_border2;
    UIView *_border3;
    UIView *_border4;
    UIView *_border5;
    UIView *_border6;
    UIView *_border7;
    UISwitch *_defaultSwitch;
    UITextField *_userNameInput;
    UITextField *_userStreetInput;
    UITextField *_userAddressTypeInput;
    UITextField *_userMobileInput;
    UIButton *_selectAddressButton;
    NSArray *_addressSource;
    NSDictionary *_selectedProvince;
    NSDictionary *_selectedCity;
    NSArray *_currentProvincePool;
    NSArray *_currentCityPool;
    NSArray *_currentDistrictPool;
}

@property _Bool saveOrDelete; // @synthesize saveOrDelete=_saveOrDelete;
@property(retain, nonatomic) NSArray *currentDistrictPool; // @synthesize currentDistrictPool=_currentDistrictPool;
@property(retain, nonatomic) NSArray *currentCityPool; // @synthesize currentCityPool=_currentCityPool;
@property(retain, nonatomic) NSArray *currentProvincePool; // @synthesize currentProvincePool=_currentProvincePool;
@property(retain, nonatomic) NSDictionary *selectedCity; // @synthesize selectedCity=_selectedCity;
@property(retain, nonatomic) NSDictionary *selectedProvince; // @synthesize selectedProvince=_selectedProvince;
@property(retain, nonatomic) NSArray *addressSource; // @synthesize addressSource=_addressSource;
@property(nonatomic) __weak UIButton *selectAddressButton; // @synthesize selectAddressButton=_selectAddressButton;
@property(nonatomic) __weak UITextField *userMobileInput; // @synthesize userMobileInput=_userMobileInput;
@property(nonatomic) __weak UITextField *userAddressTypeInput; // @synthesize userAddressTypeInput=_userAddressTypeInput;
@property(nonatomic) __weak UITextField *userStreetInput; // @synthesize userStreetInput=_userStreetInput;
@property(nonatomic) __weak UITextField *userNameInput; // @synthesize userNameInput=_userNameInput;
@property(nonatomic) __weak UISwitch *defaultSwitch; // @synthesize defaultSwitch=_defaultSwitch;
@property(nonatomic) __weak UIView *border7; // @synthesize border7=_border7;
@property(nonatomic) __weak UIView *border6; // @synthesize border6=_border6;
@property(nonatomic) __weak UIView *border5; // @synthesize border5=_border5;
@property(nonatomic) __weak UIView *border4; // @synthesize border4=_border4;
@property(nonatomic) __weak UIView *border3; // @synthesize border3=_border3;
@property(nonatomic) __weak UIView *border2; // @synthesize border2=_border2;
@property(nonatomic) __weak UIView *border1; // @synthesize border1=_border1;
@property(nonatomic) __weak UIScrollView *addressUserScrollView; // @synthesize addressUserScrollView=_addressUserScrollView;
@property(nonatomic) __weak UIView *addressSelectedView; // @synthesize addressSelectedView=_addressSelectedView;
@property(nonatomic) __weak UIPickerView *addressPicker; // @synthesize addressPicker=_addressPicker;
@property(retain) NSMutableDictionary *addressData; // @synthesize addressData;
- (void).cxx_destruct;
- (void)showAddressSelector;
- (void)hideAddressSelector;
- (void)deleteAddress;
- (void)saveAddress;
- (void)showHideBusyIndicator:(_Bool)arg1;
- (void)alertErrorMessage:(id)arg1;
- (void)backToPreviousView;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onSaveButtonPressed:(id)arg1;
- (void)onDeleteButtonPressed:(id)arg1;
- (void)onFinishSelectPressed;
- (void)onSelectAddress:(id)arg1;
- (_Bool)checkInputRequirement;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (double)pickerView:(id)arg1 widthForComponent:(long long)arg2;
- (double)pickerView:(id)arg1 rowHeightForComponent:(long long)arg2;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)loadDistrictLevelData:(id)arg1 isInitial:(_Bool)arg2;
- (void)loadCityLevelData:(id)arg1 isInitial:(_Bool)arg2;
- (void)loadProvinceLevelData;
- (void)setDefaultAddressSelected;
- (void)initializePickerView;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)setDistrictPicker:(id)arg1;
- (void)setCityPicker:(id)arg1;
- (void)setProvincePicker:(id)arg1;
- (void)onSaveAction:(id)arg1;
- (void)onCancelAction:(id)arg1;
- (void)keyboardWillHide;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)hideKeyBoard;
- (void)onViewPressed:(id)arg1;
- (void)viewDidLoad;
- (void)fillAddressData:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

