//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface FavouriteProductListData : NSObject
{
    NSMutableArray *_favouriteProductList;
}

@property(retain, nonatomic) NSMutableArray *favouriteProductList; // @synthesize favouriteProductList=_favouriteProductList;
- (void).cxx_destruct;
- (id)addObjectTo:(id)arg1 FromArray:(id)arg2;
- (void)initfavouriteProductListWithArray:(id)arg1;

@end

