//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "NJKScrollFullscreenDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UIWebViewDelegate.h"
#import "UMSocialUIDelegate.h"

@class NJKScrollFullScreen, NSLayoutConstraint, NSString, UIWebView;

@interface FDActivityWebViewController : FDBaseViewController <UIWebViewDelegate, UMSocialUIDelegate, UIScrollViewDelegate, NJKScrollFullscreenDelegate>
{
    NSLayoutConstraint *_topLayoutConstraint;
    NJKScrollFullScreen *_scrollProxy;
    NSString *currentUrl;
    _Bool _isNeedRefresh;
    UIWebView *_activityWebView;
    NSString *_pageUrl;
    NSString *_pageType;
}

@property(nonatomic) _Bool isNeedRefresh; // @synthesize isNeedRefresh=_isNeedRefresh;
@property(retain, nonatomic) NSString *pageType; // @synthesize pageType=_pageType;
@property(retain, nonatomic) NSString *pageUrl; // @synthesize pageUrl=_pageUrl;
@property(nonatomic) __weak UIWebView *activityWebView; // @synthesize activityWebView=_activityWebView;
- (void).cxx_destruct;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)scrollFullScreenScrollViewDidEndDraggingScrollDown:(id)arg1;
- (void)scrollFullScreenScrollViewDidEndDraggingScrollUp:(id)arg1;
- (void)scrollFullScreen:(id)arg1 scrollViewDidScrollDown:(double)arg2;
- (void)scrollFullScreen:(id)arg1 scrollViewDidScrollUp:(double)arg2;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)refreshCurrentUrl;
- (void)loadPageUrl:(id)arg1;
- (id)buildPageUrl:(id)arg1;
- (void)closeSelf;
- (void)gobackAction;
- (void)setNavBackAndCloseButton;
- (void)setNavBackButton;
- (void)setScrollNavBar;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

