//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "BMKGeneralDelegate.h"
#import "UIApplicationDelegate.h"
#import "WXApiDelegate.h"

@class BMKMapManager, FDSplashView, FDTabBar, ItemDetailViewController, NSDictionary, NSMutableDictionary, NSString, NSTimer, SignInViewController, UINavigationController, UITabBarController, UIView, UIWindow;

@interface FDAppDelegate : UIResponder <BMKGeneralDelegate, UIApplicationDelegate, WXApiDelegate>
{
    BMKMapManager *_mapManager;
    _Bool _shouldAlertNewUser;
    _Bool _shareNeedSign;
    _Bool _updateCenter;
    _Bool _alertBountMobile;
    _Bool _isSwitchOn;
    _Bool _hasAdDisplayed;
    UIWindow *_window;
    NSDictionary *_defaultRegion;
    NSDictionary *_userInfo;
    NSMutableDictionary *_localMark;
    NSString *_appSharedType;
    NSString *_appSharedChannel;
    ItemDetailViewController *_productDetailView;
    id _orderPayFromController;
    NSString *_webPageUrl;
    NSString *_balancePayAuthCode;
    NSString *_offlinePayAuthCode;
    SignInViewController *_signInController;
    UITabBarController *_tabBarController;
    FDTabBar *_tabBar;
    UIView *_view1;
    NSDictionary *_orderInProcessing;
    UINavigationController *_homeNavigationController;
    UINavigationController *_userNavigationController;
    FDSplashView *_splashView;
    NSTimer *_timer;
}

@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) FDSplashView *splashView; // @synthesize splashView=_splashView;
@property(nonatomic) _Bool hasAdDisplayed; // @synthesize hasAdDisplayed=_hasAdDisplayed;
@property(nonatomic) _Bool isSwitchOn; // @synthesize isSwitchOn=_isSwitchOn;
@property(retain, nonatomic) UINavigationController *userNavigationController; // @synthesize userNavigationController=_userNavigationController;
@property(retain, nonatomic) UINavigationController *homeNavigationController; // @synthesize homeNavigationController=_homeNavigationController;
@property(nonatomic) _Bool alertBountMobile; // @synthesize alertBountMobile=_alertBountMobile;
@property(nonatomic) _Bool updateCenter; // @synthesize updateCenter=_updateCenter;
@property(retain, nonatomic) NSDictionary *orderInProcessing; // @synthesize orderInProcessing=_orderInProcessing;
@property(retain, nonatomic) UIView *view1; // @synthesize view1=_view1;
@property(retain, nonatomic) FDTabBar *tabBar; // @synthesize tabBar=_tabBar;
@property(retain, nonatomic) UITabBarController *tabBarController; // @synthesize tabBarController=_tabBarController;
@property(retain, nonatomic) SignInViewController *signInController; // @synthesize signInController=_signInController;
@property(nonatomic) _Bool shareNeedSign; // @synthesize shareNeedSign=_shareNeedSign;
@property(nonatomic) _Bool shouldAlertNewUser; // @synthesize shouldAlertNewUser=_shouldAlertNewUser;
@property(retain, nonatomic) NSString *offlinePayAuthCode; // @synthesize offlinePayAuthCode=_offlinePayAuthCode;
@property(retain, nonatomic) NSString *balancePayAuthCode; // @synthesize balancePayAuthCode=_balancePayAuthCode;
@property(retain, nonatomic) NSString *webPageUrl; // @synthesize webPageUrl=_webPageUrl;
@property(retain, nonatomic) id orderPayFromController; // @synthesize orderPayFromController=_orderPayFromController;
@property(retain, nonatomic) ItemDetailViewController *productDetailView; // @synthesize productDetailView=_productDetailView;
@property(retain, nonatomic) NSString *appSharedChannel; // @synthesize appSharedChannel=_appSharedChannel;
@property(retain, nonatomic) NSString *appSharedType; // @synthesize appSharedType=_appSharedType;
@property(retain, nonatomic) NSMutableDictionary *localMark; // @synthesize localMark=_localMark;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) NSDictionary *defaultRegion; // @synthesize defaultRegion=_defaultRegion;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)respondWhenReceiveRemotePush:(id)arg1;
- (void)respondIfReceiveRemotePush:(id)arg1;
- (void)didReceiveRemoteNotificationWhenLaunch:(id)arg1;
- (void)onGetPermissionState:(int)arg1;
- (void)onGetNetworkState:(int)arg1;
- (void)bringInMain;
- (void)removeSplashView;
- (void)resetAppToFirstController;
- (void)onResp:(id)arg1;
- (_Bool)firstLaunchApp:(id)arg1;
- (void)launchBMKMapManager;
- (void)setupJPush:(id)arg1;
- (void)setupJPushUmengTrack;
- (void)initSSKeychain;
- (void)initNavigationBarAndStatusBar;
- (void)initParameters;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

