//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIImageView, UILabel;

@interface FDBaiKeCollectionViewCell : UICollectionViewCell
{
    UIImageView *_cellImageV;
    UILabel *_cellTitleL;
    UILabel *_cellNumL;
}

- (void).cxx_destruct;
- (void)displayCellByDataSources:(id)arg1 rowAtIndexPath:(id)arg2;
- (void)awakeFromNib;

@end

