//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString<Optional>;

@interface FDBaseDataModel : JSONModel
{
    NSString<Optional> *_result;
    NSString<Optional> *_message;
}

@property(copy, nonatomic) NSString<Optional> *message; // @synthesize message=_message;
@property(copy, nonatomic) NSString<Optional> *result; // @synthesize result=_result;
- (void).cxx_destruct;
- (id)initWithString:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

