//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURLSessionDataTask;

@interface FDBaseViewModel : NSObject
{
    NSURLSessionDataTask *_currentDataTask;
    NSString *_failureMessage;
}

@property(copy, nonatomic) NSString *failureMessage; // @synthesize failureMessage=_failureMessage;
@property(retain, nonatomic) NSURLSessionDataTask *currentDataTask; // @synthesize currentDataTask=_currentDataTask;
- (void).cxx_destruct;
- (void)dealloc;
- (void)cancelTheTask;
- (id)init;

@end

