//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKScene.h"

@class CMAccelerometerData, CMMotionManager, NSMutableArray;

@interface FDDisplayScene : SKScene
{
    CMMotionManager *_motionManager;
    float _latestAngle;
    CMAccelerometerData *_previousAcce;
    _Bool _contentCreated;
    NSMutableArray *_fruitNodes;
}

@property _Bool contentCreated; // @synthesize contentCreated=_contentCreated;
@property(retain, nonatomic) NSMutableArray *fruitNodes; // @synthesize fruitNodes=_fruitNodes;
- (void).cxx_destruct;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)selfDelloc;
- (void)initLSBGetDegress;
- (void)addFruitSprite;
- (void)createSceneContents;
- (void)didMoveToView:(id)arg1;
- (id)initWithSize:(struct CGSize)arg1;

@end

