//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseTableViewCell.h"

@class NSArray, NSIndexPath, UIButton, UIView;

@interface FDFourInOneHomeCell : FDBaseTableViewCell
{
    NSArray *_banners;
    NSIndexPath *_indexPath;
    CDUnknownBlockType _clickBannerBlock;
    UIView *_bannerBackgroundView;
    UIButton *_bannerPositionOne;
    UIButton *_bannerPositionTwo;
    UIButton *_bannerPositionThree;
    UIButton *_bannerPositionFour;
}

+ (double)heightForCellInTableView:(id)arg1 rowAtIndexPath:(id)arg2 dataSource:(id)arg3;
+ (id)cellForTableView:(id)arg1;
@property(nonatomic) __weak UIButton *bannerPositionFour; // @synthesize bannerPositionFour=_bannerPositionFour;
@property(nonatomic) __weak UIButton *bannerPositionThree; // @synthesize bannerPositionThree=_bannerPositionThree;
@property(nonatomic) __weak UIButton *bannerPositionTwo; // @synthesize bannerPositionTwo=_bannerPositionTwo;
@property(nonatomic) __weak UIButton *bannerPositionOne; // @synthesize bannerPositionOne=_bannerPositionOne;
@property(nonatomic) __weak UIView *bannerBackgroundView; // @synthesize bannerBackgroundView=_bannerBackgroundView;
@property(copy, nonatomic) CDUnknownBlockType clickBannerBlock; // @synthesize clickBannerBlock=_clickBannerBlock;
- (void).cxx_destruct;
- (void)clickBannerAction:(id)arg1;
- (void)cellForRowsAtIndexPath:(id)arg1 dataSource:(id)arg2 target:(id)arg3;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

