//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "RMPZoomTransitionAnimating.h"
#import "UINavigationControllerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class DBLocationManager, FDHomePageViewModel, FDRotationHomeCell, FDSegmentView, HomePageDataMode, NSMutableArray, NSString, OfflineHomeViewController, SloppySwiper, UIButton, UIScrollView, UISearchBar, UITableView, UIView, YKuImageInLoopScrollView;

@interface FDHomeViewController : FDBaseViewController <UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate, UIScrollViewDelegate, RMPZoomTransitionAnimating, UINavigationControllerDelegate>
{
    FDSegmentView *_segmentView;
    long long _selectedPage;
    UISearchBar *_searchBar;
    DBLocationManager *_locationManager;
    NSMutableArray *_locations;
    FDRotationHomeCell *_rotationHomeCell;
    _Bool _needReloadRotationHomeCell;
    _Bool _isFirstLoadData;
    _Bool _needPushAnimation;
    id <OfflineCategoryDelegate> _delegate;
    UIView *_adView;
    SloppySwiper *_swiper;
    UIButton *_scrollToTopButton;
    UIScrollView *_contentScorllView;
    UITableView *_b2cTableView;
    OfflineHomeViewController *_offlineHomeVC;
    UIButton *_customLocateButton;
    FDHomePageViewModel *_viewModel;
    HomePageDataMode *_homePageDataMode;
    YKuImageInLoopScrollView *_rotationScrollView;
}

@property(retain, nonatomic) YKuImageInLoopScrollView *rotationScrollView; // @synthesize rotationScrollView=_rotationScrollView;
@property(retain, nonatomic) HomePageDataMode *homePageDataMode; // @synthesize homePageDataMode=_homePageDataMode;
@property(retain, nonatomic) FDHomePageViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) UIButton *customLocateButton; // @synthesize customLocateButton=_customLocateButton;
@property(retain, nonatomic) OfflineHomeViewController *offlineHomeVC; // @synthesize offlineHomeVC=_offlineHomeVC;
@property(retain, nonatomic) UITableView *b2cTableView; // @synthesize b2cTableView=_b2cTableView;
@property(nonatomic) __weak UIScrollView *contentScorllView; // @synthesize contentScorllView=_contentScorllView;
@property(nonatomic) __weak UIButton *scrollToTopButton; // @synthesize scrollToTopButton=_scrollToTopButton;
@property(retain, nonatomic) SloppySwiper *swiper; // @synthesize swiper=_swiper;
@property(retain, nonatomic) UIView *adView; // @synthesize adView=_adView;
@property(nonatomic) id <OfflineCategoryDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool needPushAnimation; // @synthesize needPushAnimation=_needPushAnimation;
- (void).cxx_destruct;
- (struct CGRect)transitionDestinationImageViewFrame;
- (id)transitionSourceImageView;
- (void)showAD;
- (void)showNewUserAlert;
- (void)startUpdateLocation;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)onSearchPressed;
- (void)onLocatePress:(id)arg1;
- (void)onQRReadPressed;
- (void)initUserCenterButton;
- (void)initRightQRButtonInSearchBar;
- (void)initQRButtonInSearchBar;
- (void)initSearchBar;
- (void)initSearchIcon;
- (void)initLocationIcon;
- (void)gotoUerCenter;
- (void)scrollToTopNotification;
- (void)updateLocationNotification:(id)arg1;
- (void)performAnimation;
- (void)updateLocation:(id)arg1;
- (void)checkRedIndicator;
- (void)setupRefresh;
- (void)selectPage:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)selectPage:(unsigned long long)arg1;
- (void)selectTitleLabelAtIndex:(unsigned long long)arg1;
- (void)initSegmentView;
- (void)initWithoutTianTianDaoJia;
- (void)initWithTianTianDaoJia;
- (void)addNotificationCenter;
- (void)addB2CTableView;
- (void)configurationContentScorllView;
- (void)addSubViews;
- (void)bindViewModel;
- (void)scrollToTopButtonAction:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

