//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDProductItemData.h"

@class NSString;

@interface FDMyGiftProductData : FDProductItemData
{
    NSString *_active_id;
    NSString *_active_type;
    NSString *_product_price_id;
    NSString *_end_time;
    NSString *_gg_name;
    NSString *_gift_send_id;
    NSString *_gift_source;
    NSString *_qty;
}

@property(retain, nonatomic) NSString *gift_source; // @synthesize gift_source=_gift_source;
@property(retain, nonatomic) NSString *gift_send_id; // @synthesize gift_send_id=_gift_send_id;
@property(retain, nonatomic) NSString *qty; // @synthesize qty=_qty;
@property(retain, nonatomic) NSString *end_time; // @synthesize end_time=_end_time;
@property(retain, nonatomic) NSString *product_price_id; // @synthesize product_price_id=_product_price_id;
@property(retain, nonatomic) NSString *active_type; // @synthesize active_type=_active_type;
@property(retain, nonatomic) NSString *active_id; // @synthesize active_id=_active_id;
@property(retain, nonatomic) NSString *gg_name; // @synthesize gg_name=_gg_name;
- (void).cxx_destruct;
- (void)initWithDictionary:(id)arg1;

@end

