//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseTableViewCell.h"

@class NSLayoutConstraint, UIButton, UIImageView, UILabel, UIView;

@interface FDMyGiftCell : FDBaseTableViewCell
{
    id <GiftCellDelegate> _delegate;
    UILabel *_giftItemName;
    UILabel *_giftItemPrice;
    UIImageView *_giftItemImage;
    UILabel *_giftItemQuantity;
    UIButton *_giftGetButton;
    UILabel *_giftSourceLabel;
    UILabel *_giftEndTime;
    UIView *_cellBackgroundView;
    UILabel *_giftItemSpecLabel;
    NSLayoutConstraint *_giftItemHeightConstraint;
    UIImageView *_zengIconImageView;
}

+ (id)cellForTableView:(id)arg1;
@property(nonatomic) __weak UIImageView *zengIconImageView; // @synthesize zengIconImageView=_zengIconImageView;
@property(nonatomic) __weak NSLayoutConstraint *giftItemHeightConstraint; // @synthesize giftItemHeightConstraint=_giftItemHeightConstraint;
@property(nonatomic) __weak UILabel *giftItemSpecLabel; // @synthesize giftItemSpecLabel=_giftItemSpecLabel;
@property(nonatomic) __weak UIView *cellBackgroundView; // @synthesize cellBackgroundView=_cellBackgroundView;
@property(nonatomic) __weak UILabel *giftEndTime; // @synthesize giftEndTime=_giftEndTime;
@property(nonatomic) __weak UILabel *giftSourceLabel; // @synthesize giftSourceLabel=_giftSourceLabel;
@property(nonatomic) __weak UIButton *giftGetButton; // @synthesize giftGetButton=_giftGetButton;
@property(retain, nonatomic) UILabel *giftItemQuantity; // @synthesize giftItemQuantity=_giftItemQuantity;
@property(retain, nonatomic) UIImageView *giftItemImage; // @synthesize giftItemImage=_giftItemImage;
@property(retain, nonatomic) UILabel *giftItemPrice; // @synthesize giftItemPrice=_giftItemPrice;
@property(retain, nonatomic) UILabel *giftItemName; // @synthesize giftItemName=_giftItemName;
@property(nonatomic) id <GiftCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onGiftGetButtonPressed:(id)arg1;
- (void)displayCellByDataSources:(id)arg1 rowAtIndexPath:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

