//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseTableViewCell.h"

@class FDCurveImageView, UIButton, UILabel, UIView;

@interface FDOrderCommentCell : FDBaseTableViewCell
{
    id <OrderCommentCellDelegate> _delegate;
    UILabel *_orderNoLabel;
    UILabel *_orderNo;
    UILabel *_orderIssueDate;
    FDCurveImageView *_orderProductImage;
    UILabel *_orderPrice;
    UIButton *_commentButton;
    UIView *_cellBackgroundView;
}

+ (id)cellForTableView:(id)arg1;
@property(nonatomic) __weak UIView *cellBackgroundView; // @synthesize cellBackgroundView=_cellBackgroundView;
@property(nonatomic) __weak UIButton *commentButton; // @synthesize commentButton=_commentButton;
@property(nonatomic) __weak UILabel *orderPrice; // @synthesize orderPrice=_orderPrice;
@property(nonatomic) __weak FDCurveImageView *orderProductImage; // @synthesize orderProductImage=_orderProductImage;
@property(nonatomic) __weak UILabel *orderIssueDate; // @synthesize orderIssueDate=_orderIssueDate;
@property(nonatomic) __weak UILabel *orderNo; // @synthesize orderNo=_orderNo;
@property(nonatomic) __weak UILabel *orderNoLabel; // @synthesize orderNoLabel=_orderNoLabel;
@property(nonatomic) id <OrderCommentCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onCommentPressed:(id)arg1;
- (void)displayCellByDataSources:(id)arg1 rowAtIndexPath:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

