//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseTableViewCell.h"

@class UIButton, UIImageView, UILabel;

@interface FDOrderProductCell : FDBaseTableViewCell
{
    id <OrderProductCellDelegate> _delegate;
    UILabel *_orderItemListName;
    UILabel *_orderItemListPackage;
    UILabel *_orderItemListPrice;
    UIImageView *_orderItemListImage;
    UILabel *_orderItemListQuantity;
    UIButton *_reportIssueButton;
    UIButton *_giftIndicator;
}

+ (id)cellForTableView:(id)arg1;
@property(nonatomic) __weak UIButton *giftIndicator; // @synthesize giftIndicator=_giftIndicator;
@property(retain, nonatomic) UIButton *reportIssueButton; // @synthesize reportIssueButton=_reportIssueButton;
@property(retain, nonatomic) UILabel *orderItemListQuantity; // @synthesize orderItemListQuantity=_orderItemListQuantity;
@property(retain, nonatomic) UIImageView *orderItemListImage; // @synthesize orderItemListImage=_orderItemListImage;
@property(retain, nonatomic) UILabel *orderItemListPrice; // @synthesize orderItemListPrice=_orderItemListPrice;
@property(retain, nonatomic) UILabel *orderItemListPackage; // @synthesize orderItemListPackage=_orderItemListPackage;
@property(retain, nonatomic) UILabel *orderItemListName; // @synthesize orderItemListName=_orderItemListName;
@property(nonatomic) id <OrderProductCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onReportIssuePressed:(id)arg1;
- (void)displayCellByDataSources:(id)arg1 rowAtIndexPath:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

