//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FDOrderProductListData, NSString;

@interface FDOrderOverviewData : NSObject
{
    _Bool _can_cancel;
    _Bool _can_check_logistic;
    _Bool _can_comment;
    _Bool _can_confirm_receive;
    _Bool _can_pay;
    _Bool _can_report_issue;
    NSString *_money;
    NSString *_order_name;
    NSString *_order_status;
    NSString *_order_type;
    NSString *_pay_name;
    NSString *_pay_parent_id;
    NSString *_pay_status;
    NSString *_time;
    NSString *_order_id;
    FDOrderProductListData *_productList;
    id <OrderActionDelegate> _delegate;
}

@property(retain, nonatomic) FDOrderProductListData *productList; // @synthesize productList=_productList;
@property(retain, nonatomic) NSString *order_id; // @synthesize order_id=_order_id;
@property(retain, nonatomic) NSString *time; // @synthesize time=_time;
@property(retain, nonatomic) NSString *pay_status; // @synthesize pay_status=_pay_status;
@property(retain, nonatomic) NSString *pay_parent_id; // @synthesize pay_parent_id=_pay_parent_id;
@property(retain, nonatomic) NSString *pay_name; // @synthesize pay_name=_pay_name;
@property(retain, nonatomic) NSString *order_type; // @synthesize order_type=_order_type;
@property(retain, nonatomic) NSString *order_status; // @synthesize order_status=_order_status;
@property(retain, nonatomic) NSString *order_name; // @synthesize order_name=_order_name;
@property(retain, nonatomic) NSString *money; // @synthesize money=_money;
@property(nonatomic) _Bool can_report_issue; // @synthesize can_report_issue=_can_report_issue;
@property(nonatomic) _Bool can_pay; // @synthesize can_pay=_can_pay;
@property(nonatomic) _Bool can_confirm_receive; // @synthesize can_confirm_receive=_can_confirm_receive;
@property(nonatomic) _Bool can_comment; // @synthesize can_comment=_can_comment;
@property(nonatomic) _Bool can_check_logistic; // @synthesize can_check_logistic=_can_check_logistic;
@property(nonatomic) _Bool can_cancel; // @synthesize can_cancel=_can_cancel;
@property(nonatomic) id <OrderActionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)orderConfirm:(id)arg1;
- (void)initWithDictionary:(id)arg1;

@end

