//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDOrderOverviewData.h"

@class NSString;

@interface FDOrderDetailData : FDOrderOverviewData
{
    NSString *_card_money;
    NSString *_fp;
    NSString *_jf_money;
    NSString *_pay_discount_money;
    NSString *_goods_money;
    NSString *_mail_money;
    NSString *_pay_id;
    NSString *_score_desc;
    NSString *_shtime;
    NSString *_store_contact;
    NSString *_survey_url;
    NSString *_mobile;
    NSString *_name;
    NSString *_address;
}

@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(retain, nonatomic) NSString *survey_url; // @synthesize survey_url=_survey_url;
@property(retain, nonatomic) NSString *store_contact; // @synthesize store_contact=_store_contact;
@property(retain, nonatomic) NSString *shtime; // @synthesize shtime=_shtime;
@property(retain, nonatomic) NSString *score_desc; // @synthesize score_desc=_score_desc;
@property(retain, nonatomic) NSString *pay_id; // @synthesize pay_id=_pay_id;
@property(retain, nonatomic) NSString *mail_money; // @synthesize mail_money=_mail_money;
@property(retain, nonatomic) NSString *goods_money; // @synthesize goods_money=_goods_money;
@property(retain, nonatomic) NSString *pay_discount_money; // @synthesize pay_discount_money=_pay_discount_money;
@property(retain, nonatomic) NSString *jf_money; // @synthesize jf_money=_jf_money;
@property(retain, nonatomic) NSString *fp; // @synthesize fp=_fp;
@property(retain, nonatomic) NSString *card_money; // @synthesize card_money=_card_money;
- (void).cxx_destruct;
- (void)initWithDictionary:(id)arg1;

@end

