//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseTableViewCell.h"

@class FDCurveImageView, NSLayoutConstraint, UIButton, UILabel;

@interface FDProductItemCell : FDBaseTableViewCell
{
    id <ProductListItemCellDelegate> _delegate;
    FDCurveImageView *_previewImage;
    UILabel *_itemName;
    NSLayoutConstraint *_itemNameHeight;
    UILabel *_itemSpec;
    UILabel *_itemDesc;
    NSLayoutConstraint *_itemDescHeight;
    UILabel *_itemPriceMark;
    UILabel *_itemPrice;
    UILabel *_itemOldPrice;
    UIButton *_addToCartButton;
    UILabel *_itemSeparator;
}

+ (double)heightForCellInTableView:(id)arg1 rowAtIndexPath:(id)arg2 dataSource:(id)arg3;
+ (id)cellForTableView:(id)arg1;
@property(nonatomic) __weak UILabel *itemSeparator; // @synthesize itemSeparator=_itemSeparator;
@property(nonatomic) __weak UIButton *addToCartButton; // @synthesize addToCartButton=_addToCartButton;
@property(nonatomic) __weak UILabel *itemOldPrice; // @synthesize itemOldPrice=_itemOldPrice;
@property(nonatomic) __weak UILabel *itemPrice; // @synthesize itemPrice=_itemPrice;
@property(nonatomic) __weak UILabel *itemPriceMark; // @synthesize itemPriceMark=_itemPriceMark;
@property(nonatomic) __weak NSLayoutConstraint *itemDescHeight; // @synthesize itemDescHeight=_itemDescHeight;
@property(nonatomic) __weak UILabel *itemDesc; // @synthesize itemDesc=_itemDesc;
@property(nonatomic) __weak UILabel *itemSpec; // @synthesize itemSpec=_itemSpec;
@property(nonatomic) __weak NSLayoutConstraint *itemNameHeight; // @synthesize itemNameHeight=_itemNameHeight;
@property(nonatomic) __weak UILabel *itemName; // @synthesize itemName=_itemName;
@property(nonatomic) __weak FDCurveImageView *previewImage; // @synthesize previewImage=_previewImage;
@property(nonatomic) id <ProductListItemCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onAdd2CartPressed:(id)arg1;
- (void)displayCellByDataSources:(id)arg1 rowAtIndexPath:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

