//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseTableViewCell.h"

#import "YKuImageInLoopScrollViewDelegate.h"

@class NSArray, NSString, YKuImageInLoopScrollView;

@interface FDRotationHomeCell : FDBaseTableViewCell <YKuImageInLoopScrollViewDelegate>
{
    NSArray *_rotationList;
    CDUnknownBlockType _didTapBanner;
    YKuImageInLoopScrollView *_rotationScrollView;
}

+ (double)heightForCellInTableView:(id)arg1 rowAtIndexPath:(id)arg2 dataSource:(id)arg3;
+ (id)cellForTableView:(id)arg1;
@property(nonatomic) __weak YKuImageInLoopScrollView *rotationScrollView; // @synthesize rotationScrollView=_rotationScrollView;
@property(copy, nonatomic) CDUnknownBlockType didTapBanner; // @synthesize didTapBanner=_didTapBanner;
- (void).cxx_destruct;
- (void)scrollView:(id)arg1 didScrollPageIndex:(int)arg2;
- (void)scrollView:(id)arg1 didTapIndex:(int)arg2;
- (id)scrollView:(id)arg1 viewAtPageIndex:(int)arg2;
- (int)widthForScrollView:(id)arg1;
- (int)numOfPageForScrollView:(id)arg1;
- (void)initRotationScrollViewWithTarget:(id)arg1;
- (void)displayCellByDataSources:(id)arg1 rowAtIndexPath:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)dealloc;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

