//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewModel.h"

@class NSArray, NSString;

@interface FDShowOrderViewModel : FDBaseViewModel
{
    NSArray *_allUserCommonOrderList;
    NSString *_commentSuccess;
}

@property(retain, nonatomic) NSString *commentSuccess; // @synthesize commentSuccess=_commentSuccess;
@property(retain, nonatomic) NSArray *allUserCommonOrderList; // @synthesize allUserCommonOrderList=_allUserCommonOrderList;
- (void).cxx_destruct;
- (void)pushComment:(id)arg1;
- (void)requestCommonOrderList:(id)arg1;

@end

