//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UIButton, UIImageView;

@interface FDSplashView : UIControl
{
    UIImageView *_image1;
    UIImageView *_image2;
    UIImageView *_image3;
    UIButton *_skipButton;
    UIImageView *_imageIn35Inch;
    _Bool _showAdImage;
    CDUnknownBlockType _animationCompletionBlock;
}

@property(copy, nonatomic) CDUnknownBlockType animationCompletionBlock; // @synthesize animationCompletionBlock=_animationCompletionBlock;
- (void).cxx_destruct;
- (void)skipAction:(id)arg1;
- (void)performBlock:(CDUnknownBlockType)arg1 afterDelay:(double)arg2;
- (void)setAdImageUrl:(id)arg1;
- (void)removeSelf;
- (void)showAdUrlImage:(_Bool)arg1;
- (void)showIn35InchDisplay:(_Bool)arg1;
- (void)adjustViews;
- (void)removeAnimation;
- (void)addTapAction;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

