//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FDTabBar;

@protocol FDTabBarDelegate <NSObject>
- (void)tabbar:(FDTabBar *)arg1 didSelectItemAtIndex:(long long)arg2;

@optional
- (void)tabbar:(FDTabBar *)arg1 didSelectBeSelectedItemAtIndex:(long long)arg2;
- (_Bool)tabbar:(FDTabBar *)arg1 shouldSelectItem:(long long)arg2;
@end

