//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

@class NSDictionary, UIWebView;

@interface FlashRuleViewController : FDBaseViewController
{
    UIWebView *_ruleWebView;
    NSDictionary *_product;
}

@property(retain, nonatomic) NSDictionary *product; // @synthesize product=_product;
@property(nonatomic) __weak UIWebView *ruleWebView; // @synthesize ruleWebView=_ruleWebView;
- (void).cxx_destruct;
- (void)setRuleViewTitle:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

