//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "ProductListItemCellDelegate.h"

@class FlashSaleListData, NSDictionary, NSLayoutConstraint, NSMutableArray, NSString, UIScrollView, UITableView, YKuImageInLoopScrollView;

@interface FlashSaleActivityViewController : FDBaseViewController <ProductListItemCellDelegate>
{
    UITableView *_mTableView;
    UIScrollView *_mContainerScrollView;
    NSLayoutConstraint *_mContainerWidthConstraint;
    NSLayoutConstraint *_mContainerHeightConstraint;
    YKuImageInLoopScrollView *_mScrollView;
    FlashSaleListData *_flashSaleList;
    FlashSaleListData *_flashKillList;
    FlashSaleListData *_futrueFreshList;
    NSMutableArray *_rotationList;
    NSDictionary *_flashSaleDict;
    NSDictionary *_cartItemToAdd;
    NSDictionary *_selectedFlashSale;
}

@property(retain, nonatomic) NSDictionary *selectedFlashSale; // @synthesize selectedFlashSale=_selectedFlashSale;
@property(retain, nonatomic) NSDictionary *cartItemToAdd; // @synthesize cartItemToAdd=_cartItemToAdd;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)addProduct2CartCell:(id)arg1;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)freshSaleTimeOverAction;
- (void)enterFlashSaleDetailWithData:(id)arg1;
- (void)addToCartFromItem:(id)arg1;
- (void)getHeightForView;
- (void)requestGetFlashSaleList;
- (void)dealloc;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

