//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "YKuImageInLoopScrollViewDelegate.h"

@class NSMutableArray, NSString, UIImageView, YKuImageInLoopScrollView;

@interface FlashSaleListCell : UITableViewCell <YKuImageInLoopScrollViewDelegate>
{
    CDUnknownBlockType _scrollviewDidTapIndex;
    YKuImageInLoopScrollView *_imageInLoopView;
    UIImageView *_defaultImageView;
    NSMutableArray *_rotationList;
    double _scrollViewWidth;
}

@property(nonatomic) double scrollViewWidth; // @synthesize scrollViewWidth=_scrollViewWidth;
@property(retain, nonatomic) NSMutableArray *rotationList; // @synthesize rotationList=_rotationList;
@property(nonatomic) __weak UIImageView *defaultImageView; // @synthesize defaultImageView=_defaultImageView;
@property(nonatomic) __weak YKuImageInLoopScrollView *imageInLoopView; // @synthesize imageInLoopView=_imageInLoopView;
@property(copy, nonatomic) CDUnknownBlockType scrollviewDidTapIndex; // @synthesize scrollviewDidTapIndex=_scrollviewDidTapIndex;
- (void).cxx_destruct;
- (void)scrollView:(id)arg1 didTapIndex:(int)arg2;
- (id)scrollView:(id)arg1 viewAtPageIndex:(int)arg2;
- (int)widthForScrollView:(id)arg1;
- (int)numOfPageForScrollView:(id)arg1;
- (void)reloadLoopScrollViewWithRotationList:(id)arg1;
- (void)cellForRowsAtIndexPath:(id)arg1 SourceData:(id)arg2 Target:(id)arg3;
- (void)initLoopScrollViewWithTarget:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

