//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSDate, NSDictionary, NSMutableDictionary, NSString, NSTimer, UIButton, UIImageView, UILabel, UIScrollView, UITableView, UITableViewCell, UITextField, UIView;

@interface FlashSaleViewController : FDBaseViewController <UIAlertViewDelegate, UITableViewDataSource, UITableViewDelegate>
{
    int _saleStatus;
    int _flashType;
    int _sort;
    UIScrollView *_flashSaleScrollView;
    UIImageView *_photoImageView;
    UILabel *_priceLabel;
    UILabel *_volumeLabel;
    UILabel *_oldPriceLabel;
    UIView *_descView;
    UILabel *_nameLabel;
    UIView *_descFooterSeparator;
    UITableView *_flashRuleTableView;
    UITableViewCell *_commentCell;
    UITextField *_briefQuantityTextField;
    UIButton *_minusButton;
    UIButton *_plusButton;
    UIView *_actionView;
    UIView *_actionSeparator;
    UIButton *_purchaseButton;
    UIView *_countDownView;
    UILabel *_stockLeftLabel;
    UIButton *_stockLeftAmount;
    UILabel *_countDownTimeLabel;
    UIButton *_countDownHour;
    UIButton *_countDownMinute;
    UIButton *_countDownSecond;
    UILabel *_countDownSeparator1;
    UILabel *_countDownSeparator2;
    UIButton *_countDownGEOneDay;
    NSTimer *_countDownTimer;
    double _countDown;
    NSDate *_startTime;
    NSDate *_overTime;
    NSMutableDictionary *_product;
    NSDictionary *_itemDesc;
    NSString *_pageType;
    NSString *_targetId;
    NSString *_productId;
    NSDictionary *_cartItemToAdd;
    NSDictionary *_itemCommentRate;
}

@property(retain, nonatomic) NSDictionary *itemCommentRate; // @synthesize itemCommentRate=_itemCommentRate;
@property(retain, nonatomic) NSDictionary *cartItemToAdd; // @synthesize cartItemToAdd=_cartItemToAdd;
@property(nonatomic) int sort; // @synthesize sort=_sort;
@property(retain, nonatomic) NSString *productId; // @synthesize productId=_productId;
@property(retain, nonatomic) NSString *targetId; // @synthesize targetId=_targetId;
@property(retain, nonatomic) NSString *pageType; // @synthesize pageType=_pageType;
@property(nonatomic) int flashType; // @synthesize flashType=_flashType;
@property(retain, nonatomic) NSDictionary *itemDesc; // @synthesize itemDesc=_itemDesc;
@property(retain, nonatomic) NSMutableDictionary *product; // @synthesize product=_product;
@property(nonatomic) int saleStatus; // @synthesize saleStatus=_saleStatus;
@property(retain, nonatomic) NSDate *overTime; // @synthesize overTime=_overTime;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
@property(nonatomic) double countDown; // @synthesize countDown=_countDown;
@property(retain, nonatomic) NSTimer *countDownTimer; // @synthesize countDownTimer=_countDownTimer;
@property(nonatomic) __weak UIButton *countDownGEOneDay; // @synthesize countDownGEOneDay=_countDownGEOneDay;
@property(nonatomic) __weak UILabel *countDownSeparator2; // @synthesize countDownSeparator2=_countDownSeparator2;
@property(nonatomic) __weak UILabel *countDownSeparator1; // @synthesize countDownSeparator1=_countDownSeparator1;
@property(nonatomic) __weak UIButton *countDownSecond; // @synthesize countDownSecond=_countDownSecond;
@property(nonatomic) __weak UIButton *countDownMinute; // @synthesize countDownMinute=_countDownMinute;
@property(nonatomic) __weak UIButton *countDownHour; // @synthesize countDownHour=_countDownHour;
@property(nonatomic) __weak UILabel *countDownTimeLabel; // @synthesize countDownTimeLabel=_countDownTimeLabel;
@property(nonatomic) __weak UIButton *stockLeftAmount; // @synthesize stockLeftAmount=_stockLeftAmount;
@property(nonatomic) __weak UILabel *stockLeftLabel; // @synthesize stockLeftLabel=_stockLeftLabel;
@property(nonatomic) __weak UIView *countDownView; // @synthesize countDownView=_countDownView;
@property(nonatomic) __weak UIButton *purchaseButton; // @synthesize purchaseButton=_purchaseButton;
@property(nonatomic) __weak UIView *actionSeparator; // @synthesize actionSeparator=_actionSeparator;
@property(nonatomic) __weak UIView *actionView; // @synthesize actionView=_actionView;
@property(nonatomic) __weak UIButton *plusButton; // @synthesize plusButton=_plusButton;
@property(nonatomic) __weak UIButton *minusButton; // @synthesize minusButton=_minusButton;
@property(nonatomic) __weak UITextField *briefQuantityTextField; // @synthesize briefQuantityTextField=_briefQuantityTextField;
@property(nonatomic) __weak UITableViewCell *commentCell; // @synthesize commentCell=_commentCell;
@property(nonatomic) __weak UITableView *flashRuleTableView; // @synthesize flashRuleTableView=_flashRuleTableView;
@property(nonatomic) __weak UIView *descFooterSeparator; // @synthesize descFooterSeparator=_descFooterSeparator;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UIView *descView; // @synthesize descView=_descView;
@property(nonatomic) __weak UILabel *oldPriceLabel; // @synthesize oldPriceLabel=_oldPriceLabel;
@property(nonatomic) __weak UILabel *volumeLabel; // @synthesize volumeLabel=_volumeLabel;
@property(nonatomic) __weak UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(nonatomic) __weak UIImageView *photoImageView; // @synthesize photoImageView=_photoImageView;
@property(nonatomic) __weak UIScrollView *flashSaleScrollView; // @synthesize flashSaleScrollView=_flashSaleScrollView;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)showCommentRate:(id)arg1;
- (void)showNoCommentLabel;
- (void)loadCommentRate;
- (void)onPurchasePress:(id)arg1;
- (void)onSpecViewPress;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)setCountDownLabels:(int)arg1 interval:(double)arg2;
- (void)endFlashSale;
- (void)startFlashSale:(id)arg1;
- (void)startPreFlashSale:(id)arg1;
- (void)onCountDownFired;
- (void)onLoadFlashSaleSuccess;
- (void)loadItemDesc;
- (void)loadFlashSale;
- (void)onPlusPress:(id)arg1;
- (void)onMinusPress:(id)arg1;
- (void)hideView;
- (void)showView;
- (void)hideActionView;
- (void)showActionView:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) UIImageView *loadingImageView;
@property(readonly) Class superclass;

@end

