//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UIScrollViewDelegate.h"
#import "UMSocialUIDelegate.h"

@class NSDictionary, NSMutableArray, NSString, UIButton, UILabel, UIPageControl, UIScrollView, UIView;

@interface ForetasteDetailViewController : FDBaseViewController <UIScrollViewDelegate, UMSocialUIDelegate>
{
    UIButton *_shareButton;
    UIView *_applyView;
    UIView *_applyViewHeader;
    UILabel *_applicantCountLabel;
    UILabel *_applicantCount;
    UILabel *_countDownLabel;
    UILabel *_countDown;
    UIButton *_applyButton;
    UIView *_submitApplyView;
    UIView *_submitApplyHeader;
    UIView *_selectAddressView;
    UILabel *_contactName;
    UILabel *_contactAddressArea;
    UILabel *_contactAddressRoad;
    UILabel *_contactNo;
    UIButton *_addressTypeButton;
    UIButton *_defaultAddrTag;
    UIButton *_submitApplyButton;
    UIScrollView *_scrollView;
    UIScrollView *_photoScrollView;
    UIPageControl *_photoPageControl;
    UIView *_briefInfoView;
    UIView *_briefInfoHeader;
    UILabel *_briefItemName;
    UILabel *_briefItemPrice;
    UILabel *_briefItemOldPrice;
    UILabel *_briefItemVolume;
    UIView *_specView;
    UIView *_specHeader;
    UIView *_ruleView;
    UIView *_ruleInfoHeader;
    UIView *_reportView;
    UIView *_reportHeader;
    NSDictionary *_foretasteItem;
    NSDictionary *_foretasteItemDetail;
    NSDictionary *_address;
    NSMutableArray *_briefImagesCache;
    NSMutableArray *_photoImageViewArray;
    NSString *_weiboText;
}

@property(retain, nonatomic) NSString *weiboText; // @synthesize weiboText=_weiboText;
@property(retain, nonatomic) NSMutableArray *photoImageViewArray; // @synthesize photoImageViewArray=_photoImageViewArray;
@property(retain, nonatomic) NSMutableArray *briefImagesCache; // @synthesize briefImagesCache=_briefImagesCache;
@property(retain, nonatomic) NSDictionary *address; // @synthesize address=_address;
@property(retain, nonatomic) NSDictionary *foretasteItemDetail; // @synthesize foretasteItemDetail=_foretasteItemDetail;
@property(retain, nonatomic) NSDictionary *foretasteItem; // @synthesize foretasteItem=_foretasteItem;
@property(nonatomic) __weak UIView *reportHeader; // @synthesize reportHeader=_reportHeader;
@property(nonatomic) __weak UIView *reportView; // @synthesize reportView=_reportView;
@property(nonatomic) __weak UIView *ruleInfoHeader; // @synthesize ruleInfoHeader=_ruleInfoHeader;
@property(nonatomic) __weak UIView *ruleView; // @synthesize ruleView=_ruleView;
@property(nonatomic) __weak UIView *specHeader; // @synthesize specHeader=_specHeader;
@property(nonatomic) __weak UIView *specView; // @synthesize specView=_specView;
@property(nonatomic) __weak UILabel *briefItemVolume; // @synthesize briefItemVolume=_briefItemVolume;
@property(nonatomic) __weak UILabel *briefItemOldPrice; // @synthesize briefItemOldPrice=_briefItemOldPrice;
@property(nonatomic) __weak UILabel *briefItemPrice; // @synthesize briefItemPrice=_briefItemPrice;
@property(nonatomic) __weak UILabel *briefItemName; // @synthesize briefItemName=_briefItemName;
@property(nonatomic) __weak UIView *briefInfoHeader; // @synthesize briefInfoHeader=_briefInfoHeader;
@property(nonatomic) __weak UIView *briefInfoView; // @synthesize briefInfoView=_briefInfoView;
@property(nonatomic) __weak UIPageControl *photoPageControl; // @synthesize photoPageControl=_photoPageControl;
@property(nonatomic) __weak UIScrollView *photoScrollView; // @synthesize photoScrollView=_photoScrollView;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak UIButton *submitApplyButton; // @synthesize submitApplyButton=_submitApplyButton;
@property(nonatomic) __weak UIButton *defaultAddrTag; // @synthesize defaultAddrTag=_defaultAddrTag;
@property(nonatomic) __weak UIButton *addressTypeButton; // @synthesize addressTypeButton=_addressTypeButton;
@property(nonatomic) __weak UILabel *contactNo; // @synthesize contactNo=_contactNo;
@property(nonatomic) __weak UILabel *contactAddressRoad; // @synthesize contactAddressRoad=_contactAddressRoad;
@property(nonatomic) __weak UILabel *contactAddressArea; // @synthesize contactAddressArea=_contactAddressArea;
@property(nonatomic) __weak UILabel *contactName; // @synthesize contactName=_contactName;
@property(nonatomic) __weak UIView *selectAddressView; // @synthesize selectAddressView=_selectAddressView;
@property(nonatomic) __weak UIView *submitApplyHeader; // @synthesize submitApplyHeader=_submitApplyHeader;
@property(nonatomic) __weak UIView *submitApplyView; // @synthesize submitApplyView=_submitApplyView;
@property(nonatomic) __weak UIButton *applyButton; // @synthesize applyButton=_applyButton;
@property(nonatomic) __weak UILabel *countDown; // @synthesize countDown=_countDown;
@property(nonatomic) __weak UILabel *countDownLabel; // @synthesize countDownLabel=_countDownLabel;
@property(nonatomic) __weak UILabel *applicantCount; // @synthesize applicantCount=_applicantCount;
@property(nonatomic) __weak UILabel *applicantCountLabel; // @synthesize applicantCountLabel=_applicantCountLabel;
@property(nonatomic) __weak UIView *applyViewHeader; // @synthesize applyViewHeader=_applyViewHeader;
@property(nonatomic) __weak UIView *applyView; // @synthesize applyView=_applyView;
@property(nonatomic) __weak UIButton *shareButton; // @synthesize shareButton=_shareButton;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)dismissOnSuccess;
- (void)onSubmitApplyPress:(id)arg1;
- (void)onCancelSubmitApply:(id)arg1;
- (void)onApplyPress:(id)arg1;
- (void)updateAddress:(id)arg1;
- (void)onSelectAddressViewPress:(id)arg1;
- (void)verifyApplicationStatus;
- (void)onReportViewPress:(id)arg1;
- (void)onRuleViewPress:(id)arg1;
- (void)onSpecViewPress:(id)arg1;
- (void)loadDetail;
- (void)hideView;
- (void)showView;
- (void)shareProductInfo;
- (void)onSharePress:(id)arg1;
- (void)onBackPress:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)fitPositions;
- (double)getDeltaY;
- (void)initView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

