//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UIActivityIndicatorView, UITableView, UIView;

@interface ForetasteListViewController : FDBaseViewController <UITableViewDataSource, UITableViewDelegate>
{
    _Bool _hasMoreItems;
    _Bool _isLoadingMoreItems;
    int _segmentIndex;
    int _currentOngoingForetastePage;
    int _number;
    UITableView *_foretasteTableView;
    UIView *_emptyHintView;
    UIActivityIndicatorView *_loadMoreIndicator;
    NSMutableArray *_foretasteList;
}

@property int number; // @synthesize number=_number;
@property(nonatomic) int currentOngoingForetastePage; // @synthesize currentOngoingForetastePage=_currentOngoingForetastePage;
@property(nonatomic) int segmentIndex; // @synthesize segmentIndex=_segmentIndex;
@property(retain, nonatomic) NSMutableArray *foretasteList; // @synthesize foretasteList=_foretasteList;
@property(retain, nonatomic) UIActivityIndicatorView *loadMoreIndicator; // @synthesize loadMoreIndicator=_loadMoreIndicator;
@property _Bool isLoadingMoreItems; // @synthesize isLoadingMoreItems=_isLoadingMoreItems;
@property _Bool hasMoreItems; // @synthesize hasMoreItems=_hasMoreItems;
@property(nonatomic) __weak UIView *emptyHintView; // @synthesize emptyHintView=_emptyHintView;
@property(nonatomic) __weak UITableView *foretasteTableView; // @synthesize foretasteTableView=_foretasteTableView;
- (void).cxx_destruct;
- (void)onCheckReportPressed:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)loadForetasteList;
- (void)onForetasteSegmentSelected:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

