//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIImageView, UILabel;

@interface ForetasteCell : UITableViewCell
{
    UILabel *_itemNameLabel;
    UILabel *_itemVolumeLabel;
    UILabel *_itemOldPriceLabel;
    UILabel *_itemCurrentPriceLabel;
    UILabel *_countDownLabel;
    UILabel *_applicantCountLabel;
    UIImageView *_thumbnailImageView;
    UIButton *_amountButton;
    UIButton *_checkReportButton;
    UIButton *_purchaseButton;
    UIButton *_termButton;
}

@property(nonatomic) __weak UIButton *termButton; // @synthesize termButton=_termButton;
@property(nonatomic) __weak UIButton *purchaseButton; // @synthesize purchaseButton=_purchaseButton;
@property(nonatomic) __weak UIButton *checkReportButton; // @synthesize checkReportButton=_checkReportButton;
@property(nonatomic) __weak UIButton *amountButton; // @synthesize amountButton=_amountButton;
@property(nonatomic) __weak UIImageView *thumbnailImageView; // @synthesize thumbnailImageView=_thumbnailImageView;
@property(nonatomic) __weak UILabel *applicantCountLabel; // @synthesize applicantCountLabel=_applicantCountLabel;
@property(nonatomic) __weak UILabel *countDownLabel; // @synthesize countDownLabel=_countDownLabel;
@property(nonatomic) __weak UILabel *itemCurrentPriceLabel; // @synthesize itemCurrentPriceLabel=_itemCurrentPriceLabel;
@property(nonatomic) __weak UILabel *itemOldPriceLabel; // @synthesize itemOldPriceLabel=_itemOldPriceLabel;
@property(nonatomic) __weak UILabel *itemVolumeLabel; // @synthesize itemVolumeLabel=_itemVolumeLabel;
@property(nonatomic) __weak UILabel *itemNameLabel; // @synthesize itemNameLabel=_itemNameLabel;
- (void).cxx_destruct;
- (void)onViewReportPress:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

