//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "DZNEmptyDataSetDelegate.h"
#import "DZNEmptyDataSetSource.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UITableView;

@interface FreeTasteListViewController : FDBaseViewController <DZNEmptyDataSetSource, DZNEmptyDataSetDelegate, UITableViewDelegate, UITableViewDataSource>
{
    int _selectedNumber;
    UITableView *_freeTasteTableView;
    NSMutableArray *_myTastes;
}

@property(nonatomic) int selectedNumber; // @synthesize selectedNumber=_selectedNumber;
@property(retain, nonatomic) NSMutableArray *myTastes; // @synthesize myTastes=_myTastes;
@property(nonatomic) __weak UITableView *freeTasteTableView; // @synthesize freeTasteTableView=_freeTasteTableView;
- (void).cxx_destruct;
- (void)emptyDataSetDidTapButton:(id)arg1;
- (double)verticalOffsetForEmptyDataSet:(id)arg1;
- (id)buttonTitleForEmptyDataSet:(id)arg1 forState:(unsigned long long)arg2;
- (id)descriptionForEmptyDataSet:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (void)onAddReportPressed:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)loadMyTastes;
- (void)alertErrorMessage:(id)arg1;
- (void)showHideBusyIndicator:(_Bool)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

