//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIScrollView;

@interface FutureFreshSaleCell : UITableViewCell
{
    UIScrollView *_futureFreshSaleScrollView;
}

@property(nonatomic) __weak UIScrollView *futureFreshSaleScrollView; // @synthesize futureFreshSaleScrollView=_futureFreshSaleScrollView;
- (void).cxx_destruct;
- (void)loadFutureFreshSaleData:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)initialScrollViewWithData:(id)arg1;
- (void)awakeFromNib;

@end

