//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer, UIViewController, UIWindow;

@interface GoogleWearAlertObjc : NSObject
{
    _Bool _alertActive;
    UIWindow *_bgWindow;
    UIViewController *_defaultViewController;
    NSTimer *_timer;
}

+ (void)showAlertMessage:(id)arg1 andImage:(id)arg2 andWithType:(int)arg3 andWithDuration:(double)arg4 inViewController:(id)arg5 atPostion:(int)arg6 canBeDismissedByUser:(_Bool)arg7;
+ (void)showAlertMessage:(id)arg1 andImage:(id)arg2 andWithType:(int)arg3 andWithDuration:(double)arg4 inViewController:(id)arg5;
+ (void)showAlert:(id)arg1 andWithType:(int)arg2;
+ (id)getInstance;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) _Bool alertActive; // @synthesize alertActive=_alertActive;
@property(retain, nonatomic) UIViewController *defaultViewController; // @synthesize defaultViewController=_defaultViewController;
@property(retain, nonatomic) UIWindow *bgWindow; // @synthesize bgWindow=_bgWindow;
- (void).cxx_destruct;
- (id)useDefaultController;
- (void)removeCurrentAlert:(id)arg1;
- (void)removeAlert;
- (void)presentAlert;
- (void)prepareNotificationToBeShown:(id)arg1;

@end

