//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "DZNEmptyDataSetDelegate.h"
#import "DZNEmptyDataSetSource.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class GSMessageCenterViewModel, NSLayoutConstraint, NSMutableArray, NSString, UIBarButtonItem, UITableView, UIView;

@interface GSMessageCenterViewController : FDBaseViewController <DZNEmptyDataSetSource, DZNEmptyDataSetDelegate, UITableViewDataSource, UITableViewDelegate>
{
    _Bool _isEditing;
    UIView *_emptyView;
    UIBarButtonItem *_editButton;
    UITableView *_tableView;
    UIView *_maskView;
    UIView *_actionView;
    NSLayoutConstraint *_actionBottom;
    NSLayoutConstraint *_actionSeparatorHeight;
    GSMessageCenterViewModel *_viewModel;
    NSMutableArray *_messageList;
}

@property(retain, nonatomic) NSMutableArray *messageList; // @synthesize messageList=_messageList;
@property(retain, nonatomic) GSMessageCenterViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak NSLayoutConstraint *actionSeparatorHeight; // @synthesize actionSeparatorHeight=_actionSeparatorHeight;
@property(nonatomic) __weak NSLayoutConstraint *actionBottom; // @synthesize actionBottom=_actionBottom;
@property(nonatomic) __weak UIView *actionView; // @synthesize actionView=_actionView;
@property(nonatomic) __weak UIView *maskView; // @synthesize maskView=_maskView;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool isEditing; // @synthesize isEditing=_isEditing;
@property(nonatomic) __weak UIBarButtonItem *editButton; // @synthesize editButton=_editButton;
@property(nonatomic) __weak UIView *emptyView; // @synthesize emptyView=_emptyView;
- (void).cxx_destruct;
- (double)verticalOffsetForEmptyDataSet:(id)arg1;
- (id)descriptionForEmptyDataSet:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onReadAllPressed:(id)arg1;
- (void)hideActionView;
- (void)showActionView;
- (void)onEditPressed:(id)arg1;
- (void)bindViewModel;
- (void)footerRereshing;
- (void)headerRereshing;
- (void)setupRefresh;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

