//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, UIButton, UILabel;

@interface GSMeSectionHeader : UIView
{
    UIButton *_myPostButton;
    UIButton *_myMarkButton;
    UIButton *_myCommentButton;
    NSLayoutConstraint *_myPostViewLeading;
    UILabel *_usernameLabel;
}

@property(nonatomic) __weak UILabel *usernameLabel; // @synthesize usernameLabel=_usernameLabel;
@property(nonatomic) __weak NSLayoutConstraint *myPostViewLeading; // @synthesize myPostViewLeading=_myPostViewLeading;
@property(nonatomic) __weak UIButton *myCommentButton; // @synthesize myCommentButton=_myCommentButton;
@property(nonatomic) __weak UIButton *myMarkButton; // @synthesize myMarkButton=_myMarkButton;
@property(nonatomic) __weak UIButton *myPostButton; // @synthesize myPostButton=_myPostButton;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

