//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface HorizontalBanner : UIView
{
    id <HorizontalBannerDelegate> _delegate;
    NSArray *_items;
}

@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(retain, nonatomic) id <HorizontalBannerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onItemPressed:(id)arg1;
- (void)setupLayout;
- (id)initWithFrame:(struct CGRect)arg1 dataSource:(id)arg2 delegate:(id)arg3;

@end

