//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView;

@interface ImageSelectView : UIView
{
    UIButton *_removeBtn;
    UIImageView *_imageView;
    CDUnknownBlockType _addImageAction;
    CDUnknownBlockType _removeImageAction;
}

@property(copy, nonatomic) CDUnknownBlockType removeImageAction; // @synthesize removeImageAction=_removeImageAction;
@property(copy, nonatomic) CDUnknownBlockType addImageAction; // @synthesize addImageAction=_addImageAction;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)removeBtnAction;
- (void)setImage:(id)arg1;
- (void)configView;
- (void)setFrame:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

