//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface ImagesView : UIView
{
    NSArray *_imageUrls;
    NSArray *_images;
    double _mIVImageGapWidth;
    double _mIVImageWidth;
    double _mIVImageHeight;
    CDUnknownBlockType _tapImageView;
}

+ (double)viewHeightByImages:(id)arg1 imageHeight:(double)arg2 justShowOneLine:(_Bool)arg3;
+ (double)viewHeightByImages:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType tapImageView; // @synthesize tapImageView=_tapImageView;
@property(nonatomic) double mIVImageHeight; // @synthesize mIVImageHeight=_mIVImageHeight;
@property(nonatomic) double mIVImageWidth; // @synthesize mIVImageWidth=_mIVImageWidth;
@property(nonatomic) double mIVImageGapWidth; // @synthesize mIVImageGapWidth=_mIVImageGapWidth;
@property(retain, nonatomic) NSArray *images; // @synthesize images=_images;
@property(retain, nonatomic) NSArray *imageUrls; // @synthesize imageUrls=_imageUrls;
- (void).cxx_destruct;
- (void)tapImageView:(id)arg1;
- (void)setImageUrls:(id)arg1 placeholderImage:(id)arg2 justShowOneLine:(_Bool)arg3;
- (void)setImageUrls:(id)arg1 placeholderImage:(id)arg2;
- (void)setImages:(id)arg1 justShowOneLine:(_Bool)arg2;
- (void)configView;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

@end

