//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class InvoiceTitle, NSLayoutConstraint, NSMutableArray<InvoiceTitle>, NSString, UIButton, UITableView, UITextField;

@interface InvoiceTitleViewController : FDBaseViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate>
{
    UIButton *_checkboxPersonal;
    UIButton *_checkboxCompany;
    UITextField *_companyTitle;
    InvoiceTitle *_invoiceTitle;
    NSLayoutConstraint *_separator1Height;
    NSLayoutConstraint *_separator2Height;
    NSLayoutConstraint *_separator3Height;
    UITableView *_tableView;
    NSMutableArray<InvoiceTitle> *_companyInvoiceTitleList;
    InvoiceTitle *_updatedInvoiceTitle;
}

@property(retain, nonatomic) InvoiceTitle *updatedInvoiceTitle; // @synthesize updatedInvoiceTitle=_updatedInvoiceTitle;
@property(retain, nonatomic) NSMutableArray<InvoiceTitle> *companyInvoiceTitleList; // @synthesize companyInvoiceTitleList=_companyInvoiceTitleList;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak NSLayoutConstraint *separator3Height; // @synthesize separator3Height=_separator3Height;
@property(nonatomic) __weak NSLayoutConstraint *separator2Height; // @synthesize separator2Height=_separator2Height;
@property(nonatomic) __weak NSLayoutConstraint *separator1Height; // @synthesize separator1Height=_separator1Height;
@property(retain, nonatomic) InvoiceTitle *invoiceTitle; // @synthesize invoiceTitle=_invoiceTitle;
@property(nonatomic) __weak UITextField *companyTitle; // @synthesize companyTitle=_companyTitle;
@property(nonatomic) __weak UIButton *checkboxCompany; // @synthesize checkboxCompany=_checkboxCompany;
@property(nonatomic) __weak UIButton *checkboxPersonal; // @synthesize checkboxPersonal=_checkboxPersonal;
- (void).cxx_destruct;
- (void)didChooseInvoiceTitle;
- (void)updateInvoiceTitleView;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidChange:(id)arg1;
- (void)onViewPressed:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)loadCompanyInvoiceTitleList;
- (void)hideCompanyInvoiceTitleList;
- (void)showCompanyInvoiceTitleList;
- (void)onCompanyChecked:(id)arg1;
- (void)onPersonalChecked:(id)arg1;
- (void)onSavePressed:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

