//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSArray, NSDictionary, NSMutableDictionary, NSString, UIButton, UIPickerView, UIScrollView, UITextField, UIView;

@interface InvoiceAddressViewController : FDBaseViewController <UIPickerViewDataSource, UIPickerViewDelegate, UITextFieldDelegate>
{
    NSString *selectedProvince;
    NSString *selectedCity;
    NSString *selectedDistrict;
    NSString *selectedProvinceId;
    NSString *selectedCityId;
    NSString *selectedDistrictId;
    NSString *userProvince;
    NSString *userCity;
    NSString *userDistrict;
    _Bool _isDefault;
    UIView *_headerSeparator;
    UIView *_defaultFooter;
    UIView *_otherFooter;
    UIView *_border1;
    UIView *_border2;
    UIView *_border3;
    UIView *_border4;
    UIButton *_checkboxDefault;
    UITextField *_userNameInput;
    UITextField *_userStreetInput;
    UITextField *_userMobileInput;
    UIPickerView *_addressPicker;
    UIView *_addressSelectedView;
    UIScrollView *_invoiceScrollView;
    UIView *_otherAddrView;
    UIButton *_selectAddressButton;
    UIButton *_checkboxOther;
    UITextField *_otherAddressTextField;
    NSMutableDictionary *_invoiceAddress;
    NSMutableDictionary *_addressData;
    NSArray *_addressSource;
    NSDictionary *_selectedProvince;
    NSDictionary *_selectedCity;
    NSArray *_currentProvincePool;
    NSArray *_currentCityPool;
    NSArray *_currentDistrictPool;
}

@property _Bool isDefault; // @synthesize isDefault=_isDefault;
@property(retain, nonatomic) NSArray *currentDistrictPool; // @synthesize currentDistrictPool=_currentDistrictPool;
@property(retain, nonatomic) NSArray *currentCityPool; // @synthesize currentCityPool=_currentCityPool;
@property(retain, nonatomic) NSArray *currentProvincePool; // @synthesize currentProvincePool=_currentProvincePool;
@property(retain, nonatomic) NSDictionary *selectedCity; // @synthesize selectedCity=_selectedCity;
@property(retain, nonatomic) NSDictionary *selectedProvince; // @synthesize selectedProvince=_selectedProvince;
@property(retain, nonatomic) NSArray *addressSource; // @synthesize addressSource=_addressSource;
@property(retain) NSMutableDictionary *addressData; // @synthesize addressData=_addressData;
@property(retain, nonatomic) NSMutableDictionary *invoiceAddress; // @synthesize invoiceAddress=_invoiceAddress;
@property(nonatomic) __weak UITextField *otherAddressTextField; // @synthesize otherAddressTextField=_otherAddressTextField;
@property(nonatomic) __weak UIButton *checkboxOther; // @synthesize checkboxOther=_checkboxOther;
@property(nonatomic) __weak UIButton *selectAddressButton; // @synthesize selectAddressButton=_selectAddressButton;
@property(nonatomic) __weak UIView *otherAddrView; // @synthesize otherAddrView=_otherAddrView;
@property(nonatomic) __weak UIScrollView *invoiceScrollView; // @synthesize invoiceScrollView=_invoiceScrollView;
@property(nonatomic) __weak UIView *addressSelectedView; // @synthesize addressSelectedView=_addressSelectedView;
@property(nonatomic) __weak UIPickerView *addressPicker; // @synthesize addressPicker=_addressPicker;
@property(nonatomic) __weak UITextField *userMobileInput; // @synthesize userMobileInput=_userMobileInput;
@property(nonatomic) __weak UITextField *userStreetInput; // @synthesize userStreetInput=_userStreetInput;
@property(nonatomic) __weak UITextField *userNameInput; // @synthesize userNameInput=_userNameInput;
@property(nonatomic) __weak UIButton *checkboxDefault; // @synthesize checkboxDefault=_checkboxDefault;
@property(nonatomic) __weak UIView *border4; // @synthesize border4=_border4;
@property(nonatomic) __weak UIView *border3; // @synthesize border3=_border3;
@property(nonatomic) __weak UIView *border2; // @synthesize border2=_border2;
@property(nonatomic) __weak UIView *border1; // @synthesize border1=_border1;
@property(nonatomic) __weak UIView *otherFooter; // @synthesize otherFooter=_otherFooter;
@property(nonatomic) __weak UIView *defaultFooter; // @synthesize defaultFooter=_defaultFooter;
@property(nonatomic) __weak UIView *headerSeparator; // @synthesize headerSeparator=_headerSeparator;
- (void).cxx_destruct;
- (void)alertErrorMessage:(id)arg1;
- (void)recordInvoice:(id)arg1 destination:(id)arg2;
- (void)onSavePressed:(id)arg1;
- (void)hideAddressSelector;
- (void)onFinishSelectPressed;
- (void)backToPreviousView;
- (void)onSelectAddress:(id)arg1;
- (_Bool)checkInputRequirement;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (double)pickerView:(id)arg1 widthForComponent:(long long)arg2;
- (double)pickerView:(id)arg1 rowHeightForComponent:(long long)arg2;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)loadDistrictLevelData:(id)arg1;
- (void)loadCityLevelData:(id)arg1;
- (void)loadProvinceLevelData;
- (void)setDefaultAddressSelected;
- (void)initializePickerView;
- (void)textFieldDidChange:(id)arg1;
- (void)onViewPressed:(id)arg1;
- (void)updateInvoiceAddressView;
- (void)onBackButtonPressed;
- (void)onOtherChecked:(id)arg1;
- (void)onDefaultChecked:(id)arg1;
- (void)fillAddressData:(id)arg1;
- (void)changeAddressViewHeight:(_Bool)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)keyboardWillHide;
- (void)showHideBusyIndicator:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

