//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UIWebViewDelegate.h"

@class NSDictionary, NSString, UIImageView, UIWebView;

@interface ItemSpecViewController : FDBaseViewController <UIWebViewDelegate>
{
    UIWebView *_specWebView;
    UIImageView *_specLoadingImageView;
    NSDictionary *_itemDesc;
}

@property(retain, nonatomic) NSDictionary *itemDesc; // @synthesize itemDesc=_itemDesc;
@property(retain, nonatomic) UIImageView *specLoadingImageView; // @synthesize specLoadingImageView=_specLoadingImageView;
@property(nonatomic) __weak UIWebView *specWebView; // @synthesize specWebView=_specWebView;
- (void).cxx_destruct;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)loadSpecView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)onBackPress:(id)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

