//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "AAShareBubblesDelegate.h"
#import "RMPZoomTransitionAnimating.h"
#import "RMPZoomTransitionDelegate.h"
#import "SpecSelectionViewDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UMSocialUIDelegate.h"

@class BaiKeRecommendView, JSBadgeView, NSDictionary, NSMutableArray, NSString, UIButton, UILabel, UIPageControl, UIScrollView, UITextField, UIView, UIWebView;

@interface ItemDetailViewController : FDBaseViewController <RMPZoomTransitionAnimating, RMPZoomTransitionDelegate, UIScrollViewDelegate, UMSocialUIDelegate, AAShareBubblesDelegate, SpecSelectionViewDelegate>
{
    NSMutableArray *briefImagesCache;
    struct CGRect _photoPageControlRect;
    struct CGRect _photoScrollViewRect;
    _Bool _markedFlag;
    _Bool _isOfflineProduct;
    _Bool _hasRecommendedItems;
    _Bool _isNaviToCommentView;
    int _itemId;
    UIScrollView *_scrollView;
    UIView *_actionView;
    UIView *_actionHeader;
    UIButton *_viewCartButton;
    JSBadgeView *_cartBadge;
    UIButton *_add2CartButton;
    UIButton *_backButton;
    UIButton *_shareButton;
    UIButton *_addFavouriteButton;
    UIScrollView *_photoScrollView;
    UIPageControl *_photoPageControl;
    UIView *_briefInfoView;
    UIView *_briefInfoHeader;
    UILabel *_briefItemName;
    UILabel *_briefItemPrice;
    UILabel *_briefItemOldPrice;
    UITextField *_briefQuantityTextField;
    UIButton *_minusButton;
    UIButton *_plusButton;
    UIView *_volumeHeader;
    UIView *_volumeSelectedView;
    UIView *_commentHeader;
    UIView *_commentFooter;
    UILabel *_noCommentLabel;
    UILabel *_commentLabel;
    UIView *_commentSeparator;
    UIView *_commentView;
    UIView *_shareOrderView;
    UIView *_commentRateView;
    BaiKeRecommendView *_baiKeView;
    UIView *_recommendContainerView;
    UIScrollView *_recommendScrollView;
    UIButton *_recommendBannerButton;
    NSDictionary *_item;
    NSDictionary *_itemDesc;
    NSDictionary *_selectedVolume;
    NSMutableArray *_photoImageViewArray;
    NSString *_favOrCartOrShare;
    NSString *_weiboText;
    NSDictionary *_cartItemToAdd;
    Class _sourceViewControllerClass;
    id <ItemListDelegate> _itemListDelegate;
    NSDictionary *_itemCommentRate;
    UIWebView *_specWebView;
}

@property(retain, nonatomic) UIWebView *specWebView; // @synthesize specWebView=_specWebView;
@property _Bool isNaviToCommentView; // @synthesize isNaviToCommentView=_isNaviToCommentView;
@property(retain, nonatomic) NSDictionary *itemCommentRate; // @synthesize itemCommentRate=_itemCommentRate;
@property(nonatomic) _Bool hasRecommendedItems; // @synthesize hasRecommendedItems=_hasRecommendedItems;
@property(nonatomic) __weak id <ItemListDelegate> itemListDelegate; // @synthesize itemListDelegate=_itemListDelegate;
@property(retain, nonatomic) Class sourceViewControllerClass; // @synthesize sourceViewControllerClass=_sourceViewControllerClass;
@property(retain, nonatomic) NSDictionary *cartItemToAdd; // @synthesize cartItemToAdd=_cartItemToAdd;
@property(retain, nonatomic) NSString *weiboText; // @synthesize weiboText=_weiboText;
@property(nonatomic) _Bool isOfflineProduct; // @synthesize isOfflineProduct=_isOfflineProduct;
@property(nonatomic) _Bool markedFlag; // @synthesize markedFlag=_markedFlag;
@property(retain, nonatomic) NSString *favOrCartOrShare; // @synthesize favOrCartOrShare=_favOrCartOrShare;
@property(retain, nonatomic) NSMutableArray *photoImageViewArray; // @synthesize photoImageViewArray=_photoImageViewArray;
@property(retain, nonatomic) NSDictionary *selectedVolume; // @synthesize selectedVolume=_selectedVolume;
@property(retain, nonatomic) NSDictionary *itemDesc; // @synthesize itemDesc=_itemDesc;
@property(retain, nonatomic) NSDictionary *item; // @synthesize item=_item;
@property(nonatomic) int itemId; // @synthesize itemId=_itemId;
@property(nonatomic) __weak UIButton *recommendBannerButton; // @synthesize recommendBannerButton=_recommendBannerButton;
@property(nonatomic) __weak UIScrollView *recommendScrollView; // @synthesize recommendScrollView=_recommendScrollView;
@property(nonatomic) __weak UIView *recommendContainerView; // @synthesize recommendContainerView=_recommendContainerView;
@property(retain, nonatomic) BaiKeRecommendView *baiKeView; // @synthesize baiKeView=_baiKeView;
@property(nonatomic) __weak UIView *commentRateView; // @synthesize commentRateView=_commentRateView;
@property(nonatomic) __weak UIView *shareOrderView; // @synthesize shareOrderView=_shareOrderView;
@property(nonatomic) __weak UIView *commentView; // @synthesize commentView=_commentView;
@property(nonatomic) __weak UIView *commentSeparator; // @synthesize commentSeparator=_commentSeparator;
@property(nonatomic) __weak UILabel *commentLabel; // @synthesize commentLabel=_commentLabel;
@property(nonatomic) __weak UILabel *noCommentLabel; // @synthesize noCommentLabel=_noCommentLabel;
@property(nonatomic) __weak UIView *commentFooter; // @synthesize commentFooter=_commentFooter;
@property(nonatomic) __weak UIView *commentHeader; // @synthesize commentHeader=_commentHeader;
@property(nonatomic) __weak UIView *volumeSelectedView; // @synthesize volumeSelectedView=_volumeSelectedView;
@property(nonatomic) __weak UIView *volumeHeader; // @synthesize volumeHeader=_volumeHeader;
@property(nonatomic) __weak UIButton *plusButton; // @synthesize plusButton=_plusButton;
@property(nonatomic) __weak UIButton *minusButton; // @synthesize minusButton=_minusButton;
@property(nonatomic) __weak UITextField *briefQuantityTextField; // @synthesize briefQuantityTextField=_briefQuantityTextField;
@property(nonatomic) __weak UILabel *briefItemOldPrice; // @synthesize briefItemOldPrice=_briefItemOldPrice;
@property(nonatomic) __weak UILabel *briefItemPrice; // @synthesize briefItemPrice=_briefItemPrice;
@property(nonatomic) __weak UILabel *briefItemName; // @synthesize briefItemName=_briefItemName;
@property(nonatomic) __weak UIView *briefInfoHeader; // @synthesize briefInfoHeader=_briefInfoHeader;
@property(nonatomic) __weak UIView *briefInfoView; // @synthesize briefInfoView=_briefInfoView;
@property(nonatomic) __weak UIPageControl *photoPageControl; // @synthesize photoPageControl=_photoPageControl;
@property(nonatomic) __weak UIScrollView *photoScrollView; // @synthesize photoScrollView=_photoScrollView;
@property(nonatomic) __weak UIButton *addFavouriteButton; // @synthesize addFavouriteButton=_addFavouriteButton;
@property(nonatomic) __weak UIButton *shareButton; // @synthesize shareButton=_shareButton;
@property(nonatomic) __weak UIButton *backButton; // @synthesize backButton=_backButton;
@property(nonatomic) __weak UIButton *add2CartButton; // @synthesize add2CartButton=_add2CartButton;
@property(retain, nonatomic) JSBadgeView *cartBadge; // @synthesize cartBadge=_cartBadge;
@property(nonatomic) __weak UIButton *viewCartButton; // @synthesize viewCartButton=_viewCartButton;
@property(nonatomic) __weak UIView *actionHeader; // @synthesize actionHeader=_actionHeader;
@property(nonatomic) __weak UIView *actionView; // @synthesize actionView=_actionView;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)zoomTransitionAnimator:(id)arg1 didCompleteTransition:(_Bool)arg2 animatingSourceImageView:(id)arg3;
- (struct CGRect)transitionDestinationImageViewFrame;
- (id)transitionSourceImageView;
- (void)tapBannerAction:(id)arg1;
- (void)goToBoundMobile;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)isSignedIn;
- (id)composeParameterItems:(id)arg1 quantity:(long long)arg2;
- (void)onPurchasePress:(id)arg1;
- (void)onPlusPress:(id)arg1;
- (void)onMinusPress:(id)arg1;
- (void)setCartCountBadge:(long long)arg1;
- (void)onViewCartPress:(id)arg1;
- (void)hideActionView;
- (void)showActionView:(_Bool)arg1;
- (void)shareProductInfo;
- (void)onSharePress:(id)arg1;
- (void)onMarkPress:(id)arg1;
- (void)changeMarkImage;
- (void)didStopAnimating;
- (void)markAnimation:(_Bool)arg1;
- (void)cancelProductFavourite;
- (void)markProductForFavourite;
- (void)checkUserFavourite;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)loadSpecView;
- (void)setupRefresh;
- (void)onSpecViewPress:(id)arg1;
- (void)showRecommendProducts:(id)arg1;
- (void)loadRecommendItems;
- (void)showBaiKeView:(id)arg1;
- (void)getBaikeData:(id)arg1;
- (void)showCommentRate:(id)arg1;
- (void)loadCommentRate;
- (void)onShareOrderViewPress:(id)arg1;
- (void)onCommentViewPress:(id)arg1;
- (void)didSelectSpec:(id)arg1;
- (void)initSKUSelectionView;
- (void)showSKUInfo;
- (void)showProductInfo;
- (void)loadItemDetail;
- (int)getOfflineGap;
- (void)hideControlWhenOfflineEntrance;
- (_Bool)isOfflineEntrance;
- (void)fitPositions;
- (double)getDeltaY;
- (void)hideView;
- (void)showView;
- (void)showHideBusyIndicator:(_Bool)arg1;
- (void)onBackPress:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

