//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSString;

@interface ItemPhoto : FDBaseDataModel
{
    NSString *_huge;
    NSString *_big;
    NSString *_middle;
    NSString *_small;
    NSString *_thum;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)keyMapper;
@property(retain, nonatomic) NSString *thum; // @synthesize thum=_thum;
@property(retain, nonatomic) NSString *small; // @synthesize small=_small;
@property(retain, nonatomic) NSString *middle; // @synthesize middle=_middle;
@property(retain, nonatomic) NSString *big; // @synthesize big=_big;
@property(retain, nonatomic) NSString *huge; // @synthesize huge=_huge;
- (void).cxx_destruct;

@end

