//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UIScrollViewDelegate.h"

@class NSLayoutConstraint, NSMutableArray, NSString, UIPageControl, UIScrollView;

@interface ItemDetailLargeImageCell : UITableViewCell <UIScrollViewDelegate>
{
    CDUnknownBlockType _specPressEvent;
    NSLayoutConstraint *_scrollHeightConstraint;
    NSLayoutConstraint *_scrollTopConstraint;
    UIScrollView *_itemScrollView;
    UIPageControl *_pageView;
    NSMutableArray *_photoImageViewArray;
}

+ (double)heightForRowAtIndexPath:(id)arg1;
@property(retain, nonatomic) NSMutableArray *photoImageViewArray; // @synthesize photoImageViewArray=_photoImageViewArray;
@property(nonatomic) __weak UIPageControl *pageView; // @synthesize pageView=_pageView;
@property(nonatomic) __weak UIScrollView *itemScrollView; // @synthesize itemScrollView=_itemScrollView;
@property(nonatomic) __weak NSLayoutConstraint *scrollTopConstraint; // @synthesize scrollTopConstraint=_scrollTopConstraint;
@property(nonatomic) __weak NSLayoutConstraint *scrollHeightConstraint; // @synthesize scrollHeightConstraint=_scrollHeightConstraint;
@property(copy, nonatomic) CDUnknownBlockType specPressEvent; // @synthesize specPressEvent=_specPressEvent;
- (void).cxx_destruct;
- (void)onSpecViewPress;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)cellForRowAtIndexPath:(id)arg1 sourceData:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

