//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "DZNEmptyDataSetDelegate.h"
#import "DZNEmptyDataSetSource.h"
#import "ItemListDelegate.h"
#import "ProductListItemCellDelegate.h"
#import "RMPZoomTransitionAnimating.h"
#import "UINavigationControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class FDAppDelegate, FDProductItemListData, NSDictionary, NSIndexPath, NSMutableArray, NSString, UIActivityIndicatorView, UIButton, UITableView;

@interface ItemListViewController : FDBaseViewController <ProductListItemCellDelegate, RMPZoomTransitionAnimating, UINavigationControllerDelegate, DZNEmptyDataSetSource, DZNEmptyDataSetDelegate, UITableViewDataSource, UITableViewDelegate, ItemListDelegate>
{
    NSIndexPath *_indexPathForSelectedRow;
    FDProductItemListData *_productListData;
    NSMutableArray *items;
    int sort;
    FDAppDelegate *delegate;
    int priceSorting;
    _Bool isRefreshNeeded;
    int currentPage;
    _Bool isScrollNeeded;
    _Bool _hasMoreItems;
    _Bool _isLoadingMoreItems;
    UITableView *_itemListTableView;
    UIButton *_sortByNewButton;
    UIButton *_sortByHotButton;
    UIButton *_sortByPriceButton;
    UIActivityIndicatorView *_loadMoreIndicator;
    NSDictionary *_category;
    NSDictionary *_cartItemToAdd;
}

@property(retain, nonatomic) NSDictionary *cartItemToAdd; // @synthesize cartItemToAdd=_cartItemToAdd;
@property(retain) NSDictionary *category; // @synthesize category=_category;
@property(retain, nonatomic) UIActivityIndicatorView *loadMoreIndicator; // @synthesize loadMoreIndicator=_loadMoreIndicator;
@property(nonatomic) _Bool isLoadingMoreItems; // @synthesize isLoadingMoreItems=_isLoadingMoreItems;
@property(nonatomic) _Bool hasMoreItems; // @synthesize hasMoreItems=_hasMoreItems;
@property(nonatomic) __weak UIButton *sortByPriceButton; // @synthesize sortByPriceButton=_sortByPriceButton;
@property(nonatomic) __weak UIButton *sortByHotButton; // @synthesize sortByHotButton=_sortByHotButton;
@property(nonatomic) __weak UIButton *sortByNewButton; // @synthesize sortByNewButton=_sortByNewButton;
@property(nonatomic) __weak UITableView *itemListTableView; // @synthesize itemListTableView=_itemListTableView;
- (void).cxx_destruct;
- (double)verticalOffsetForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (id)descriptionForEmptyDataSet:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (struct CGRect)transitionDestinationImageViewFrame;
- (id)transitionSourceImageView;
- (void)setRefreshFlag:(_Bool)arg1;
- (void)onSortItemSelected:(id)arg1;
- (_Bool)updateSortButtonState:(int)arg1;
- (void)clearSortButtonState;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)onAddToCartPress:(id)arg1;
- (void)addProduct2CartCell:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)showItemList;
- (void)hideItemList;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)loadItemListWithCategory;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

