//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSLayoutConstraint, UIImageView, UILabel, UITextField;

@interface LocationCell : UITableViewCell
{
    double _layoutFill;
    double _indicatorFill;
    UILabel *_titleLabel;
    UILabel *_contantLabel;
    UIImageView *_iconImageView;
    UITextField *_buildingInfoTextFiled;
    NSLayoutConstraint *_contantLabelTrailingConstraint;
    NSLayoutConstraint *_textFieldTrailingConstraint;
    NSLayoutConstraint *_iconTrailingConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *iconTrailingConstraint; // @synthesize iconTrailingConstraint=_iconTrailingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *textFieldTrailingConstraint; // @synthesize textFieldTrailingConstraint=_textFieldTrailingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *contantLabelTrailingConstraint; // @synthesize contantLabelTrailingConstraint=_contantLabelTrailingConstraint;
@property(nonatomic) __weak UITextField *buildingInfoTextFiled; // @synthesize buildingInfoTextFiled=_buildingInfoTextFiled;
@property(nonatomic) __weak UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(nonatomic) __weak UILabel *contantLabel; // @synthesize contantLabel=_contantLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)initShowArrowViewInDispatch:(id)arg1;
- (void)initShowArrowViewInComfirmOrder:(id)arg1 isFruitdayDispatch:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

