//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "CLLocationManagerDelegate.h"
#import "HotLocationViewDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CLLocationManager, FDHomeViewController, FDViewController, NSArray, NSDictionary, NSMutableArray, NSString, UIButton, UITableView;

@interface LocationViewController : FDBaseViewController <UITableViewDelegate, UITableViewDataSource, CLLocationManagerDelegate, UIAlertViewDelegate, HotLocationViewDelegate>
{
    CLLocationManager *locationManager;
    NSDictionary *locationByGPS;
    NSMutableArray *locations;
    NSArray *hotLocations;
    _Bool isLocationByGPSRetrieved;
    _Bool isRegionNotSupported;
    _Bool _isFirstLaunch;
    _Bool _isSubNavigtion;
    UITableView *_locationsTableView;
    UIButton *_locationByGPSButton;
    FDHomeViewController *_homeViewController;
    FDViewController *_tabBarViewController;
}

@property(nonatomic) _Bool isSubNavigtion; // @synthesize isSubNavigtion=_isSubNavigtion;
@property(nonatomic) _Bool isFirstLaunch; // @synthesize isFirstLaunch=_isFirstLaunch;
@property(retain, nonatomic) FDViewController *tabBarViewController; // @synthesize tabBarViewController=_tabBarViewController;
@property(retain, nonatomic) FDHomeViewController *homeViewController; // @synthesize homeViewController=_homeViewController;
@property(nonatomic) __weak UIButton *locationByGPSButton; // @synthesize locationByGPSButton=_locationByGPSButton;
@property(nonatomic) __weak UITableView *locationsTableView; // @synthesize locationsTableView=_locationsTableView;
- (void).cxx_destruct;
- (void)onCancelSelectLocation:(id)arg1;
- (void)finishSelectingLocation:(id)arg1;
- (void)onLocationByGPSPress:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (_Bool)shouldPerformSegueWithIdentifier:(id)arg1 sender:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)hackLocation;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)locateCity:(id)arg1;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)initLocating;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didSelectHotLocation:(id)arg1;
- (void)initHotLocation;
- (void)loadRegions;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

