//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSLayoutConstraint, UIImageView, UILabel, UIView;

@interface MessageCell : UITableViewCell
{
    UIImageView *_avatarImageView;
    UIView *_stateIndicator;
    UILabel *_authorUsernameLabel;
    UILabel *_contentLabel;
    UILabel *_timestampLabel;
    NSLayoutConstraint *_stateIndicatorWidth;
    NSLayoutConstraint *_usernameLeading;
}

@property(nonatomic) __weak NSLayoutConstraint *usernameLeading; // @synthesize usernameLeading=_usernameLeading;
@property(nonatomic) __weak NSLayoutConstraint *stateIndicatorWidth; // @synthesize stateIndicatorWidth=_stateIndicatorWidth;
@property(retain, nonatomic) UILabel *timestampLabel; // @synthesize timestampLabel=_timestampLabel;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UILabel *authorUsernameLabel; // @synthesize authorUsernameLabel=_authorUsernameLabel;
@property(nonatomic) __weak UIView *stateIndicator; // @synthesize stateIndicator=_stateIndicator;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

