//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UIScrollViewDelegate.h"

@class NSArray, NSDictionary, NSString, SKView, UIButton, UIImageView, UILabel, UIRefreshControl, UIScrollView, UIView;

@interface MyCenterViewController : FDBaseViewController <UIScrollViewDelegate>
{
    NSArray *permissions;
    SKView *_mSKView;
    struct CGRect _iconFrame;
    _Bool _isPullToRefresh;
    _Bool _needSetJpush;
    UILabel *_userName;
    UILabel *_userCreditLabel;
    UILabel *_userCredit;
    UILabel *_userCoupon;
    UILabel *_userBalanceLabel;
    UILabel *_userBalance;
    UIScrollView *_userScrollView;
    UIImageView *_vipImage;
    UIButton *_signInButton;
    UIImageView *_userSmileThum;
    UIView *_userBgView;
    UIView *_border1;
    UIView *_border2;
    UIView *_border3;
    UILabel *_myOrderLabel;
    UILabel *_myShowLabel;
    UILabel *_myFavLabel;
    UILabel *_myGiftLabel;
    UILabel *_myRightLabel;
    UILabel *_myTasteLabel;
    UIButton *_orderButton;
    UIButton *_commentButton;
    UIButton *_favButton;
    UIButton *_giftButton;
    UIButton *_rightButton;
    UIButton *_tasteButton;
    UIImageView *_orderImageView;
    UIImageView *_commentImageView;
    UIImageView *_favImageView;
    UIImageView *_giftImageView;
    UIImageView *_rightImageView;
    UIImageView *_tasteImageView;
    UIView *_orderView;
    UIView *_commentView;
    UIView *_favView;
    UIView *_giftView;
    UIView *_rightView;
    UIView *_tasteView;
    UIView *_centerEntrenceView;
    NSString *_userBadge;
    NSString *_appDescription;
    NSString *_appLink;
    NSDictionary *_myRightInfo;
    NSString *_reGetConnectIdType;
    NSDictionary *_personalData;
    UIRefreshControl *_refreshControl;
    NSArray *_activity;
    UILabel *_balanceLabel;
    UILabel *_couponLabel;
    UIImageView *_myBalanceRedIndicator;
    UIImageView *_myCouponRedIndicator;
    UIImageView *_myGiftRedIndicator;
}

@property(nonatomic) __weak UIImageView *myGiftRedIndicator; // @synthesize myGiftRedIndicator=_myGiftRedIndicator;
@property(nonatomic) __weak UIImageView *myCouponRedIndicator; // @synthesize myCouponRedIndicator=_myCouponRedIndicator;
@property(nonatomic) __weak UIImageView *myBalanceRedIndicator; // @synthesize myBalanceRedIndicator=_myBalanceRedIndicator;
@property(nonatomic) __weak UILabel *couponLabel; // @synthesize couponLabel=_couponLabel;
@property(nonatomic) __weak UILabel *balanceLabel; // @synthesize balanceLabel=_balanceLabel;
@property(retain, nonatomic) NSArray *activity; // @synthesize activity=_activity;
@property(nonatomic) _Bool needSetJpush; // @synthesize needSetJpush=_needSetJpush;
@property(nonatomic) _Bool isPullToRefresh; // @synthesize isPullToRefresh=_isPullToRefresh;
@property(retain, nonatomic) UIRefreshControl *refreshControl; // @synthesize refreshControl=_refreshControl;
@property(retain, nonatomic) NSDictionary *personalData; // @synthesize personalData=_personalData;
@property(retain, nonatomic) NSString *reGetConnectIdType; // @synthesize reGetConnectIdType=_reGetConnectIdType;
@property(retain, nonatomic) NSDictionary *myRightInfo; // @synthesize myRightInfo=_myRightInfo;
@property(retain, nonatomic) NSString *appLink; // @synthesize appLink=_appLink;
@property(retain, nonatomic) NSString *appDescription; // @synthesize appDescription=_appDescription;
@property(retain, nonatomic) NSString *userBadge; // @synthesize userBadge=_userBadge;
@property(nonatomic) __weak UIView *centerEntrenceView; // @synthesize centerEntrenceView=_centerEntrenceView;
@property(nonatomic) __weak UIView *tasteView; // @synthesize tasteView=_tasteView;
@property(nonatomic) __weak UIView *rightView; // @synthesize rightView=_rightView;
@property(nonatomic) __weak UIView *giftView; // @synthesize giftView=_giftView;
@property(nonatomic) __weak UIView *favView; // @synthesize favView=_favView;
@property(nonatomic) __weak UIView *commentView; // @synthesize commentView=_commentView;
@property(nonatomic) __weak UIView *orderView; // @synthesize orderView=_orderView;
@property(nonatomic) __weak UIImageView *tasteImageView; // @synthesize tasteImageView=_tasteImageView;
@property(nonatomic) __weak UIImageView *rightImageView; // @synthesize rightImageView=_rightImageView;
@property(nonatomic) __weak UIImageView *giftImageView; // @synthesize giftImageView=_giftImageView;
@property(nonatomic) __weak UIImageView *favImageView; // @synthesize favImageView=_favImageView;
@property(nonatomic) __weak UIImageView *commentImageView; // @synthesize commentImageView=_commentImageView;
@property(nonatomic) __weak UIImageView *orderImageView; // @synthesize orderImageView=_orderImageView;
@property(nonatomic) __weak UIButton *tasteButton; // @synthesize tasteButton=_tasteButton;
@property(nonatomic) __weak UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(nonatomic) __weak UIButton *giftButton; // @synthesize giftButton=_giftButton;
@property(nonatomic) __weak UIButton *favButton; // @synthesize favButton=_favButton;
@property(nonatomic) __weak UIButton *commentButton; // @synthesize commentButton=_commentButton;
@property(nonatomic) __weak UIButton *orderButton; // @synthesize orderButton=_orderButton;
@property(nonatomic) __weak UILabel *myTasteLabel; // @synthesize myTasteLabel=_myTasteLabel;
@property(nonatomic) __weak UILabel *myRightLabel; // @synthesize myRightLabel=_myRightLabel;
@property(nonatomic) __weak UILabel *myGiftLabel; // @synthesize myGiftLabel=_myGiftLabel;
@property(nonatomic) __weak UILabel *myFavLabel; // @synthesize myFavLabel=_myFavLabel;
@property(nonatomic) __weak UILabel *myShowLabel; // @synthesize myShowLabel=_myShowLabel;
@property(nonatomic) __weak UILabel *myOrderLabel; // @synthesize myOrderLabel=_myOrderLabel;
@property(nonatomic) __weak UIView *border3; // @synthesize border3=_border3;
@property(nonatomic) __weak UIView *border2; // @synthesize border2=_border2;
@property(nonatomic) __weak UIView *border1; // @synthesize border1=_border1;
@property(nonatomic) __weak UIView *userBgView; // @synthesize userBgView=_userBgView;
@property(nonatomic) __weak UIImageView *userSmileThum; // @synthesize userSmileThum=_userSmileThum;
@property(nonatomic) __weak UIButton *signInButton; // @synthesize signInButton=_signInButton;
@property(nonatomic) __weak UIImageView *vipImage; // @synthesize vipImage=_vipImage;
@property(nonatomic) __weak UIScrollView *userScrollView; // @synthesize userScrollView=_userScrollView;
@property(nonatomic) __weak UILabel *userBalance; // @synthesize userBalance=_userBalance;
@property(nonatomic) __weak UILabel *userBalanceLabel; // @synthesize userBalanceLabel=_userBalanceLabel;
@property(nonatomic) __weak UILabel *userCoupon; // @synthesize userCoupon=_userCoupon;
@property(nonatomic) __weak UILabel *userCredit; // @synthesize userCredit=_userCredit;
@property(nonatomic) __weak UILabel *userCreditLabel; // @synthesize userCreditLabel=_userCreditLabel;
@property(nonatomic) __weak UILabel *userName; // @synthesize userName=_userName;
- (void).cxx_destruct;
- (id)creatFruitNodes;
- (void)initFruitScene;
- (void)dealloc;
- (void)pullToRefresh:(id)arg1;
- (void)onTopupPressed:(id)arg1;
- (void)onThumbPressed:(id)arg1;
- (void)onMyCreditPressed:(id)arg1;
- (void)onMyCouponPressed:(id)arg1;
- (void)onMyAddressPressed:(id)arg1;
- (void)onMyRightPressed:(id)arg1;
- (void)onMyGiftPressed:(id)arg1;
- (void)onMyFavPressed:(id)arg1;
- (void)onMyOrderShowPressed:(id)arg1;
- (void)onMyOrderPressed:(id)arg1;
- (void)goToUserLevel;
- (void)onShowUserInfoCard;
- (void)goToSingIn;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (_Bool)shouldPerformSegueWithIdentifier:(id)arg1 sender:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)tagsAliasCallback:(int)arg1 tags:(id)arg2 alias:(id)arg3;
- (void)setJpushUserInfo:(id)arg1;
- (void)setFaceImage:(id)arg1;
- (void)loadUserInfoData;
- (void)loadInfoAlert;
- (id)updateAlertLabel:(int)arg1 labelText:(id)arg2;
- (void)updateRedIndicator:(id)arg1;
- (void)updateAlertInfo:(id)arg1;
- (void)showHideBusyIndicator:(_Bool)arg1;
- (void)performSingleImageViewAnimation:(id)arg1 oriFrame:(struct CGRect)arg2;
- (void)performSingleViewAnimation:(float)arg1 withView:(id)arg2 withImageView:(id)arg3;
- (void)performViewAnimation;
- (void)updateRefreshControl;
- (void)clearUserInfo;
- (void)removeRedIndicator;
- (void)initialRedIndicator;
- (void)initialImageView;
- (void)adjustFontForCenterEntrence;
- (void)initBaseOnLoginStatus;
- (void)initView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

