//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "DZNEmptyDataSetDelegate.h"
#import "DZNEmptyDataSetSource.h"
#import "GiftCellDelegate.h"
#import "UITextFieldDelegate.h"

@class FDGiftProductListData, NSString, UILabel, UITableView, UITextField, UIView;

@interface MyGiftViewController : FDBaseViewController <DZNEmptyDataSetSource, DZNEmptyDataSetDelegate, GiftCellDelegate, UITextFieldDelegate>
{
    FDGiftProductListData *_giftListData;
    UITableView *_myGiftTableView;
    UIView *_borderUp;
    UIView *_borderDown;
    UITextField *_giftCodeInput;
    Class _sourceViewControllerClass;
    long long _tag;
    UIView *_codeView;
    UILabel *_giftTipsLabel;
}

@property(nonatomic) __weak UILabel *giftTipsLabel; // @synthesize giftTipsLabel=_giftTipsLabel;
@property(nonatomic) __weak UIView *codeView; // @synthesize codeView=_codeView;
@property long long tag; // @synthesize tag=_tag;
@property(retain, nonatomic) Class sourceViewControllerClass; // @synthesize sourceViewControllerClass=_sourceViewControllerClass;
@property(nonatomic) __weak UITextField *giftCodeInput; // @synthesize giftCodeInput=_giftCodeInput;
@property(nonatomic) __weak UIView *borderDown; // @synthesize borderDown=_borderDown;
@property(nonatomic) __weak UIView *borderUp; // @synthesize borderUp=_borderUp;
@property(nonatomic) __weak UITableView *myGiftTableView; // @synthesize myGiftTableView=_myGiftTableView;
- (void).cxx_destruct;
- (void)emptyDataSetDidTapButton:(id)arg1;
- (double)verticalOffsetForEmptyDataSet:(id)arg1;
- (id)buttonTitleForEmptyDataSet:(id)arg1 forState:(unsigned long long)arg2;
- (id)descriptionForEmptyDataSet:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (void)onGiftGetPressed:(id)arg1;
- (void)backToPreviousView;
- (_Bool)needAutoBack;
- (void)getGiftFromCode:(id)arg1;
- (void)recordGiftFromCode;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)addGiftToCart:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)alertErrorMessage:(id)arg1;
- (void)loadMyGiftList;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)hideKeyBoard;
- (void)onViewPressed:(id)arg1;
- (void)UIUpRefresh;
- (void)UIForLabel;
- (void)UIForCALayer;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

