//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSLayoutConstraint, UIImageView, UILabel;

@interface MyMarkedItemCell : UITableViewCell
{
    UIImageView *_categoryIcon;
    UILabel *_categoryTitle;
    UILabel *_pubDate;
    UILabel *_postTitle;
    UILabel *_postDesc;
    UIImageView *_postThumb;
    NSLayoutConstraint *_separatorHeight;
}

@property(nonatomic) __weak NSLayoutConstraint *separatorHeight; // @synthesize separatorHeight=_separatorHeight;
@property(nonatomic) __weak UIImageView *postThumb; // @synthesize postThumb=_postThumb;
@property(nonatomic) __weak UILabel *postDesc; // @synthesize postDesc=_postDesc;
@property(nonatomic) __weak UILabel *postTitle; // @synthesize postTitle=_postTitle;
@property(nonatomic) __weak UILabel *pubDate; // @synthesize pubDate=_pubDate;
@property(nonatomic) __weak UILabel *categoryTitle; // @synthesize categoryTitle=_categoryTitle;
@property(nonatomic) __weak UIImageView *categoryIcon; // @synthesize categoryIcon=_categoryIcon;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

