//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView;

@interface MyRightTableViewCell : UITableViewCell
{
    UIImageView *_couponBackground;
}

@property(nonatomic) __weak UIImageView *couponBackground; // @synthesize couponBackground=_couponBackground;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

