//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "DZNEmptyDataSetDelegate.h"
#import "DZNEmptyDataSetSource.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UMSocialUIDelegate.h"

@class NSDictionary, NSMutableArray, NSString, UITableView, UserRankData;

@interface MyRightListViewController : FDBaseViewController <DZNEmptyDataSetSource, DZNEmptyDataSetDelegate, UITableViewDataSource, UITableViewDelegate, UMSocialUIDelegate>
{
    _Bool _hasPerformAnimation;
    UITableView *_myRightsTableView;
    NSMutableArray *_items;
    NSDictionary *_myRightInfo;
    NSDictionary *_myOffilineRightInfo;
    UserRankData *_userLevelData;
    NSString *_qrUrl;
    NSString *_activityName;
    NSString *_apiName;
}

@property _Bool hasPerformAnimation; // @synthesize hasPerformAnimation=_hasPerformAnimation;
@property(retain, nonatomic) NSString *apiName; // @synthesize apiName=_apiName;
@property(retain, nonatomic) NSString *activityName; // @synthesize activityName=_activityName;
@property(retain, nonatomic) NSString *qrUrl; // @synthesize qrUrl=_qrUrl;
@property(retain, nonatomic) UserRankData *userLevelData; // @synthesize userLevelData=_userLevelData;
@property(retain, nonatomic) NSDictionary *myOffilineRightInfo; // @synthesize myOffilineRightInfo=_myOffilineRightInfo;
@property(retain, nonatomic) NSDictionary *myRightInfo; // @synthesize myRightInfo=_myRightInfo;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(nonatomic) __weak UITableView *myRightsTableView; // @synthesize myRightsTableView=_myRightsTableView;
- (void).cxx_destruct;
- (void)emptyDataSetDidTapButton:(id)arg1;
- (id)buttonTitleForEmptyDataSet:(id)arg1 forState:(unsigned long long)arg2;
- (id)descriptionForEmptyDataSet:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)shareRight;
- (void)goToUserLevelCenter;
- (void)checkWhetherSendDiscountCode:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)alertErrorMessage:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)showHideBusyIndicator:(_Bool)arg1;
- (void)performCouponAnimation;
- (void)loadMyRightsList;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

