//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

@class CategoryViewModel, DoubleDeckTableView;

@interface NewCategoryViewController : FDBaseViewController
{
    DoubleDeckTableView *_doubleDeckTableView;
    CategoryViewModel *_viewModel;
}

@property(retain, nonatomic) CategoryViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)onSearchPressed;
- (void)initSearchIcon;
- (void)initDoubleDeckTableView;
- (void)bindViewModel;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

