//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NJKScrollFullScreen;

@protocol NJKScrollFullscreenDelegate <NSObject>
- (void)scrollFullScreenScrollViewDidEndDraggingScrollDown:(NJKScrollFullScreen *)arg1;
- (void)scrollFullScreenScrollViewDidEndDraggingScrollUp:(NJKScrollFullScreen *)arg1;
- (void)scrollFullScreen:(NJKScrollFullScreen *)arg1 scrollViewDidScrollDown:(double)arg2;
- (void)scrollFullScreen:(NJKScrollFullScreen *)arg1 scrollViewDidScrollUp:(double)arg2;
@end

