//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@interface NoItemHintCell : UITableViewCell
{
    id <NoItemHintCellDelegate> _delegate;
}

@property(nonatomic) id <NoItemHintCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onCreatePostPressed:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

