//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BaiKeCommentData, M80AttributedLabel;

@interface OfficialReplyView : UIView
{
    M80AttributedLabel *_contentLabel;
    UIView *_garyView;
    BaiKeCommentData *_officialReply;
}

+ (double)viewHeight:(id)arg1 viewWidth:(double)arg2;
@property(retain, nonatomic) BaiKeCommentData *officialReply; // @synthesize officialReply=_officialReply;
- (void).cxx_destruct;
- (void)initContentLabel;
- (void)initGaryView;
- (void)initJianTou;
- (void)initialize;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

