//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface OfflineCartCell : UITableViewCell
{
    CDUnknownBlockType _addProductNumberEvent;
    CDUnknownBlockType _reduceProductNumberEvent;
    UIImageView *_productImageView;
    UILabel *_productNameLabel;
    UILabel *_productNumLabel;
    UILabel *_productPriceLabel;
    UIButton *_reduceButton;
    UIButton *_plusButton;
    UIView *_segmentLine;
}

@property(nonatomic) __weak UIView *segmentLine; // @synthesize segmentLine=_segmentLine;
@property(nonatomic) __weak UIButton *plusButton; // @synthesize plusButton=_plusButton;
@property(nonatomic) __weak UIButton *reduceButton; // @synthesize reduceButton=_reduceButton;
@property(nonatomic) __weak UILabel *productPriceLabel; // @synthesize productPriceLabel=_productPriceLabel;
@property(nonatomic) __weak UILabel *productNumLabel; // @synthesize productNumLabel=_productNumLabel;
@property(nonatomic) __weak UILabel *productNameLabel; // @synthesize productNameLabel=_productNameLabel;
@property(nonatomic) __weak UIImageView *productImageView; // @synthesize productImageView=_productImageView;
@property(copy, nonatomic) CDUnknownBlockType reduceProductNumberEvent; // @synthesize reduceProductNumberEvent=_reduceProductNumberEvent;
@property(copy, nonatomic) CDUnknownBlockType addProductNumberEvent; // @synthesize addProductNumberEvent=_addProductNumberEvent;
- (void).cxx_destruct;
- (void)plusAction:(id)arg1;
- (void)reduceAction:(id)arg1;
- (void)checkStockNum:(id)arg1;
- (void)loadOfflineCartWithProductData:(id)arg1 indexPath:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

