//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class FDBaseViewController, NSLayoutConstraint, UIActivityIndicatorView, UIButton, UILabel;

@interface OfflineHomeHeaderView : UIView
{
    FDBaseViewController *_target;
    CDUnknownBlockType _startLocationBlock;
    CDUnknownBlockType _moreAddressBlock;
    UIActivityIndicatorView *_loadingIndicator;
    UIButton *_startLocationButton;
    UIButton *_moreAddressButton;
    UILabel *_addressNameLabel;
    NSLayoutConstraint *_addressNameLabelWidthConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *addressNameLabelWidthConstraint; // @synthesize addressNameLabelWidthConstraint=_addressNameLabelWidthConstraint;
@property(nonatomic) __weak UILabel *addressNameLabel; // @synthesize addressNameLabel=_addressNameLabel;
@property(nonatomic) __weak UIButton *moreAddressButton; // @synthesize moreAddressButton=_moreAddressButton;
@property(nonatomic) __weak UIButton *startLocationButton; // @synthesize startLocationButton=_startLocationButton;
@property(nonatomic) __weak UIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(copy, nonatomic) CDUnknownBlockType moreAddressBlock; // @synthesize moreAddressBlock=_moreAddressBlock;
@property(copy, nonatomic) CDUnknownBlockType startLocationBlock; // @synthesize startLocationBlock=_startLocationBlock;
- (void).cxx_destruct;
- (void)stopLoading;
- (void)startLoading;
- (id)getLocationStatus;
- (void)moreAddressAction:(id)arg1;
- (void)startLocationAction:(id)arg1;
- (void)reloadHeaderViewWithUserAddress:(id)arg1 target:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

