//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface OfflineUserAddressData : NSObject
{
    NSString *_province;
    NSString *_city;
    NSString *_area;
    NSString *_bszone;
    NSString *_building;
    NSString *_address;
    NSString *_storeName;
    NSString *_receiverName;
    NSString *_receiverPhoneNum;
    NSString *_cityId;
    NSString *_areaId;
    NSString *_bszoneId;
    NSString *_buildingId;
    NSString *_storeId;
    NSMutableArray *_stores;
}

@property(retain, nonatomic) NSMutableArray *stores; // @synthesize stores=_stores;
@property(retain, nonatomic) NSString *storeId; // @synthesize storeId=_storeId;
@property(retain, nonatomic) NSString *buildingId; // @synthesize buildingId=_buildingId;
@property(retain, nonatomic) NSString *bszoneId; // @synthesize bszoneId=_bszoneId;
@property(retain, nonatomic) NSString *areaId; // @synthesize areaId=_areaId;
@property(retain, nonatomic) NSString *cityId; // @synthesize cityId=_cityId;
@property(retain, nonatomic) NSString *receiverPhoneNum; // @synthesize receiverPhoneNum=_receiverPhoneNum;
@property(retain, nonatomic) NSString *receiverName; // @synthesize receiverName=_receiverName;
@property(retain, nonatomic) NSString *storeName; // @synthesize storeName=_storeName;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
@property(retain, nonatomic) NSString *building; // @synthesize building=_building;
@property(retain, nonatomic) NSString *bszone; // @synthesize bszone=_bszone;
@property(retain, nonatomic) NSString *area; // @synthesize area=_area;
@property(retain, nonatomic) NSString *city; // @synthesize city=_city;
@property(retain, nonatomic) NSString *province; // @synthesize province=_province;
- (void).cxx_destruct;
- (void)setDataEmpty;
- (void)initOfflineUserAddressDataWithDictionary:(id)arg1;

@end

