//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "LocationCellDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"
#import "XTPickerViewDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString, OfflinePayData, OfflineUserAddressData, UIButton, UILabel, UITableView, UITextField, UITextView, XTPickerView, XTPresentCartView;

@interface OfflineConfirmOrderViewController : FDBaseViewController <LocationCellDelegate, UITextFieldDelegate, UITextViewDelegate, UIGestureRecognizerDelegate, XTPickerViewDelegate>
{
    UITableView *_mTableView;
    UILabel *_mTotalLabel;
    UIButton *_mAccountsButton;
    _Bool _isCostCredit;
    NSMutableArray *_titleArray;
    NSMutableArray *_sectionTitle;
    UITextField *_tempTextField;
    OfflinePayData *_payOptionData;
    UITextView *_tempTextView;
    XTPickerView *_stimePickerView;
    _Bool _isFirstRequest;
    int _transportType;
    OfflineUserAddressData *_userAddressData;
    XTPresentCartView *_cartView;
    NSMutableDictionary *_shoppingInfo;
    NSMutableArray *_selectedProducts;
    UITextField *_authCodeInput;
    NSString *_authConnectId;
    NSString *_authCode;
    NSString *_jfMoney;
    NSString *_cardNumber;
    NSString *_payId;
    NSString *_payParentId;
}

@property(retain, nonatomic) NSString *payParentId; // @synthesize payParentId=_payParentId;
@property(retain, nonatomic) NSString *payId; // @synthesize payId=_payId;
@property(retain, nonatomic) NSString *cardNumber; // @synthesize cardNumber=_cardNumber;
@property(retain, nonatomic) NSString *jfMoney; // @synthesize jfMoney=_jfMoney;
@property(retain, nonatomic) NSString *authCode; // @synthesize authCode=_authCode;
@property(retain, nonatomic) NSString *authConnectId; // @synthesize authConnectId=_authConnectId;
@property(retain, nonatomic) UITextField *authCodeInput; // @synthesize authCodeInput=_authCodeInput;
@property(nonatomic) int transportType; // @synthesize transportType=_transportType;
@property(retain, nonatomic) NSMutableArray *selectedProducts; // @synthesize selectedProducts=_selectedProducts;
@property(retain, nonatomic) NSMutableDictionary *shoppingInfo; // @synthesize shoppingInfo=_shoppingInfo;
@property(retain, nonatomic) XTPresentCartView *cartView; // @synthesize cartView=_cartView;
@property(retain, nonatomic) OfflineUserAddressData *userAddressData; // @synthesize userAddressData=_userAddressData;
- (void).cxx_destruct;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)CostCreditControlActionInLocationCell:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)cellForNormalAtIndexPath:(id)arg1;
- (id)cellForOrderProductListAtIndexPath:(id)arg1;
- (id)cellForOrderRemarkAtIndexPath:(id)arg1;
- (id)cellForCostCreditAtIndexPath:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)checkStoreInfoVaild;
- (void)resetTitleArray;
- (void)go2DispatchVC;
- (void)confirmAuthCodeInput:(id)arg1;
- (void)cancelAuthCode;
- (void)insertSelectedProductsAndSectionTitle;
- (id)getSelectedProductAtIndexPath:(long long)arg1;
- (id)getSelectedProducts:(id)arg1;
- (void)updateOrderInfo:(id)arg1 WithType:(int)arg2 WithResult:(CDUnknownBlockType)arg3;
- (void)setTotalPrice:(id)arg1;
- (void)fillTempData;
- (void)resetTempData;
- (_Bool)checkOrderInfoFinished;
- (void)onSectionHeaderPressed:(id)arg1;
- (void)onViewTapped:(id)arg1;
- (void)addTapToEndEdit;
- (void)showMobileAuthCodeDialog;
- (void)initPickerSelectedRow;
- (void)requestSendMobileTicket:(id)arg1;
- (void)requestSubmitOrder;
- (void)requestInitOrderWithResult:(CDUnknownBlockType)arg1 WithType:(int)arg2;
- (void)accountsAction:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

