//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface OfflineBuildingData : NSObject
{
    NSString *_latitude;
    NSString *_longitude;
    NSString *_city_name;
    NSString *_city_id;
    NSString *_area_name;
    NSString *_area_id;
    NSString *_bszone_name;
    NSString *_bszone_id;
    NSString *_building_name;
    NSString *_building_id;
    NSString *_store_id;
    NSString *_distance;
    NSString *_addr;
    _Bool _isSelectBuilding;
    NSMutableArray *_stores;
}

@property(retain, nonatomic) NSMutableArray *stores; // @synthesize stores=_stores;
@property(nonatomic) _Bool isSelectBuilding; // @synthesize isSelectBuilding=_isSelectBuilding;
@property(retain, nonatomic) NSString *addr; // @synthesize addr=_addr;
@property(retain, nonatomic) NSString *distance; // @synthesize distance=_distance;
@property(retain, nonatomic) NSString *store_id; // @synthesize store_id=_store_id;
@property(retain, nonatomic) NSString *building_id; // @synthesize building_id=_building_id;
@property(retain, nonatomic) NSString *building_name; // @synthesize building_name=_building_name;
@property(retain, nonatomic) NSString *bszone_id; // @synthesize bszone_id=_bszone_id;
@property(retain, nonatomic) NSString *bszone_name; // @synthesize bszone_name=_bszone_name;
@property(retain, nonatomic) NSString *area_id; // @synthesize area_id=_area_id;
@property(retain, nonatomic) NSString *area_name; // @synthesize area_name=_area_name;
@property(retain, nonatomic) NSString *city_id; // @synthesize city_id=_city_id;
@property(retain, nonatomic) NSString *city_name; // @synthesize city_name=_city_name;
@property(retain, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
- (void).cxx_destruct;
- (void)setDataEmpty;
- (void)initOfflineBuildingDataWithDictionary:(id)arg1;

@end

