//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSMutableArray, UIImageView, UILabel;

@interface OfflineStoreHeaderCell : UITableViewCell
{
    NSMutableArray *_categoryList;
    UILabel *_storeTitleLabel;
    UIImageView *_storeIconImageView;
    UILabel *_storeDesLabel;
    CDUnknownBlockType _checkAllBlock;
}

@property(copy, nonatomic) CDUnknownBlockType checkAllBlock; // @synthesize checkAllBlock=_checkAllBlock;
@property(nonatomic) __weak UILabel *storeDesLabel; // @synthesize storeDesLabel=_storeDesLabel;
@property(nonatomic) __weak UIImageView *storeIconImageView; // @synthesize storeIconImageView=_storeIconImageView;
@property(nonatomic) __weak UILabel *storeTitleLabel; // @synthesize storeTitleLabel=_storeTitleLabel;
@property(retain, nonatomic) NSMutableArray *categoryList; // @synthesize categoryList=_categoryList;
- (void).cxx_destruct;
- (id)regionName;
- (void)checkAllAction:(id)arg1;
- (void)cellForRowsAtIndexPath:(id)arg1 dataSource:(id)arg2 target:(id)arg3;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

