//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "RMPZoomTransitionAnimating.h"
#import "UINavigationControllerDelegate.h"

@class HMSegmentedControl, NSMutableArray, NSString, OfflineCategoryDataModel, UIScrollView, UIView, UIViewController;

@interface OfflineCategoryListViewController : FDBaseViewController <RMPZoomTransitionAnimating, UINavigationControllerDelegate>
{
    HMSegmentedControl *_segmentedControl;
    UIViewController *_currentViewController;
    long long _currentIndex;
    _Bool _isFirst;
    _Bool _needPushAnimation;
    id <OfflineCategoryDelegate> _delegate;
    NSMutableArray *_childViewControllers;
    NSMutableArray *_categoryList;
    OfflineCategoryDataModel *_categoryDataModel;
    UIView *_segmentBgView;
    UIScrollView *_mScrollView;
}

@property(nonatomic) __weak UIScrollView *mScrollView; // @synthesize mScrollView=_mScrollView;
@property(nonatomic) __weak UIView *segmentBgView; // @synthesize segmentBgView=_segmentBgView;
@property(nonatomic) _Bool needPushAnimation; // @synthesize needPushAnimation=_needPushAnimation;
@property(retain, nonatomic) OfflineCategoryDataModel *categoryDataModel; // @synthesize categoryDataModel=_categoryDataModel;
@property(retain, nonatomic) NSMutableArray *categoryList; // @synthesize categoryList=_categoryList;
@property(retain, nonatomic) NSMutableArray *childViewControllers; // @synthesize childViewControllers=_childViewControllers;
@property(nonatomic) id <OfflineCategoryDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGRect)transitionDestinationImageViewFrame;
- (id)transitionSourceImageView;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)ViewDidScrollToViewController:(id)arg1;
- (void)segmentedControlChangedValue:(id)arg1;
- (void)initHMSegmentView;
- (void)initScrollView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

