//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@class NSMutableArray;

@interface OfflineCategoryScrollView : UIScrollView
{
    NSMutableArray *_itemArray;
    CDUnknownBlockType _clickItemBlock;
}

@property(retain, nonatomic) NSMutableArray *itemArray; // @synthesize itemArray=_itemArray;
@property(copy, nonatomic) CDUnknownBlockType clickItemBlock; // @synthesize clickItemBlock=_clickItemBlock;
- (void).cxx_destruct;
- (void)removeAllItems;
- (void)loadItemWithData:(id)arg1 index:(long long)arg2;
- (void)reloadCategoryScrollViewWithDataArray:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

