//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel;

@interface OfflineBuildingCell : UITableViewCell
{
    UILabel *_buildingNameLabel;
    UILabel *_buildingDistanceLabel;
    UILabel *_buildingAddressLabel;
}

@property(nonatomic) __weak UILabel *buildingAddressLabel; // @synthesize buildingAddressLabel=_buildingAddressLabel;
@property(nonatomic) __weak UILabel *buildingDistanceLabel; // @synthesize buildingDistanceLabel=_buildingDistanceLabel;
@property(nonatomic) __weak UILabel *buildingNameLabel; // @synthesize buildingNameLabel=_buildingNameLabel;
- (void).cxx_destruct;
- (void)loadBuildInfoWithData:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

