//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSLayoutConstraint, UIButton, UIImageView, UILabel, UIView;

@interface OfflineMoreItemCell : UICollectionViewCell
{
    CDUnknownBlockType _plusNumEvent;
    UIView *_pSelloutBgView;
    UIView *_itemBoardView;
    UIImageView *_itemImageView;
    UILabel *_itemNameLabel;
    UILabel *_itemUnitLabel;
    UILabel *_itemPriceLabel;
    UIButton *_plusButton;
    NSLayoutConstraint *_nameLabelHeightConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *nameLabelHeightConstraint; // @synthesize nameLabelHeightConstraint=_nameLabelHeightConstraint;
@property(nonatomic) __weak UIButton *plusButton; // @synthesize plusButton=_plusButton;
@property(nonatomic) __weak UILabel *itemPriceLabel; // @synthesize itemPriceLabel=_itemPriceLabel;
@property(nonatomic) __weak UILabel *itemUnitLabel; // @synthesize itemUnitLabel=_itemUnitLabel;
@property(nonatomic) __weak UILabel *itemNameLabel; // @synthesize itemNameLabel=_itemNameLabel;
@property(nonatomic) __weak UIImageView *itemImageView; // @synthesize itemImageView=_itemImageView;
@property(nonatomic) __weak UIView *itemBoardView; // @synthesize itemBoardView=_itemBoardView;
@property(nonatomic) __weak UIView *pSelloutBgView; // @synthesize pSelloutBgView=_pSelloutBgView;
@property(copy, nonatomic) CDUnknownBlockType plusNumEvent; // @synthesize plusNumEvent=_plusNumEvent;
- (void).cxx_destruct;
- (void)checkStockNum:(id)arg1 num:(id)arg2;
- (void)plusAction:(id)arg1;
- (void)cellForRowAtIndexPath:(id)arg1 sourceData:(id)arg2;
- (void)awakeFromNib;

@end

