//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSMutableArray;

@interface OfflineHomeCheckAllCell : UITableViewCell
{
    NSMutableArray *_categoryList;
    CDUnknownBlockType _checkAllBlock;
}

+ (double)heightForRowAtIndexPath:(id)arg1 dataSource:(id)arg2;
@property(copy, nonatomic) CDUnknownBlockType checkAllBlock; // @synthesize checkAllBlock=_checkAllBlock;
@property(retain, nonatomic) NSMutableArray *categoryList; // @synthesize categoryList=_categoryList;
- (void).cxx_destruct;
- (id)regionName;
- (void)checkAllAction:(id)arg1;
- (void)cellForRowsAtIndexPath:(id)arg1 dataSource:(id)arg2 target:(id)arg3;

@end

