//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class OfflineProductListCell;

@protocol OfflineProductListCellDelegate <NSObject>
- (void)addProductNumActionInProductListCell:(OfflineProductListCell *)arg1;
- (void)reduceProductNumActionInProductListCell:(OfflineProductListCell *)arg1;
@end

