//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface OfflinePayData : NSObject
{
    NSString *_card_money;
    NSString *_use_jf;
    NSString *_goods_money;
    NSString *_stime;
    NSString *_stime_key;
    NSString *_shtime;
    NSString *_user_mobile;
    NSString *_order_jf_limit;
    NSString *_pay_discount;
    NSString *_uid;
    NSString *_pmoney;
    NSString *_can_use_jf;
    NSString *_user_money;
    NSString *_use_card;
    NSString *_method_money;
    NSString *_need_authen_code;
    NSString *_jf_money;
    NSString *_jf_limit_pro;
    NSString *_money;
    NSString *_can_use_card;
    NSString *_user_coupon_num;
    NSString *_pay_parent_id;
    NSString *_pay_id;
    NSString *_pay_icon_url;
    NSString *_pay_name;
    NSString *_card_number;
    NSString *_orderRemark;
    _Bool _hasOrderRemark;
    NSDictionary *_order_address;
    NSDictionary *_cart_info;
    NSArray *_deliver_option;
}

@property(retain, nonatomic) NSArray *deliver_option; // @synthesize deliver_option=_deliver_option;
@property(retain, nonatomic) NSDictionary *cart_info; // @synthesize cart_info=_cart_info;
@property(retain, nonatomic) NSDictionary *order_address; // @synthesize order_address=_order_address;
@property(nonatomic) _Bool hasOrderRemark; // @synthesize hasOrderRemark=_hasOrderRemark;
@property(retain, nonatomic) NSString *orderRemark; // @synthesize orderRemark=_orderRemark;
@property(retain, nonatomic) NSString *card_number; // @synthesize card_number=_card_number;
@property(retain, nonatomic) NSString *pay_icon_url; // @synthesize pay_icon_url=_pay_icon_url;
@property(retain, nonatomic) NSString *pay_name; // @synthesize pay_name=_pay_name;
@property(retain, nonatomic) NSString *pay_id; // @synthesize pay_id=_pay_id;
@property(retain, nonatomic) NSString *pay_parent_id; // @synthesize pay_parent_id=_pay_parent_id;
@property(retain, nonatomic) NSString *user_coupon_num; // @synthesize user_coupon_num=_user_coupon_num;
@property(retain, nonatomic) NSString *can_use_card; // @synthesize can_use_card=_can_use_card;
@property(retain, nonatomic) NSString *money; // @synthesize money=_money;
@property(retain, nonatomic) NSString *jf_limit_pro; // @synthesize jf_limit_pro=_jf_limit_pro;
@property(retain, nonatomic) NSString *jf_money; // @synthesize jf_money=_jf_money;
@property(retain, nonatomic) NSString *need_authen_code; // @synthesize need_authen_code=_need_authen_code;
@property(retain, nonatomic) NSString *method_money; // @synthesize method_money=_method_money;
@property(retain, nonatomic) NSString *use_card; // @synthesize use_card=_use_card;
@property(retain, nonatomic) NSString *user_money; // @synthesize user_money=_user_money;
@property(retain, nonatomic) NSString *can_use_jf; // @synthesize can_use_jf=_can_use_jf;
@property(retain, nonatomic) NSString *pmoney; // @synthesize pmoney=_pmoney;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(retain, nonatomic) NSString *pay_discount; // @synthesize pay_discount=_pay_discount;
@property(retain, nonatomic) NSString *order_jf_limit; // @synthesize order_jf_limit=_order_jf_limit;
@property(retain, nonatomic) NSString *user_mobile; // @synthesize user_mobile=_user_mobile;
@property(retain, nonatomic) NSString *shtime; // @synthesize shtime=_shtime;
@property(retain, nonatomic) NSString *stime_key; // @synthesize stime_key=_stime_key;
@property(retain, nonatomic) NSString *stime; // @synthesize stime=_stime;
@property(retain, nonatomic) NSString *goods_money; // @synthesize goods_money=_goods_money;
@property(retain, nonatomic) NSString *use_jf; // @synthesize use_jf=_use_jf;
@property(retain, nonatomic) NSString *card_money; // @synthesize card_money=_card_money;
- (void).cxx_destruct;
- (void)setDataEmpty;
- (void)initOfflinePayDataWithDictionary:(id)arg1;

@end

