//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UISearchBarDelegate.h"

@class NSLayoutConstraint, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, OfflineBuildingListData, OfflineDispatchViewController, OfflineUserAddressData, UISearchBar, UITableView;

@interface OfflineSelectBuildingViewController : FDBaseViewController <UISearchBarDelegate>
{
    UITableView *_mTableView;
    UISearchBar *_mSearchBar;
    NSLayoutConstraint *_searchBarTopConstraint;
    OfflineBuildingListData *_buildingListData;
    NSMutableDictionary *_buildingDataDict;
    NSMutableArray *_matchedbuildingArray;
    NSMutableArray *_allKeysArr;
    int _buildingShowType;
    NSObject<OS_dispatch_queue> *search_queue;
    OfflineUserAddressData *_userAddressData;
    OfflineDispatchViewController *_disPatchVC;
}

@property(retain, nonatomic) OfflineDispatchViewController *disPatchVC; // @synthesize disPatchVC=_disPatchVC;
@property(retain, nonatomic) OfflineUserAddressData *userAddressData; // @synthesize userAddressData=_userAddressData;
- (void).cxx_destruct;
- (void)dispatchBySelfAction:(id)arg1;
- (void)comeBackAction:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (_Bool)searchBarShouldEndEditing:(id)arg1;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (void)searchDisplayControllerDidBeginSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)phonetic:(id)arg1;
- (id)getAllKeyFromDataArray:(id)arg1;
- (void)getSearchResult:(id)arg1 searchText:(id)arg2;
- (void)requestGetBuildingList;
- (void)viewDidLayoutSubviews;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

