//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UILabel, UIViewController;

@interface OfflineBuildingCellHeaderView : UIView
{
    UIViewController *_target;
    UIButton *_moreButton;
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
}

@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(nonatomic) __weak UIButton *moreButton; // @synthesize moreButton=_moreButton;
- (void).cxx_destruct;
- (void)moreAction:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 target:(id)arg2;

@end

