//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

@class OfflineDispatchViewController, UISegmentedControl, UIViewController, XTPresentCartView;

@interface OfflineViewControllerContainer : FDBaseViewController
{
    UIViewController *_currentViewController;
    OfflineDispatchViewController *_firstViewController;
    _Bool _isFirstUsed;
    int _lBSShowType;
    UISegmentedControl *_transportTypeSegment;
    XTPresentCartView *_cartView;
}

@property(retain, nonatomic) XTPresentCartView *cartView; // @synthesize cartView=_cartView;
@property(nonatomic) int lBSShowType; // @synthesize lBSShowType=_lBSShowType;
@property(retain, nonatomic) UISegmentedControl *transportTypeSegment; // @synthesize transportTypeSegment=_transportTypeSegment;
@property(nonatomic) _Bool isFirstUsed; // @synthesize isFirstUsed=_isFirstUsed;
- (void).cxx_destruct;
- (void)transitionToViewController:(id)arg1;
- (void)segAction:(id)arg1;
- (void)selectedTransportBySelfType;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

