//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

@class NSMutableArray, OfflineDispatchViewController, UITableView, UIView;

@interface OfflineAddressInfoViewController : FDBaseViewController
{
    UITableView *_mTableView;
    UIView *_emptyView;
    NSMutableArray *_addressInfoArray;
    OfflineDispatchViewController *_OfflineDispatchVC;
}

@property(retain, nonatomic) OfflineDispatchViewController *OfflineDispatchVC; // @synthesize OfflineDispatchVC=_OfflineDispatchVC;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)requestGetAddressList;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

