//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@interface OfflineHomeEmptyDataCell : UITableViewCell
{
    CDUnknownBlockType _back2B2CBlock;
    CDUnknownBlockType _changeBuildingIdBlock;
}

+ (id)cellForRowsAtIndexPath:(id)arg1 tableView:(id)arg2 target:(id)arg3;
+ (double)heightForRowAtIndexPath:(id)arg1 dataSource:(id)arg2;
@property(copy, nonatomic) CDUnknownBlockType changeBuildingIdBlock; // @synthesize changeBuildingIdBlock=_changeBuildingIdBlock;
@property(copy, nonatomic) CDUnknownBlockType back2B2CBlock; // @synthesize back2B2CBlock=_back2B2CBlock;
- (void).cxx_destruct;
- (void)changeBuildingIdAction:(id)arg1;
- (void)back2B2CAction:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

