//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

@class NSLayoutConstraint, UIButton, UIImageView;

@interface OfflineGuideViewController : FDBaseViewController
{
    NSLayoutConstraint *_bottomConstraint;
    NSLayoutConstraint *_buttonBottomConstraint;
    UIButton *_finishButton;
    UIImageView *_mImageView;
}

@property(nonatomic) __weak UIImageView *mImageView; // @synthesize mImageView=_mImageView;
@property(nonatomic) __weak UIButton *finishButton; // @synthesize finishButton=_finishButton;
@property(nonatomic) __weak NSLayoutConstraint *buttonBottomConstraint; // @synthesize buttonBottomConstraint=_buttonBottomConstraint;
@property(nonatomic) __weak NSLayoutConstraint *bottomConstraint; // @synthesize bottomConstraint=_bottomConstraint;
- (void).cxx_destruct;
- (void)backToPreviousAction:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

