//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UMSocialUIDelegate.h"

@class FDAppDelegate, NSDictionary, NSMutableArray, NSString, UIButton, UILabel, UIView;

@interface OrderDetailContainerViewController : FDBaseViewController <UMSocialUIDelegate>
{
    UIView *_orderStatusHeader;
    _Bool _onPay;
    _Bool _isDirectPay;
    NSString *orderID;
    NSString *orderBackendId;
    UILabel *_orderInfoTitle;
    UILabel *_orderId;
    UILabel *_orderStatus;
    UIButton *_cancelOrderButton;
    UIButton *_payOrderButton;
    UIButton *_addCommentButton;
    UIButton *_confirmOrderButton;
    UIView *_actionBottomView;
    UIView *_actionHeader;
    UIView *_orderTitleView;
    FDAppDelegate *_delegate;
    NSDictionary *_myRightInfo;
    NSMutableArray *_orderItems;
    NSString *_commentRule;
    NSString *_storePhoneNumber;
    NSDictionary *_orderDetail;
}

@property _Bool isDirectPay; // @synthesize isDirectPay=_isDirectPay;
@property _Bool onPay; // @synthesize onPay=_onPay;
@property(retain, nonatomic) NSDictionary *orderDetail; // @synthesize orderDetail=_orderDetail;
@property(retain, nonatomic) NSString *storePhoneNumber; // @synthesize storePhoneNumber=_storePhoneNumber;
@property(retain, nonatomic) NSString *commentRule; // @synthesize commentRule=_commentRule;
@property(retain, nonatomic) NSMutableArray *orderItems; // @synthesize orderItems=_orderItems;
@property(retain, nonatomic) NSDictionary *myRightInfo; // @synthesize myRightInfo=_myRightInfo;
@property(retain, nonatomic) FDAppDelegate *delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIView *orderTitleView; // @synthesize orderTitleView=_orderTitleView;
@property(retain, nonatomic) UIView *actionHeader; // @synthesize actionHeader=_actionHeader;
@property(retain, nonatomic) UIView *actionBottomView; // @synthesize actionBottomView=_actionBottomView;
@property(retain, nonatomic) UIButton *confirmOrderButton; // @synthesize confirmOrderButton=_confirmOrderButton;
@property(retain, nonatomic) UIButton *addCommentButton; // @synthesize addCommentButton=_addCommentButton;
@property(retain, nonatomic) UIButton *payOrderButton; // @synthesize payOrderButton=_payOrderButton;
@property(retain, nonatomic) UIButton *cancelOrderButton; // @synthesize cancelOrderButton=_cancelOrderButton;
@property(retain, nonatomic) UILabel *orderStatus; // @synthesize orderStatus=_orderStatus;
@property(retain, nonatomic) UILabel *orderId; // @synthesize orderId=_orderId;
@property(retain, nonatomic) UILabel *orderInfoTitle; // @synthesize orderInfoTitle=_orderInfoTitle;
@property(retain, nonatomic) NSString *orderBackendId; // @synthesize orderBackendId;
@property(retain, nonatomic) NSString *orderID; // @synthesize orderID;
- (void).cxx_destruct;
- (void)showGoCommentInAppStore;
- (void)checkWhetherSendDiscountCode:(id)arg1;
- (void)onDialCustomerService:(id)arg1;
- (void)confirmOrder:(id)arg1;
- (void)addComment:(id)arg1;
- (void)processPayOrder:(_Bool)arg1;
- (void)checkOrderCanPay;
- (void)payOrder:(id)arg1;
- (void)payOrderFromList;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)dialCustomerNumber;
- (void)cancelOrder:(id)arg1;
- (void)processCancelOrder;
- (void)processConfirmOrder;
- (void)backToPreviousView;
- (void)alertErrorMessage:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)showHideBusyIndicator:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

