//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class FDCurveImageView, UILabel;

@interface OrderProductListCell : UITableViewCell
{
    FDCurveImageView *_pImageView;
    UILabel *_pNameLabel;
    UILabel *_pUnitLabel;
    UILabel *_pPriceLabel;
    UILabel *_pNumLabel;
}

@property(nonatomic) __weak UILabel *pNumLabel; // @synthesize pNumLabel=_pNumLabel;
@property(nonatomic) __weak UILabel *pPriceLabel; // @synthesize pPriceLabel=_pPriceLabel;
@property(nonatomic) __weak UILabel *pUnitLabel; // @synthesize pUnitLabel=_pUnitLabel;
@property(nonatomic) __weak UILabel *pNameLabel; // @synthesize pNameLabel=_pNameLabel;
@property(nonatomic) __weak FDCurveImageView *pImageView; // @synthesize pImageView=_pImageView;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

