//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface OrderObject : NSObject
{
    NSMutableDictionary *_originalData;
}

@property(retain, nonatomic) NSMutableDictionary *originalData; // @synthesize originalData=_originalData;
- (void).cxx_destruct;
- (id)getAllCartItems;
- (void)setPayment:(id)arg1;
- (id)getPayment;
- (id)getUserMoney;
- (id)getInvoiceAddress;
- (void)setInvoiceAddress:(id)arg1;
- (void)setDeliveryOption:(id)arg1;
- (id)getDeliveryOption;
- (void)setOrderAddress:(id)arg1;
- (id)getOrderAddress;
- (id)initWithDictionary:(id)arg1;

@end

