//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSArray<Optional><ProductDataModel>, NSString<Optional>;

@interface OrderCommentDataModel : FDBaseDataModel
{
    NSString<Optional> *_order_name;
    NSString<Optional> *_order_time;
    NSArray<Optional><ProductDataModel> *_product;
}

@property(retain, nonatomic) NSArray<Optional><ProductDataModel> *product; // @synthesize product=_product;
@property(copy, nonatomic) NSString<Optional> *order_time; // @synthesize order_time=_order_time;
@property(copy, nonatomic) NSString<Optional> *order_name; // @synthesize order_name=_order_name;
- (void).cxx_destruct;

@end

