//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSDictionary, NSLayoutConstraint, NSString, UIImageView, UITableView, UIView, UIViewController;

@interface OrderCompleteViewController : FDBaseViewController <UITableViewDataSource, UITableViewDelegate>
{
    _Bool _isNotDirectPay;
    _Bool _hasShare;
    NSString *_orderName;
    UIViewController *_fromViewController;
    UITableView *_tableView;
    NSLayoutConstraint *_headerImageTop;
    UIImageView *_okImageView;
    UIView *_tableFooterView;
    NSLayoutConstraint *_actionHeaderHeight;
    NSLayoutConstraint *_actionPayViewWidth;
    NSLayoutConstraint *_actionViewBottom;
    NSDictionary *_orderDetail;
    NSDictionary *_myRightInfo;
}

@property(retain, nonatomic) NSDictionary *myRightInfo; // @synthesize myRightInfo=_myRightInfo;
@property _Bool hasShare; // @synthesize hasShare=_hasShare;
@property(nonatomic) _Bool isNotDirectPay; // @synthesize isNotDirectPay=_isNotDirectPay;
@property(retain, nonatomic) NSDictionary *orderDetail; // @synthesize orderDetail=_orderDetail;
@property(nonatomic) __weak NSLayoutConstraint *actionViewBottom; // @synthesize actionViewBottom=_actionViewBottom;
@property(nonatomic) __weak NSLayoutConstraint *actionPayViewWidth; // @synthesize actionPayViewWidth=_actionPayViewWidth;
@property(nonatomic) __weak NSLayoutConstraint *actionHeaderHeight; // @synthesize actionHeaderHeight=_actionHeaderHeight;
@property(nonatomic) __weak UIView *tableFooterView; // @synthesize tableFooterView=_tableFooterView;
@property(nonatomic) __weak UIImageView *okImageView; // @synthesize okImageView=_okImageView;
@property(nonatomic) __weak NSLayoutConstraint *headerImageTop; // @synthesize headerImageTop=_headerImageTop;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIViewController *fromViewController; // @synthesize fromViewController=_fromViewController;
@property(retain, nonatomic) NSString *orderName; // @synthesize orderName=_orderName;
- (void).cxx_destruct;
- (void)bringInMain;
- (void)backHome:(id)arg1;
- (void)checkWhetherSendDiscountCode:(id)arg1;
- (void)onOrderPaid:(id)arg1;
- (void)payInstantly:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)showGoCommentInAppStore;
- (void)updateOrderView:(_Bool)arg1;
- (void)loadOrderDetailWithSuccess:(CDUnknownBlockType)arg1;
- (void)initHeaderView;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

