//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, UIViewController;

@interface PayCenter : NSObject
{
    NSDictionary *_orderInfo;
    UIViewController *_sourceViewController;
    Class _sourceViewControllerClass;
}

+ (id)sharedInstance;
@property(retain, nonatomic) Class sourceViewControllerClass; // @synthesize sourceViewControllerClass=_sourceViewControllerClass;
@property(retain, nonatomic) UIViewController *sourceViewController; // @synthesize sourceViewController=_sourceViewController;
@property(retain, nonatomic) NSDictionary *orderInfo; // @synthesize orderInfo=_orderInfo;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)createPaymentId:(long long)arg1;
- (void)setTopUpPaid;
- (void)setOrderPaid:(id)arg1;
- (void)doBankDirectPay:(id)arg1 withOrderInfo:(id)arg2;
- (void)onAlipayCallback:(id)arg1 success:(CDUnknownBlockType)arg2;
- (void)doAlipayPayOrder:(id)arg1 success:(CDUnknownBlockType)arg2;
- (void)prepareAlipayOrder:(id)arg1 orderMoney:(id)arg2 productDescription:(id)arg3 orderType:(id)arg4 success:(CDUnknownBlockType)arg5;
- (void)payTopUp:(id)arg1 withOrderMoney:(id)arg2 withPayParentId:(long long)arg3 withPayId:(long long)arg4 withFromController:(id)arg5 withFromControllerClass:(Class)arg6;
- (void)payOnline:(id)arg1 fromController:(id)arg2 fromControllerClass:(Class)arg3;

@end

