//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ConfirmOrderViewController, NSDictionary, NSIndexPath, NSMutableDictionary, NSString, OfflineConfirmOrderViewController, UITableView;

@interface PayOptionsViewController : FDBaseViewController <UITableViewDelegate, UITableViewDataSource, UIAlertViewDelegate>
{
    NSMutableDictionary *payOptions;
    NSIndexPath *selectedIndex;
    _Bool _isOfflineOrder;
    _Bool _isNotBalancePay;
    _Bool _canBalancePay;
    UITableView *_payOptionsTableView;
    NSMutableDictionary *_selectedPayment;
    NSDictionary *_region;
    NSString *_orderFee;
    NSString *_userMoney;
    ConfirmOrderViewController *_confirmController;
    OfflineConfirmOrderViewController *_offlineConfirmController;
}

@property _Bool canBalancePay; // @synthesize canBalancePay=_canBalancePay;
@property _Bool isNotBalancePay; // @synthesize isNotBalancePay=_isNotBalancePay;
@property _Bool isOfflineOrder; // @synthesize isOfflineOrder=_isOfflineOrder;
@property(retain, nonatomic) OfflineConfirmOrderViewController *offlineConfirmController; // @synthesize offlineConfirmController=_offlineConfirmController;
@property(retain, nonatomic) ConfirmOrderViewController *confirmController; // @synthesize confirmController=_confirmController;
@property(retain, nonatomic) NSString *userMoney; // @synthesize userMoney=_userMoney;
@property(retain, nonatomic) NSString *orderFee; // @synthesize orderFee=_orderFee;
@property(retain, nonatomic) NSDictionary *region; // @synthesize region=_region;
@property(retain, nonatomic) NSMutableDictionary *selectedPayment; // @synthesize selectedPayment=_selectedPayment;
@property(retain, nonatomic) UITableView *payOptionsTableView; // @synthesize payOptionsTableView=_payOptionsTableView;
- (void).cxx_destruct;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (id)createPaymentId:(int)arg1;
- (_Bool)shouldPerformSegueWithIdentifier:(id)arg1 sender:(id)arg2;
- (void)backToPrevious;
- (void)didSelectPayOptionInOfflineOrder;
- (void)recordPayOption:(id)arg1 payId:(id)arg2 payName:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)checkUserMoney:(id)arg1 payId:(id)arg2 payName:(id)arg3;
- (void)alertErrorMessage:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (id)filterPayOptions:(id)arg1;
- (void)loadOfflinePayOptions;
- (void)loadPayOptions;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

