//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "UIActionSheetDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UITextFieldDelegate.h"

@class NSDictionary, NSString, UIImagePickerController, UIImageView, UILabel, UITextField, UserRankData;

@interface PersonalDataTableViewController : UITableViewController <UITextFieldDelegate, UIActionSheetDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
{
    UserRankData *_userRankData;
    UIImageView *_userImage;
    UIImageView *_userLevelImage;
    UITextField *_userNameInput;
    UILabel *_userNameLabel;
    UILabel *_userSexLabel;
    UILabel *_userBirthdayLabel;
    UILabel *_userMobileStatusLabel;
    UILabel *_userCompanyStatusLabel;
    NSDictionary *_personalData;
    UIImagePickerController *_imagePickerController;
    NSString *_imageFullPath;
}

@property(retain, nonatomic) NSString *imageFullPath; // @synthesize imageFullPath=_imageFullPath;
@property(retain, nonatomic) UIImagePickerController *imagePickerController; // @synthesize imagePickerController=_imagePickerController;
@property(retain, nonatomic) NSDictionary *personalData; // @synthesize personalData=_personalData;
@property(nonatomic) __weak UILabel *userCompanyStatusLabel; // @synthesize userCompanyStatusLabel=_userCompanyStatusLabel;
@property(nonatomic) __weak UILabel *userMobileStatusLabel; // @synthesize userMobileStatusLabel=_userMobileStatusLabel;
@property(nonatomic) __weak UILabel *userBirthdayLabel; // @synthesize userBirthdayLabel=_userBirthdayLabel;
@property(nonatomic) __weak UILabel *userSexLabel; // @synthesize userSexLabel=_userSexLabel;
@property(nonatomic) __weak UILabel *userNameLabel; // @synthesize userNameLabel=_userNameLabel;
@property(nonatomic) __weak UITextField *userNameInput; // @synthesize userNameInput=_userNameInput;
@property(nonatomic) __weak UIImageView *userLevelImage; // @synthesize userLevelImage=_userLevelImage;
@property(nonatomic) __weak UIImageView *userImage; // @synthesize userImage=_userImage;
- (void).cxx_destruct;
- (void)setChangedStatus;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)selectUserBirthday;
- (void)selectUserSex;
- (void)editNickName;
- (void)deleteSinglePhoto;
- (void)reLoadImageView;
- (void)saveImage:(id)arg1 withData:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)useImage:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)setDefaultImage;
- (void)openImageSelector;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)goToBoundCompony;
- (void)goToBoundMobile;
- (void)userLogOff;
- (void)onUserLogOffPressed;
- (void)goToMyFav;
- (void)goToUserLevelCenter;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)saveUserInfo;
- (void)loadUserInfo:(_Bool)arg1;
- (void)updateBoundStatus;
- (void)updatePersonalData;
- (void)setFaceImage:(id)arg1;
- (void)alertErrorMessage:(id)arg1;
- (void)didReceiveMemoryWarning;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)hideKeyBoard;
- (void)viewTapped:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

