//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "MWPhotoBrowserDelegate.h"

@class NSDictionary, NSMutableArray, NSString;

@interface PhotoBrowserViewController : FDBaseViewController <MWPhotoBrowserDelegate>
{
    NSMutableArray *_photos;
    NSDictionary *_dataSource;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSDictionary *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) NSMutableArray *photos; // @synthesize photos=_photos;
- (void).cxx_destruct;
- (id)photoBrowser:(id)arg1 thumbPhotoAtIndex:(unsigned long long)arg2;
- (id)photoBrowser:(id)arg1 photoAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfPhotosInPhotoBrowser:(id)arg1;
- (void)showPhotoBrowserWithDataSource:(id)arg1 target:(id)arg2;
- (id)prepareDataSourceWithImageUrls:(id)arg1 imageAlt:(id)arg2 position:(long long)arg3;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

