//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface ProductListCell : UITableViewCell
{
    id <ProductListCellDelegate> _delegate;
    UIImageView *_pImageView;
    UIImageView *_pSignImageView;
    UIView *_pSelloutView;
    UILabel *_pNameLabel;
    UILabel *_pUnitLabel;
    UILabel *_pPriceLabel;
    UILabel *_pNumLabel;
    UILabel *_pOldPriceLabel;
    UIButton *_pReduceButton;
    UIButton *_pAddButton;
    UIButton *_pSelectButton;
}

@property(nonatomic) __weak UIButton *pSelectButton; // @synthesize pSelectButton=_pSelectButton;
@property(nonatomic) __weak UIButton *pAddButton; // @synthesize pAddButton=_pAddButton;
@property(nonatomic) __weak UIButton *pReduceButton; // @synthesize pReduceButton=_pReduceButton;
@property(nonatomic) __weak UILabel *pOldPriceLabel; // @synthesize pOldPriceLabel=_pOldPriceLabel;
@property(nonatomic) __weak UILabel *pNumLabel; // @synthesize pNumLabel=_pNumLabel;
@property(nonatomic) __weak UILabel *pPriceLabel; // @synthesize pPriceLabel=_pPriceLabel;
@property(nonatomic) __weak UILabel *pUnitLabel; // @synthesize pUnitLabel=_pUnitLabel;
@property(nonatomic) __weak UILabel *pNameLabel; // @synthesize pNameLabel=_pNameLabel;
@property(nonatomic) __weak UIView *pSelloutView; // @synthesize pSelloutView=_pSelloutView;
@property(nonatomic) __weak UIImageView *pSignImageView; // @synthesize pSignImageView=_pSignImageView;
@property(nonatomic) __weak UIImageView *pImageView; // @synthesize pImageView=_pImageView;
@property(nonatomic) id <ProductListCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)loadProductWithData:(id)arg1;
- (void)checkStockNum:(id)arg1 num:(id)arg2;
- (void)selectAction:(id)arg1;
- (void)addAction:(id)arg1;
- (void)reduceAction:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

