//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSString<Optional>;

@interface ProductDataModel : FDBaseDataModel
{
    NSString<Optional> *_id;
    NSString<Optional> *_order_id;
    NSString<Optional> *_product_id;
    NSString<Optional> *_product_no;
    NSString<Optional> *_product_name;
    NSString<Optional> *_gg_name;
    NSString<Optional> *_price;
    NSString<Optional> *_qty;
    NSString<Optional> *_score;
    NSString<Optional> *_type;
    NSString<Optional> *_total_money;
    NSString<Optional> *_order_name;
    NSString<Optional> *_photo;
    NSString<Optional> *_score_desc;
}

@property(copy, nonatomic) NSString<Optional> *score_desc; // @synthesize score_desc=_score_desc;
@property(copy, nonatomic) NSString<Optional> *photo; // @synthesize photo=_photo;
@property(copy, nonatomic) NSString<Optional> *order_name; // @synthesize order_name=_order_name;
@property(copy, nonatomic) NSString<Optional> *total_money; // @synthesize total_money=_total_money;
@property(copy, nonatomic) NSString<Optional> *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString<Optional> *score; // @synthesize score=_score;
@property(copy, nonatomic) NSString<Optional> *qty; // @synthesize qty=_qty;
@property(copy, nonatomic) NSString<Optional> *price; // @synthesize price=_price;
@property(copy, nonatomic) NSString<Optional> *gg_name; // @synthesize gg_name=_gg_name;
@property(copy, nonatomic) NSString<Optional> *product_name; // @synthesize product_name=_product_name;
@property(copy, nonatomic) NSString<Optional> *product_no; // @synthesize product_no=_product_no;
@property(copy, nonatomic) NSString<Optional> *product_id; // @synthesize product_id=_product_id;
@property(copy, nonatomic) NSString<Optional> *order_id; // @synthesize order_id=_order_id;
@property(copy, nonatomic) NSString<Optional> *id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

