//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CartItemCell, NSIndexPath, PromoProduct;

@protocol ProductItemCellDelegate <NSObject>

@optional
- (void)didSelectCartPromo:(PromoProduct *)arg1 atIndexPath:(NSIndexPath *)arg2;
- (void)qtyMinus:(CartItemCell *)arg1 toDelete:(_Bool)arg2;
- (void)qtyPlus:(CartItemCell *)arg1;
@end

