//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class QBAssetsCollectionCheckmarkView;

@interface QBAssetsCollectionOverlayView : UIView
{
    QBAssetsCollectionCheckmarkView *_checkmarkView;
}

@property(retain, nonatomic) QBAssetsCollectionCheckmarkView *checkmarkView; // @synthesize checkmarkView=_checkmarkView;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

