//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "AVCaptureMetadataOutputObjectsDelegate.h"
#import "UIAlertViewDelegate.h"

@class AVCaptureSession, AVCaptureVideoPreviewLayer, NSString, NSTimer, UIImageView, UILabel, UITextField, UIView, UIViewController;

@interface QRCodeReaderViewController : FDBaseViewController <AVCaptureMetadataOutputObjectsDelegate, UIAlertViewDelegate>
{
    UIImageView *resultImage;
    UIView *_moveLine;
    UIView *_hMoveLine;
    UIView *_qrIndicatorView;
    UIView *_brIndicatorView;
    NSString *_QRType;
    UITextField *_fromTextField;
    UIViewController *_fromController;
    UILabel *_indicatorLabel;
    AVCaptureSession *_session;
    AVCaptureVideoPreviewLayer *_previewLayer;
    NSTimer *_timer;
}

@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *previewLayer; // @synthesize previewLayer=_previewLayer;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session=_session;
@property(nonatomic) __weak UILabel *indicatorLabel; // @synthesize indicatorLabel=_indicatorLabel;
@property(retain, nonatomic) UIViewController *fromController; // @synthesize fromController=_fromController;
@property(retain, nonatomic) UITextField *fromTextField; // @synthesize fromTextField=_fromTextField;
@property(retain, nonatomic) NSString *QRType; // @synthesize QRType=_QRType;
@property(nonatomic) __weak UIView *brIndicatorView; // @synthesize brIndicatorView=_brIndicatorView;
@property(nonatomic) __weak UIView *qrIndicatorView; // @synthesize qrIndicatorView=_qrIndicatorView;
@property(nonatomic) __weak UIView *hMoveLine; // @synthesize hMoveLine=_hMoveLine;
@property(nonatomic) __weak UIView *moveLine; // @synthesize moveLine=_moveLine;
@property(retain, nonatomic) UIImageView *resultImage; // @synthesize resultImage;
- (void).cxx_destruct;
- (id)getDataFromJsonFile:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)loadTraceInfoByCode:(id)arg1;
- (void)goToInerProductDetail:(id)arg1;
- (_Bool)checkWhetherInerProduct:(id)arg1;
- (_Bool)isPureInt:(id)arg1;
- (void)captureOutput:(id)arg1 didOutputMetadataObjects:(id)arg2 fromConnection:(id)arg3;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)readQRCode;
- (void)moveLodingLine;
- (void)startLoadingLine;
- (void)showIndicaterLabelText:(int)arg1;
- (void)adjustViewByType;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

