//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSLayoutConstraint, UIImageView, UILabel;

@interface RechargeConfirmationGiftCell : UITableViewCell
{
    UIImageView *_giftImage;
    UILabel *_productsName;
    UILabel *_productsNum;
    UILabel *_moneyIcon;
    UILabel *_moneyNum;
    UILabel *_zeroIcon;
    NSLayoutConstraint *_productsNameHeightConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *productsNameHeightConstraint; // @synthesize productsNameHeightConstraint=_productsNameHeightConstraint;
@property(nonatomic) __weak UILabel *zeroIcon; // @synthesize zeroIcon=_zeroIcon;
@property(nonatomic) __weak UILabel *moneyNum; // @synthesize moneyNum=_moneyNum;
@property(nonatomic) __weak UILabel *moneyIcon; // @synthesize moneyIcon=_moneyIcon;
@property(nonatomic) __weak UILabel *productsNum; // @synthesize productsNum=_productsNum;
@property(nonatomic) __weak UILabel *productsName; // @synthesize productsName=_productsName;
@property(nonatomic) __weak UIImageView *giftImage; // @synthesize giftImage=_giftImage;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

