//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UIAlertViewDelegate.h"

@class NSDictionary, NSMutableArray, NSString, UIAlertView, UIButton, UILabel, UITableView, UIView;

@interface RechargeConfirmationViewController : FDBaseViewController <UIAlertViewDelegate>
{
    NSDictionary *_giftDic;
    UILabel *_topUpLabel;
    NSString *_moneyValue;
    UILabel *_moneyValueLabel;
    id <RechargeConfirmationDelegate> _rechargeConfirmationDelegate;
    NSMutableArray *_rechargeConfirmationPaymentArrayFirst;
    NSMutableArray *_rechargeConfirmationPaymentArray;
    UITableView *_rechargeConfirmationTableView;
    NSDictionary *_paramsDic;
    UIButton *_chargeBtn;
    UIView *_rechargeConfirmationTopUpView;
    UIAlertView *_commitChargeAlertView;
}

@property(retain, nonatomic) UIAlertView *commitChargeAlertView; // @synthesize commitChargeAlertView=_commitChargeAlertView;
@property(nonatomic) __weak UIView *rechargeConfirmationTopUpView; // @synthesize rechargeConfirmationTopUpView=_rechargeConfirmationTopUpView;
@property(nonatomic) __weak UIButton *chargeBtn; // @synthesize chargeBtn=_chargeBtn;
@property(retain, nonatomic) NSDictionary *paramsDic; // @synthesize paramsDic=_paramsDic;
@property(nonatomic) __weak UITableView *rechargeConfirmationTableView; // @synthesize rechargeConfirmationTableView=_rechargeConfirmationTableView;
@property(retain, nonatomic) NSMutableArray *rechargeConfirmationPaymentArray; // @synthesize rechargeConfirmationPaymentArray=_rechargeConfirmationPaymentArray;
@property(retain, nonatomic) NSMutableArray *rechargeConfirmationPaymentArrayFirst; // @synthesize rechargeConfirmationPaymentArrayFirst=_rechargeConfirmationPaymentArrayFirst;
@property(nonatomic) id <RechargeConfirmationDelegate> rechargeConfirmationDelegate; // @synthesize rechargeConfirmationDelegate=_rechargeConfirmationDelegate;
@property(nonatomic) __weak UILabel *moneyValueLabel; // @synthesize moneyValueLabel=_moneyValueLabel;
@property(retain, nonatomic) NSString *moneyValue; // @synthesize moneyValue=_moneyValue;
@property(nonatomic) __weak UILabel *topUpLabel; // @synthesize topUpLabel=_topUpLabel;
@property(retain, nonatomic) NSDictionary *giftDic; // @synthesize giftDic=_giftDic;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)commitChargeFuction;
- (void)commitCharge:(id)arg1;
- (void)PaidCompleted;
- (void)loadPaymentList;
- (void)choosePreviousViewWithPhysicalGifts:(id)arg1;
- (void)choosePreviousViewWithNonPhysicalGifts:(id)arg1;
- (void)backToPreviousView;
- (void)didReceiveMemoryWarning;
- (void)UIBtn;
- (void)UILabel;
- (void)UILay;
- (void)UICellSeparator;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

