//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIActivityIndicatorView, UIImageView, UILabel, UIView;

@interface RecommendTableViewCell : UITableViewCell
{
    UIView *_cellHeader;
    UIImageView *_itemPreview;
    UIView *_itemDescView;
    UIView *_itemTransparentView;
    UILabel *_itemName;
    UILabel *_itemSpec;
    UILabel *_itemPrice;
    UIView *_cellFooter;
    UIView *_cellLeft;
    UIView *_cellRight;
    UIActivityIndicatorView *_loadingIndicator;
}

@property(nonatomic) __weak UIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(nonatomic) __weak UIView *cellRight; // @synthesize cellRight=_cellRight;
@property(nonatomic) __weak UIView *cellLeft; // @synthesize cellLeft=_cellLeft;
@property(nonatomic) __weak UIView *cellFooter; // @synthesize cellFooter=_cellFooter;
@property(nonatomic) __weak UILabel *itemPrice; // @synthesize itemPrice=_itemPrice;
@property(nonatomic) __weak UILabel *itemSpec; // @synthesize itemSpec=_itemSpec;
@property(nonatomic) __weak UILabel *itemName; // @synthesize itemName=_itemName;
@property(nonatomic) __weak UIView *itemTransparentView; // @synthesize itemTransparentView=_itemTransparentView;
@property(nonatomic) __weak UIView *itemDescView; // @synthesize itemDescView=_itemDescView;
@property(nonatomic) __weak UIImageView *itemPreview; // @synthesize itemPreview=_itemPreview;
@property(nonatomic) __weak UIView *cellHeader; // @synthesize cellHeader=_cellHeader;
- (void).cxx_destruct;
- (void)performDownAnimation;
- (void)performUpAnimation;
- (void)performZoomAnimation;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

