//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface ResponsiveImageGroupView : UIView
{
    NSArray *_imageArray;
    id _target;
}

+ (double)getImageGroupHeightByDataSource:(id)arg1;
@property(retain, nonatomic) id target; // @synthesize target=_target;
@property(retain, nonatomic) NSArray *imageArray; // @synthesize imageArray=_imageArray;
- (void).cxx_destruct;
- (void)onImagePressed:(id)arg1;
- (id)initWithImages:(id)arg1 target:(id)arg2;

@end

