//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"

@class NSString;

@interface RMPZoomTransitionAnimator : NSObject <UIViewControllerAnimatedTransitioning>
{
    _Bool _goingForward;
    id <RMPZoomTransitionAnimating><RMPZoomTransitionDelegate> _sourceTransition;
    id <RMPZoomTransitionAnimating><RMPZoomTransitionDelegate> _destinationTransition;
}

@property(nonatomic) __weak id <RMPZoomTransitionAnimating><RMPZoomTransitionDelegate> destinationTransition; // @synthesize destinationTransition=_destinationTransition;
@property(nonatomic) __weak id <RMPZoomTransitionAnimating><RMPZoomTransitionDelegate> sourceTransition; // @synthesize sourceTransition=_sourceTransition;
@property(nonatomic) _Bool goingForward; // @synthesize goingForward=_goingForward;
- (void).cxx_destruct;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

