//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCNavTabBarDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSMutableArray, NSString, SCNavTabBar, UIColor, UIImage, UIScrollView;

@interface SCNavTabBarController : UIViewController <UIScrollViewDelegate, SCNavTabBarDelegate>
{
    SCNavTabBar *_navTabBar;
    NSMutableArray *_titles;
    UIScrollView *_mainView;
    long long _currentIndex;
    _Bool _showArrowButton;
    _Bool _scrollAnimation;
    _Bool _mainViewBounces;
    id <SCNavTabBarControllerDelegate> _delegate;
    NSArray *_subViewControllers;
    UIColor *_navTabBarColor;
    UIColor *_navTabBarLineColor;
    UIImage *_navTabBarArrowImage;
}

@property(retain, nonatomic) UIImage *navTabBarArrowImage; // @synthesize navTabBarArrowImage=_navTabBarArrowImage;
@property(retain, nonatomic) UIColor *navTabBarLineColor; // @synthesize navTabBarLineColor=_navTabBarLineColor;
@property(retain, nonatomic) UIColor *navTabBarColor; // @synthesize navTabBarColor=_navTabBarColor;
@property(retain, nonatomic) NSArray *subViewControllers; // @synthesize subViewControllers=_subViewControllers;
@property(nonatomic) _Bool mainViewBounces; // @synthesize mainViewBounces=_mainViewBounces;
@property(nonatomic) _Bool scrollAnimation; // @synthesize scrollAnimation=_scrollAnimation;
@property(nonatomic) _Bool showArrowButton; // @synthesize showArrowButton=_showArrowButton;
@property(nonatomic) id <SCNavTabBarControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)shouldPopNavgationItemMenu:(_Bool)arg1 height:(double)arg2;
- (void)itemDidSelectedWithIndex:(long long)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)viewScrollAtIndex:(long long)arg1;
- (void)addParentController:(id)arg1;
- (void)setNavTabbarColor:(id)arg1;
- (void)viewConfig;
- (void)viewInit;
- (void)initConfig;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithSubViewControllers:(id)arg1 andParentViewController:(id)arg2 showArrowButton:(_Bool)arg3;
- (id)initWithParentViewController:(id)arg1;
- (id)initWithSubViewControllers:(id)arg1;
- (id)initWithShowArrowButton:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

