//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SCPopViewDelegate.h"

@class NSArray, NSMutableArray, NSString, SCPopView, UIColor, UIImage, UIImageView, UIScrollView;

@interface SCNavTabBar : UIView <SCPopViewDelegate>
{
    UIScrollView *_navgationTabBar;
    UIImageView *_arrowButton;
    UIView *_line;
    SCPopView *_popView;
    NSMutableArray *_items;
    NSArray *_itemsWidth;
    _Bool _showArrowButton;
    _Bool _popItemMenu;
    id <SCNavTabBarDelegate> _delegate;
    long long _currentItemIndex;
    NSArray *_itemTitles;
    UIColor *_lineColor;
    UIImage *_arrowImage;
}

@property(retain, nonatomic) UIImage *arrowImage; // @synthesize arrowImage=_arrowImage;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(retain, nonatomic) NSArray *itemTitles; // @synthesize itemTitles=_itemTitles;
@property(nonatomic) long long currentItemIndex; // @synthesize currentItemIndex=_currentItemIndex;
@property(nonatomic) __weak id <SCNavTabBarDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)itemPressedWithIndex:(long long)arg1;
- (void)refresh;
- (void)updateData;
- (void)popItemMenu:(_Bool)arg1;
- (double)popMenuHeight;
- (void)viewShowShadow:(id)arg1 shadowRadius:(double)arg2 shadowOpacity:(double)arg3;
- (id)getButtonsWidthWithTitles:(id)arg1;
- (void)functionButtonPressed;
- (void)setButtonHighted:(long long)arg1;
- (void)viewScrollAtIndex:(long long)arg1;
- (void)itemPressed:(id)arg1;
- (void)addTapGestureRecognizer;
- (double)contentWidthAndAddNavTabBarItemsWithButtonsWidth:(id)arg1;
- (void)showLineWithButtonWidth:(double)arg1;
- (void)viewConfig;
- (void)initConfig;
- (id)initWithFrame:(struct CGRect)arg1 showArrowButton:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

