//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface SCPopView : UIView
{
    id <SCPopViewDelegate> _delegate;
    NSArray *_itemNames;
}

@property(retain, nonatomic) NSArray *itemNames; // @synthesize itemNames=_itemNames;
@property(nonatomic) __weak id <SCPopViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)itemPressed:(id)arg1;
- (void)updateSubViewsWithItemWidths:(id)arg1;
- (id)getButtonsWidthWithTitles:(id)arg1;

@end

