//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "DZNEmptyDataSetDelegate.h"
#import "DZNEmptyDataSetSource.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSDictionary, NSMutableArray, NSString, UIImageView, UITableView, UIViewController;

@interface SelectAddressViewController : FDBaseViewController <UIAlertViewDelegate, UITableViewDataSource, UITableViewDelegate, DZNEmptyDataSetSource, DZNEmptyDataSetDelegate>
{
    _Bool _selectionSucceed;
    _Bool _loadOrSelect;
    _Bool _editingEnabled;
    _Bool _autoSelect;
    UITableView *_selectAddressListTableView;
    NSMutableArray *_selectAddressList;
    NSDictionary *_selectedAddress;
    NSDictionary *_repostSelectedAddress;
    UIViewController *_fromViewController;
    NSString *_addressListType;
    NSString *_autoSelectedAddressId;
}

@property(retain, nonatomic) NSString *autoSelectedAddressId; // @synthesize autoSelectedAddressId=_autoSelectedAddressId;
@property(nonatomic) _Bool autoSelect; // @synthesize autoSelect=_autoSelect;
@property(retain, nonatomic) NSString *addressListType; // @synthesize addressListType=_addressListType;
@property(retain, nonatomic) UIViewController *fromViewController; // @synthesize fromViewController=_fromViewController;
@property(nonatomic) _Bool editingEnabled; // @synthesize editingEnabled=_editingEnabled;
@property _Bool loadOrSelect; // @synthesize loadOrSelect=_loadOrSelect;
@property(retain, nonatomic) NSDictionary *repostSelectedAddress; // @synthesize repostSelectedAddress=_repostSelectedAddress;
@property(nonatomic) _Bool selectionSucceed; // @synthesize selectionSucceed=_selectionSucceed;
@property(retain, nonatomic) NSDictionary *selectedAddress; // @synthesize selectedAddress=_selectedAddress;
@property(retain, nonatomic) NSMutableArray *selectAddressList; // @synthesize selectAddressList=_selectAddressList;
@property(retain, nonatomic) UITableView *selectAddressListTableView; // @synthesize selectAddressListTableView=_selectAddressListTableView;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)clearSelectedAddress;
- (void)recordAddressSelection:(id)arg1;
- (_Bool)shouldPerformSegueWithIdentifier:(id)arg1 sender:(id)arg2;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)emptyDataSetDidTapButton:(id)arg1;
- (double)verticalOffsetForEmptyDataSet:(id)arg1;
- (id)buttonTitleForEmptyDataSet:(id)arg1 forState:(unsigned long long)arg2;
- (id)descriptionForEmptyDataSet:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)onEditAddressPress:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)autoSelectAddress:(id)arg1;
- (void)onNewAddressPress:(id)arg1;
- (void)loadAddressList;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) UIImageView *loadingImageView;
@property(readonly) Class superclass;

@end

