//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "DZNEmptyDataSetDelegate.h"
#import "DZNEmptyDataSetSource.h"
#import "OrderActionDelegate.h"
#import "OrderCellDelegate.h"

@class FDOrderOverviewListData, NSMutableArray, NSString, UITableView;

@interface ServiceLogisticViewController : FDBaseViewController <OrderActionDelegate, DZNEmptyDataSetSource, DZNEmptyDataSetDelegate, OrderCellDelegate>
{
    FDOrderOverviewListData *_orderListData;
    _Bool _isPayNeed;
    UITableView *_myOrderTableView;
    NSMutableArray *_issueOrderList;
}

@property _Bool isPayNeed; // @synthesize isPayNeed=_isPayNeed;
@property(retain, nonatomic) NSMutableArray *issueOrderList; // @synthesize issueOrderList=_issueOrderList;
@property(nonatomic) __weak UITableView *myOrderTableView; // @synthesize myOrderTableView=_myOrderTableView;
- (void).cxx_destruct;
- (void)emptyDataSetDidTapButton:(id)arg1;
- (double)verticalOffsetForEmptyDataSet:(id)arg1;
- (id)buttonTitleForEmptyDataSet:(id)arg1 forState:(unsigned long long)arg2;
- (id)descriptionForEmptyDataSet:(id)arg1;
- (id)titleForEmptyDataSet:(id)arg1;
- (id)imageForEmptyDataSet:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)confirmOrderDone:(id)arg1 withCell:(id)arg2;
- (void)confirmOrderPressed:(id)arg1;
- (void)onServiceDetailPressed:(id)arg1;
- (void)onDialService:(id)arg1;
- (void)goToDetailAfterConfirm:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)loadOrdersList;
- (id)filterCanCheckLogistic:(id)arg1;
- (void)showItemList;
- (void)hideItemList;
- (void)alertErrorMessage:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

