//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UIWebViewDelegate.h"

@class NSString, UIWebView;

@interface ServiceIntroViewController : FDBaseViewController <UIWebViewDelegate>
{
    UIWebView *_introWebView;
}

@property(nonatomic) __weak UIWebView *introWebView; // @synthesize introWebView=_introWebView;
- (void).cxx_destruct;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)onContactServicePressed:(id)arg1;
- (void)loadPageUrl;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

