//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UserInfo;

@interface SessionData : NSObject
{
    UserInfo *_userInfo;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedData;
@property(retain, nonatomic) UserInfo *userInfo; // @synthesize userInfo=_userInfo;
- (void).cxx_destruct;
- (void)getUserInfoFromViewController:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)resetData;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

