//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

@class FDCurveImageView, NSDictionary, NSString, NSTimer, UIButton, UIImageView, UILabel, UIView;

@interface ShakeWithGiftViewController : FDBaseViewController
{
    NSString *_shareChannel;
    NSDictionary *_productInfo;
    NSDictionary *_cartItemToAdd;
    NSString *_appDescription;
    NSString *_exchangeRule;
    NSString *_appLink;
    NSString *_activityUrl;
    NSTimer *_defultTimer;
    NSTimer *_shakeTimer;
    int _leftChance;
    _Bool _canShake;
    UIImageView *_shakeBackground;
    UILabel *_leftChanceLabel;
    UIView *_resultBackground;
    UIView *_resultView;
    UIImageView *_resultImage;
    UILabel *_resultGiftLabel;
    UIView *_actionView;
    UIButton *_continueShakeButton;
    UIButton *_tomorrowGoOnButton;
    UIButton *_shareResultButton;
    UIButton *_goToActivityButton;
    UIImageView *_shakeAnimateView;
    UIView *_productView;
    FDCurveImageView *_productImageView;
    UILabel *_productPriceLabel;
    UILabel *_productOldPriceLabel;
    UILabel *_productDescLabel;
    UILabel *_productPackageLabel;
    UIButton *_add2CartButton;
}

@property(nonatomic) __weak UIButton *add2CartButton; // @synthesize add2CartButton=_add2CartButton;
@property(nonatomic) __weak UILabel *productPackageLabel; // @synthesize productPackageLabel=_productPackageLabel;
@property(nonatomic) __weak UILabel *productDescLabel; // @synthesize productDescLabel=_productDescLabel;
@property(nonatomic) __weak UILabel *productOldPriceLabel; // @synthesize productOldPriceLabel=_productOldPriceLabel;
@property(nonatomic) __weak UILabel *productPriceLabel; // @synthesize productPriceLabel=_productPriceLabel;
@property(nonatomic) __weak FDCurveImageView *productImageView; // @synthesize productImageView=_productImageView;
@property(nonatomic) __weak UIView *productView; // @synthesize productView=_productView;
@property(nonatomic) __weak UIImageView *shakeAnimateView; // @synthesize shakeAnimateView=_shakeAnimateView;
@property(nonatomic) __weak UIButton *goToActivityButton; // @synthesize goToActivityButton=_goToActivityButton;
@property(nonatomic) __weak UIButton *shareResultButton; // @synthesize shareResultButton=_shareResultButton;
@property(nonatomic) __weak UIButton *tomorrowGoOnButton; // @synthesize tomorrowGoOnButton=_tomorrowGoOnButton;
@property(nonatomic) __weak UIButton *continueShakeButton; // @synthesize continueShakeButton=_continueShakeButton;
@property(nonatomic) __weak UIView *actionView; // @synthesize actionView=_actionView;
@property(nonatomic) __weak UILabel *resultGiftLabel; // @synthesize resultGiftLabel=_resultGiftLabel;
@property(nonatomic) __weak UIImageView *resultImage; // @synthesize resultImage=_resultImage;
@property(nonatomic) __weak UIView *resultView; // @synthesize resultView=_resultView;
@property(nonatomic) __weak UIView *resultBackground; // @synthesize resultBackground=_resultBackground;
@property(nonatomic) __weak UILabel *leftChanceLabel; // @synthesize leftChanceLabel=_leftChanceLabel;
@property(nonatomic) __weak UIImageView *shakeBackground; // @synthesize shakeBackground=_shakeBackground;
- (void).cxx_destruct;
- (void)backToPrevious;
- (void)doExchangeShakeChance;
- (void)onShakeExchangePressed:(id)arg1;
- (void)onCheckGiftHistoryPressed:(id)arg1;
- (void)onCheckRulePressed:(id)arg1;
- (void)onBackToPrevious:(id)arg1;
- (void)goToActivityPressed:(id)arg1;
- (void)shareShakeResult:(id)arg1;
- (void)tomorrowGoOnShake:(id)arg1;
- (void)continueToShake:(id)arg1;
- (void)onAdd2CartPressed:(id)arg1;
- (void)onProductViewPressed:(id)arg1;
- (void)shareAppInfo;
- (void)motionCancelled:(long long)arg1 withEvent:(id)arg2;
- (void)motionEnded:(long long)arg1 withEvent:(id)arg2;
- (void)motionBegan:(long long)arg1 withEvent:(id)arg2;
- (_Bool)canBecomeFirstResponder;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertErrorMessage:(id)arg1;
- (void)showHideBusyIndicator:(_Bool)arg1;
- (void)showResultView:(_Bool)arg1;
- (void)updateShakeResult:(id)arg1;
- (void)updateTodayShakeTimes:(id)arg1;
- (void)shakeGirt:(id)arg1 withLoadingNeed:(_Bool)arg2;
- (void)animationSetting:(float)arg1 withDuration:(float)arg2;
- (void)shakeAnimation;
- (void)startDefaultAnimation;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

