//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UMSocialUIDelegate.h"

@class NSString, UIImage, UIViewController;

@interface ShareCenter : NSObject <UMSocialUIDelegate>
{
    _Bool _forbiddenCallBack;
    int _shareFromView;
    NSString *_shareTitle;
    NSString *_shareText;
    NSString *_photoUrl;
    UIImage *_photoImage;
    NSString *_shareUrl;
    NSString *_extraInfo;
    UIViewController *_sourceController;
    id _errorCallback;
    id _successCallback;
}

+ (id)sharedInstance;
@property int shareFromView; // @synthesize shareFromView=_shareFromView;
@property _Bool forbiddenCallBack; // @synthesize forbiddenCallBack=_forbiddenCallBack;
@property(retain, nonatomic) id successCallback; // @synthesize successCallback=_successCallback;
@property(retain, nonatomic) id errorCallback; // @synthesize errorCallback=_errorCallback;
@property(retain, nonatomic) UIViewController *sourceController; // @synthesize sourceController=_sourceController;
@property(retain, nonatomic) NSString *extraInfo; // @synthesize extraInfo=_extraInfo;
@property(retain, nonatomic) NSString *shareUrl; // @synthesize shareUrl=_shareUrl;
@property(retain, nonatomic) UIImage *photoImage; // @synthesize photoImage=_photoImage;
@property(retain, nonatomic) NSString *photoUrl; // @synthesize photoUrl=_photoUrl;
@property(retain, nonatomic) NSString *shareText; // @synthesize shareText=_shareText;
@property(retain, nonatomic) NSString *shareTitle; // @synthesize shareTitle=_shareTitle;
- (void).cxx_destruct;
- (void)sharedSuccessWithGift:(id)arg1 type:(id)arg2 extra:(id)arg3;
- (void)shareAndSendDiscountCode:(int)arg1;
- (void)aaShareBubblesDidHide:(id)arg1;
- (void)aaShareBubbles:(id)arg1 tappedBubbleWithType:(int)arg2;
- (void)showShareBubbles:(id)arg1 type:(id)arg2;
- (void)doShareWithType:(id)arg1 withTitle:(id)arg2 withText:(id)arg3 withImage:(id)arg4 withImageUrl:(id)arg5 fromView:(int)arg6 withExtraData:(id)arg7 fromController:(id)arg8 withType:(id)arg9 errorCallback:(CDUnknownBlockType)arg10 successCallback:(CDUnknownBlockType)arg11;
- (void)doShare:(id)arg1 withTitle:(id)arg2 withText:(id)arg3 withImage:(id)arg4 withImageUrl:(id)arg5 fromView:(int)arg6 withExtraData:(id)arg7 fromController:(id)arg8 errorCallback:(CDUnknownBlockType)arg9 successCallback:(CDUnknownBlockType)arg10;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

