//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSDictionary<Optional><ConvertOnDemand>, NSString<Optional>;

@interface SheQuListDetailsDataModel : FDBaseDataModel
{
    NSString<Optional> *_ptype;
    NSDictionary<Optional><ConvertOnDemand> *_data;
}

@property(retain, nonatomic) NSDictionary<Optional><ConvertOnDemand> *data; // @synthesize data=_data;
@property(copy, nonatomic) NSString<Optional> *ptype; // @synthesize ptype=_ptype;
- (void).cxx_destruct;

@end

