//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSArray<Optional><SheQuListDetailsDataModel>;

@interface SheQuListDataModel : FDBaseDataModel
{
    NSArray<Optional><SheQuListDetailsDataModel> *_top;
    NSArray<Optional><SheQuListDetailsDataModel> *_main;
}

@property(retain, nonatomic) NSArray<Optional><SheQuListDetailsDataModel> *main; // @synthesize main=_main;
@property(retain, nonatomic) NSArray<Optional><SheQuListDetailsDataModel> *top; // @synthesize top=_top;
- (void).cxx_destruct;

@end

