//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class ImageSelectView;

@interface ShowOrderCollectionViewCell : UICollectionViewCell
{
    ImageSelectView *_imageSelectView;
    CDUnknownBlockType _addImageAction;
    CDUnknownBlockType _removeImageAction;
}

@property(copy, nonatomic) CDUnknownBlockType removeImageAction; // @synthesize removeImageAction=_removeImageAction;
@property(copy, nonatomic) CDUnknownBlockType addImageAction; // @synthesize addImageAction=_addImageAction;
- (void).cxx_destruct;
- (void)displayCellByDataSources:(id)arg1 rowAtIndexPath:(id)arg2;
- (void)awakeFromNib;

@end

