//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseTableViewCell.h"

#import "StarRatingDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UITextViewDelegate.h"

@class FDCurveImageView, NSLayoutConstraint, NSMutableArray, NSString, StarRatingControl, UICollectionView, UIImageView, UILabel, UITextView, UIView;

@interface ShowOrderCell : FDBaseTableViewCell <UITextViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, StarRatingDelegate>
{
    FDCurveImageView *_productImageView;
    UILabel *_productTitleL;
    UILabel *_productStandardL;
    UILabel *_productPriceL;
    StarRatingControl *_starRatingControl;
    UITextView *_productCommentTV;
    UILabel *_defaultCommentL;
    UICollectionView *_productImagesCollectionView;
    UIView *_garySplitView;
    UIImageView *_bottomLine;
    NSLayoutConstraint *defaultCommonLHeightLayoutConstraint;
    NSLayoutConstraint *_titleHeightLayoutConstraint;
    NSMutableArray *_productImages;
    NSString *_productCommont;
    long long _productStarNumber;
    CDUnknownBlockType _addImageAction;
    CDUnknownBlockType _removeImageAction;
    CDUnknownBlockType _updateStarRating;
    CDUnknownBlockType _updateCommonContent;
    CDUnknownBlockType _pushCommontAction;
    CDUnknownBlockType _beginEditingAction;
}

+ (id)cellForTableView:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType beginEditingAction; // @synthesize beginEditingAction=_beginEditingAction;
@property(copy, nonatomic) CDUnknownBlockType pushCommontAction; // @synthesize pushCommontAction=_pushCommontAction;
@property(copy, nonatomic) CDUnknownBlockType updateCommonContent; // @synthesize updateCommonContent=_updateCommonContent;
@property(copy, nonatomic) CDUnknownBlockType updateStarRating; // @synthesize updateStarRating=_updateStarRating;
@property(copy, nonatomic) CDUnknownBlockType removeImageAction; // @synthesize removeImageAction=_removeImageAction;
@property(copy, nonatomic) CDUnknownBlockType addImageAction; // @synthesize addImageAction=_addImageAction;
@property(nonatomic) long long productStarNumber; // @synthesize productStarNumber=_productStarNumber;
@property(retain, nonatomic) NSString *productCommont; // @synthesize productCommont=_productCommont;
@property(retain, nonatomic) NSMutableArray *productImages; // @synthesize productImages=_productImages;
- (void).cxx_destruct;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)starRatingControl:(id)arg1 didUpdateRating:(unsigned long long)arg2;
- (void)reloadProductImages;
- (void)setBottomLineHide:(_Bool)arg1;
- (void)pushCommontAction:(id)arg1;
- (void)displayCellByDataSources:(id)arg1 rowAtIndexPath:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)dealloc;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

