//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface SpecSelectionView : UIView
{
    id <SpecSelectionViewDelegate> _delegate;
    NSArray *_data;
}

+ (double)heightForViewWithData:(id)arg1;
@property(retain, nonatomic) NSArray *data; // @synthesize data=_data;
@property(retain, nonatomic) id <SpecSelectionViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onButtonPressed:(id)arg1;
- (void)resetButtonStyle;
- (void)alignRight;
- (id)initWithData:(id)arg1 delegate:(id)arg2 leading:(double)arg3 top:(double)arg4 trailing:(double)arg5;

@end

