//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class FDCurveImageView, UIButton, UIImageView, UILabel;

@interface SpecialItemTableViewCell : UITableViewCell
{
    FDCurveImageView *_specialItemPreviewImage;
    UILabel *_specialItemName;
    UILabel *_specialItemSpec;
    UILabel *_specialItemPrice;
    UILabel *_specialItemOldPrice;
    UIButton *_addToCartButton;
    UIImageView *_checkBoxImageView;
    UIButton *_checkBoxButton;
}

@property(nonatomic) __weak UIButton *checkBoxButton; // @synthesize checkBoxButton=_checkBoxButton;
@property(nonatomic) __weak UIImageView *checkBoxImageView; // @synthesize checkBoxImageView=_checkBoxImageView;
@property(nonatomic) __weak UIButton *addToCartButton; // @synthesize addToCartButton=_addToCartButton;
@property(nonatomic) __weak UILabel *specialItemOldPrice; // @synthesize specialItemOldPrice=_specialItemOldPrice;
@property(nonatomic) __weak UILabel *specialItemPrice; // @synthesize specialItemPrice=_specialItemPrice;
@property(nonatomic) __weak UILabel *specialItemSpec; // @synthesize specialItemSpec=_specialItemSpec;
@property(nonatomic) __weak UILabel *specialItemName; // @synthesize specialItemName=_specialItemName;
@property(nonatomic) __weak FDCurveImageView *specialItemPreviewImage; // @synthesize specialItemPreviewImage=_specialItemPreviewImage;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

