//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSArray, NSObject<StarRatingDelegate>, UIImage;

@interface StarRatingControl : UIControl
{
    int _numberOfStars;
    int _currentIdx;
    UIImage *_star;
    UIImage *_highlightedStar;
    NSObject<StarRatingDelegate> *delegate;
    NSArray *_stars;
}

@property(retain) NSArray *stars; // @synthesize stars=_stars;
@property int currentIdx; // @synthesize currentIdx=_currentIdx;
@property int numberOfStars; // @synthesize numberOfStars=_numberOfStars;
@property __weak NSObject<StarRatingDelegate> *delegate; // @synthesize delegate;
@property(retain) UIImage *highlightedStar; // @synthesize highlightedStar=_highlightedStar;
@property(retain) UIImage *star; // @synthesize star=_star;
- (void).cxx_destruct;
@property unsigned long long rating;
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (_Bool)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)cancelTrackingWithEvent:(id)arg1;
- (_Bool)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (unsigned long long)indexForStarAtPoint:(struct CGPoint)arg1;
- (id)starForPoint:(struct CGPoint)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 andStars:(unsigned long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setupView;

@end

