//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface StaticWaveView : UIView
{
    struct CGRect _mRect;
    float _depth;
    float _waveHeight;
    UIColor *_currentWaterColor;
}

@property(nonatomic) float waveHeight; // @synthesize waveHeight=_waveHeight;
@property(nonatomic) float depth; // @synthesize depth=_depth;
@property(retain, nonatomic) UIColor *currentWaterColor; // @synthesize currentWaterColor=_currentWaterColor;
- (void).cxx_destruct;
- (void)drawWaveStaticViewWithWaveColor:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

