//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UINavigationControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UITableView, UIView;

@interface TasteReportViewController : FDBaseViewController <UINavigationControllerDelegate, UITableViewDataSource, UITableViewDelegate>
{
    int _currentPage;
    UIView *_orderNoDataView;
    UIView *_orderStatisticView;
    UITableView *_orderTableView;
    NSString *_tasteId;
    NSMutableArray *_comments;
}

@property int currentPage; // @synthesize currentPage=_currentPage;
@property(retain, nonatomic) NSMutableArray *comments; // @synthesize comments=_comments;
@property(retain, nonatomic) NSString *tasteId; // @synthesize tasteId=_tasteId;
@property(nonatomic) __weak UITableView *orderTableView; // @synthesize orderTableView=_orderTableView;
@property(nonatomic) __weak UIView *orderStatisticView; // @synthesize orderStatisticView=_orderStatisticView;
@property(nonatomic) __weak UIView *orderNoDataView; // @synthesize orderNoDataView=_orderNoDataView;
- (void).cxx_destruct;
- (void)openFullScreenImage:(long long)arg1 imageOrder:(long long)arg2;
- (void)onImageTap:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onBackPressed:(id)arg1;
- (void)loadCommentView;
- (void)showHideBusyIndicator:(_Bool)arg1;
- (void)alertErrorMessage:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)initOrderView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

