//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class CountDownView, NSLayoutConstraint, UIButton, UIImageView, UILabel, UIView;

@interface TodayFlashSaleCell : UITableViewCell
{
    CountDownView *_countDownView;
    CDUnknownBlockType _addCartAction;
    UIView *_countDownContainerView;
    UIView *_countDownBgView;
    UILabel *_countDownStockNumLabel;
    UIImageView *_todayFlashImageVIew;
    UILabel *_todayFlashNameLabel;
    UILabel *_todayFlashPriceLabel;
    UILabel *_todayFlashOldPriceLabel;
    UILabel *_todayFlashUnitLabel;
    UIButton *_todayFlashAddCartButton;
    NSLayoutConstraint *_countDownStockWidthConstraint;
    UIView *_saleOutBgView;
}

@property(nonatomic) __weak UIView *saleOutBgView; // @synthesize saleOutBgView=_saleOutBgView;
@property(nonatomic) __weak NSLayoutConstraint *countDownStockWidthConstraint; // @synthesize countDownStockWidthConstraint=_countDownStockWidthConstraint;
@property(nonatomic) __weak UIButton *todayFlashAddCartButton; // @synthesize todayFlashAddCartButton=_todayFlashAddCartButton;
@property(nonatomic) __weak UILabel *todayFlashUnitLabel; // @synthesize todayFlashUnitLabel=_todayFlashUnitLabel;
@property(nonatomic) __weak UILabel *todayFlashOldPriceLabel; // @synthesize todayFlashOldPriceLabel=_todayFlashOldPriceLabel;
@property(nonatomic) __weak UILabel *todayFlashPriceLabel; // @synthesize todayFlashPriceLabel=_todayFlashPriceLabel;
@property(nonatomic) __weak UILabel *todayFlashNameLabel; // @synthesize todayFlashNameLabel=_todayFlashNameLabel;
@property(nonatomic) __weak UIImageView *todayFlashImageVIew; // @synthesize todayFlashImageVIew=_todayFlashImageVIew;
@property(nonatomic) __weak UILabel *countDownStockNumLabel; // @synthesize countDownStockNumLabel=_countDownStockNumLabel;
@property(nonatomic) __weak UIView *countDownBgView; // @synthesize countDownBgView=_countDownBgView;
@property(nonatomic) __weak UIView *countDownContainerView; // @synthesize countDownContainerView=_countDownContainerView;
@property(copy, nonatomic) CDUnknownBlockType addCartAction; // @synthesize addCartAction=_addCartAction;
@property(retain, nonatomic) CountDownView *countDownView; // @synthesize countDownView=_countDownView;
- (void).cxx_destruct;
- (void)todayFlashAddCartAction:(id)arg1;
- (void)loadTodayFlashSaleData:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

