//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class CountDownView, UILabel, UIView;

@interface TodayFlashSaleHeaderCell : UITableViewCell
{
    CountDownView *_countDownView;
    UILabel *_headerTitleLabel;
    UIView *_headerColorBgView;
}

@property(nonatomic) __weak UIView *headerColorBgView; // @synthesize headerColorBgView=_headerColorBgView;
@property(nonatomic) __weak UILabel *headerTitleLabel; // @synthesize headerTitleLabel=_headerTitleLabel;
@property(retain, nonatomic) CountDownView *countDownView; // @synthesize countDownView=_countDownView;
- (void).cxx_destruct;
- (void)loadFuturnFlshSaleHeaderCell:(id)arg1;
- (void)loadTodayFlshSaleHeaderCell:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

