//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseDataModel.h"

@class NSString<Optional>;

@interface TopicListDataModel : FDBaseDataModel
{
    NSString<Optional> *_id;
    NSString<Optional> *_title;
    NSString<Optional> *_itopic_stated;
}

@property(copy, nonatomic) NSString<Optional> *itopic_stated; // @synthesize itopic_stated=_itopic_stated;
@property(copy, nonatomic) NSString<Optional> *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString<Optional> *id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

