//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "EAIntroDelegate.h"

@class NSString, TraceInfo, UIButton;

@interface TraceInfoViewController : FDBaseViewController <EAIntroDelegate>
{
    TraceInfo *_info;
    UIButton *_backButton;
}

@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) TraceInfo *info; // @synthesize info=_info;
- (void).cxx_destruct;
- (void)introDidFinish:(id)arg1;
- (void)intro:(id)arg1 pageAppeared:(id)arg2 withIndex:(unsigned long long)arg3;
- (void)initIntroPage;
- (void)backAction:(id)arg1;
- (void)initBackButton;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

