//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface TraceTipsView : UIView
{
    UIImageView *_bgImageView;
    UILabel *_titleLabel;
    UILabel *_productNameLabel;
    UIImageView *_productImageView;
    UILabel *_growPeriodLabel;
    UILabel *_temperatureLabel;
    UILabel *_humidityLabel;
    UILabel *_shelfLifeLabel;
}

@property(nonatomic) __weak UILabel *shelfLifeLabel; // @synthesize shelfLifeLabel=_shelfLifeLabel;
@property(nonatomic) __weak UILabel *humidityLabel; // @synthesize humidityLabel=_humidityLabel;
@property(nonatomic) __weak UILabel *temperatureLabel; // @synthesize temperatureLabel=_temperatureLabel;
@property(nonatomic) __weak UILabel *growPeriodLabel; // @synthesize growPeriodLabel=_growPeriodLabel;
@property(nonatomic) __weak UIImageView *productImageView; // @synthesize productImageView=_productImageView;
@property(nonatomic) __weak UILabel *productNameLabel; // @synthesize productNameLabel=_productNameLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
- (void).cxx_destruct;
- (void)displayWithData:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

