//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, UIImageView, UILabel;

@interface TraceCountryView : UIView
{
    UIImageView *_bgImageView;
    UIImageView *_planeImageView;
    UILabel *_sourceLabel;
    NSLayoutConstraint *_sourceLabelLeading;
    NSLayoutConstraint *_planeImageLeading;
}

@property(nonatomic) __weak NSLayoutConstraint *planeImageLeading; // @synthesize planeImageLeading=_planeImageLeading;
@property(nonatomic) __weak NSLayoutConstraint *sourceLabelLeading; // @synthesize sourceLabelLeading=_sourceLabelLeading;
@property(nonatomic) __weak UILabel *sourceLabel; // @synthesize sourceLabel=_sourceLabel;
@property(nonatomic) __weak UIImageView *planeImageView; // @synthesize planeImageView=_planeImageView;
@property(nonatomic) __weak UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
- (void).cxx_destruct;
- (void)displayWithData:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

