//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (Hardware)
+ (long long)totalDiskSpaceBytes;
+ (long long)freeDiskSpaceBytes;
+ (unsigned long long)freeMemoryBytes;
+ (unsigned long long)totalMemoryBytes;
+ (unsigned long long)cpuNumber;
+ (unsigned long long)ramSize;
+ (unsigned long long)busFrequency;
+ (unsigned long long)cpuFrequency;
+ (unsigned long long)getSysInfo:(unsigned int)arg1;
+ (_Bool)hasCamera;
+ (id)systemVersion;
+ (id)macAddress;
- (_Bool)isIphoneWith4inchDisplay;
- (struct CGSize)backCameraStillImageResolutionInPixels;
- (_Bool)isCurrentDeviceHardwareBetterThan:(int)arg1;
- (float)hardwareNumber:(int)arg1;
- (id)hardwareSimpleDescription;
- (id)hardwareDescription;
- (int)hardware;
- (id)hardwareString;
@end

