//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBar.h"

@interface UITabBar (RedIndicator)
+ (void)removeRedIndicatorFromBackend:(id)arg1;
- (void)removeRedIndicator:(int)arg1;
- (_Bool)checkBadgeOnItemIndexExist:(int)arg1;
- (void)removeBadgeOnItemIndex:(int)arg1;
- (void)hideBadgeOnItemIndex:(int)arg1;
- (void)showBadgeOnItemIndex:(int)arg1;
@end

