//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (Frame)
@property(nonatomic) double middleY;
@property(nonatomic) double middleX;
@property(nonatomic) double tail;
@property(nonatomic) double bottom;
@property(nonatomic) struct CGSize size;
@property(nonatomic) double height;
@property(nonatomic) double width;
@property(nonatomic) struct CGPoint origin;
@property(nonatomic) double y;
@property(nonatomic) double x;
@end

