//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (Animation)
- (void)startPropertyAnimationFromValue:(float)arg1 toValue:(float)arg2 duration:(float)arg3;
- (void)scaleView:(id)arg1 scaleValue:(double)arg2 durationTime:(double)arg3;
- (void)raisePriceLabelFromView:(id)arg1 WithString:(id)arg2;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)startCurveAnimationFromView:(id)arg1 toView:(id)arg2 withString:(id)arg3 completed:(CDUnknownBlockType)arg4;
@end

