//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (NJKFullScreenSupport)
- (double)bottomBarViewControlleViewHeightFromViewSize:(struct CGSize)arg1;
- (void)setTabBarOriginY:(double)arg1 animated:(_Bool)arg2;
- (void)moveTabBar:(double)arg1 animated:(_Bool)arg2;
- (void)hideTabBar:(_Bool)arg1;
- (void)showTabBar:(_Bool)arg1;
- (void)setToolbarOriginY:(double)arg1 animated:(_Bool)arg2;
- (void)moveToolbar:(double)arg1 animated:(_Bool)arg2;
- (void)hideToolbar:(_Bool)arg1;
- (void)showToolbar:(_Bool)arg1;
- (double)statusBarHeight;
- (void)setNavigationBarOriginY:(double)arg1 animated:(_Bool)arg2;
- (void)moveNavigationBar:(double)arg1 animated:(_Bool)arg2;
- (void)hideNavigationBar:(_Bool)arg1;
- (void)showNavigationBar:(_Bool)arg1;
@end

