//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIActivityIndicatorView, UILabel;

@interface UMMaskView : UIView
{
    UILabel *_statusLabel;
    UIActivityIndicatorView *_activityIndicatorView;
    _Bool _isActivity;
    NSString *_statusText;
}

@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(nonatomic) _Bool isActivity; // @synthesize isActivity=_isActivity;
@property(copy, nonatomic) NSString *statusText; // @synthesize statusText=_statusText;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithRoundedView;
- (void)dealloc;

@end

