//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UMProtocolData : NSObject
{
}

+ (id)md5Value:(id)arg1;
+ (id)accessString;
+ (_Bool)isPad;
+ (id)orientationString;
+ (id)cpuString;
+ (id)osVersionString;
+ (id)osString;
+ (id)deviceModelString;
+ (id)UUIDMD5String;
+ (id)UUIDString;
+ (id)openUDIDString;
+ (id)deviceMacString;
+ (id)deviceIDVendorString;
+ (id)lngString;
+ (id)latString;
+ (id)timeMSString;
+ (id)timeString;
+ (id)dateString;

@end

