//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface UMSocialUrlResource : NSObject
{
    int _resourceType;
    NSString *_url;
}

@property(nonatomic) int resourceType; // @synthesize resourceType=_resourceType;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
- (void)setResourceType:(int)arg1 url:(id)arg2;
- (id)initWithSnsResourceType:(int)arg1 url:(id)arg2;
- (void)dealloc;

@end

