//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UINavigationController, UMSocialControllerService, UMSocialData, UMSocialResponseEntity;

@protocol UMSocialUIDelegate <NSObject>

@optional
- (_Bool)isDirectShareInIconActionSheet;
- (void)didSelectSocialPlatform:(NSString *)arg1 withSocialData:(UMSocialData *)arg2;
- (void)didFinishGetUMSocialDataInViewController:(UMSocialResponseEntity *)arg1;
- (void)didCloseUIViewController:(int)arg1;
- (_Bool)closeOauthWebViewController:(UINavigationController *)arg1 socialControllerService:(UMSocialControllerService *)arg2;
@end

