//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UMSocialUIHelper : NSObject
{
    _Bool _isSetTranslucent;
    _Bool _isTranslucent;
}

+ (void)customNavBar:(id)arg1;
+ (void)setTranslucent:(id)arg1;
+ (void)customNavButton:(id)arg1 WithTitle:(id)arg2;
+ (void)customNavRefreshButton:(id)arg1;
+ (void)customNavPostButton:(id)arg1;
+ (void)customNavBackButton:(id)arg1 WithTitle:(id)arg2;
+ (void)customNavigationItem:(id)arg1;
+ (void)setNavigationBarTranslucent:(id)arg1;
+ (id)shareInstance;
@property(nonatomic) _Bool isTranslucent; // @synthesize isTranslucent=_isTranslucent;
@property(nonatomic) _Bool isSetTranslucent; // @synthesize isSetTranslucent=_isSetTranslucent;

@end

