//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UMSocialSnsData.h"

@class NSString;

@interface UMSocialTencentData : UMSocialSnsData
{
    NSString *_title;
    NSString *_author;
}

@property(copy, nonatomic) NSString *author; // @synthesize author=_author;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (id)init;

@end

