//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSError, NSString;

@interface UMSocialResponseEntity : NSObject
{
    int _responseCode;
    int _responseType;
    int _viewControllerType;
    NSString *_message;
    NSDictionary *_data;
    NSError *_error;
}

@property(nonatomic) int viewControllerType; // @synthesize viewControllerType=_viewControllerType;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) int responseType; // @synthesize responseType=_responseType;
@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(nonatomic) int responseCode; // @synthesize responseCode=_responseCode;
- (id)description;
- (void)dealloc;

@end

