//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface UMSViewControllerFactory : NSObject
{
    NSMutableArray *_viewControllerStack;
    id _mailDelegate;
}

+ (id)sharedInstance;
@property(nonatomic) id mailDelegate; // @synthesize mailDelegate=_mailDelegate;
@property(retain, nonatomic) NSMutableArray *viewControllerStack; // @synthesize viewControllerStack=_viewControllerStack;
- (void)dealloc;
- (id)createSocialViewController:(int)arg1 withSnsType:(int)arg2 withControllerService:(id)arg3;
- (id)init;

@end

