//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSMutableString, UILabel;

@interface UserInfoTableViewCell : UITableViewCell
{
    UILabel *_rulesLabel;
    NSMutableString *_str;
}

@property(retain, nonatomic) NSMutableString *str; // @synthesize str=_str;
@property(nonatomic) __weak UILabel *rulesLabel; // @synthesize rulesLabel=_rulesLabel;
- (void).cxx_destruct;
- (void)setTipsLabel:(id)arg1;

@end

