//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewController.h"

#import "UIScrollViewDelegate.h"

@class FDViewController, NSMutableArray, NSString, UIButton, UIPageControl, UIScrollView;

@interface UserGuideViewController : FDBaseViewController <UIScrollViewDelegate>
{
    NSMutableArray *userGuideImages;
    UIScrollView *_userGuideScrollView;
    UIPageControl *_userGuidePageControl;
    UIButton *_startButton;
    FDViewController *_fdVC;
}

@property(retain, nonatomic) FDViewController *fdVC; // @synthesize fdVC=_fdVC;
@property(nonatomic) __weak UIButton *startButton; // @synthesize startButton=_startButton;
@property(nonatomic) __weak UIPageControl *userGuidePageControl; // @synthesize userGuidePageControl=_userGuidePageControl;
@property(nonatomic) __weak UIScrollView *userGuideScrollView; // @synthesize userGuideScrollView=_userGuideScrollView;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)onStartPress:(id)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

