//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseViewModel.h"

@class NSArray, NSString;

@interface WritePostViewModel : FDBaseViewModel
{
    NSString *_successMessage;
    NSArray *_topicList;
}

@property(retain, nonatomic) NSArray *topicList; // @synthesize topicList=_topicList;
@property(copy, nonatomic) NSString *successMessage; // @synthesize successMessage=_successMessage;
- (void).cxx_destruct;
- (void)publishArticle:(id)arg1 description:(id)arg2 photos:(id)arg3 tid:(id)arg4;
- (void)getTopicListQuery;

@end

