//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextFieldDelegate.h"

@class NSLayoutConstraint, NSString, UIButton, UITextField;

@interface XTTextField : UIView <UITextFieldDelegate>
{
    NSLayoutConstraint *_keyboardHeightConstraint;
    id <XTTextFieldDelegate> _delegate;
    UITextField *_inputTextField;
    UIButton *_finishEditButton;
}

@property(nonatomic) __weak UIButton *finishEditButton; // @synthesize finishEditButton=_finishEditButton;
@property(nonatomic) __weak UITextField *inputTextField; // @synthesize inputTextField=_inputTextField;
@property(nonatomic) id <XTTextFieldDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)keyboardWillHidden:(id)arg1;
- (void)keyboardWillShown:(id)arg1;
- (void)setBgViewShow:(_Bool)arg1 andHeight:(float)arg2;
- (void)becomeFirstResponder;
- (void)finishEditAction:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

