//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class NSDate, NSMutableDictionary, NSString, NSTimer, PageIndicator, StyledPageControl, UIScrollView;

@interface YKuImageInLoopScrollView : UIView <UIScrollViewDelegate>
{
    int m_absolutePageIndex;
    int numOfPage;
    float oldOffsetX;
    _Bool skipSetContentOffset;
    UIScrollView *contentScrollView;
    NSMutableDictionary *addSubViewDictionary;
    struct CGSize sizeOfPage;
    NSDate *startDate;
    NSDate *endDate;
    NSTimer *repeatTimer;
    UIView *_currentView;
    UIView *_lastView;
    UIView *_nextView;
    int _scrollViewType;
    id <YKuImageInLoopScrollViewDelegate> delegate;
    StyledPageControl *_styledPageControl;
    PageIndicator *_pageIndicator;
}

@property(retain, nonatomic) PageIndicator *pageIndicator; // @synthesize pageIndicator=_pageIndicator;
@property(retain, nonatomic) StyledPageControl *styledPageControl; // @synthesize styledPageControl=_styledPageControl;
@property(nonatomic) int scrollViewType; // @synthesize scrollViewType=_scrollViewType;
@property(nonatomic) id <YKuImageInLoopScrollViewDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)timerInvalidate;
- (void)onSetContentOffset:(struct CGPoint)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)dealloc;
- (void)initPageIndicator;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)internalInit;
- (id)viewAtNextPage;
- (id)viewAtLastPage;
- (id)viewAtCurrentPage;
- (void)didTapIndex:(id)arg1;
- (void)reloadData;
- (void)timerFired:(id)arg1;
- (void)nextPage:(_Bool)arg1;
- (int)pageIndex;
- (void)setPageIndex:(int)arg1 animated:(_Bool)arg2;
- (int)absolutePageIndex;
- (void)setAbsolutePageIndex:(int)arg1;
- (void)setAbsolutePageIndex:(int)arg1 animated:(_Bool)arg2;
- (void)setAbsolutePageIndex:(int)arg1 animated:(_Bool)arg2 setContentOffset:(_Bool)arg3;
- (void)layoutPage:(int)arg1;
- (id)viewAtIndex:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

